// Code generated by gen/repo. DO NOT EDIT.
// Code generated by gen/repo. DO NOT EDIT.
// Code generated by gen/repo. DO NOT EDIT.

package ai_boilerplate_repo

import (
	"context"
	"errors"
	"reflect"
	"strings"

	"github.com/fzf-labs/ai-boilerplate-backend/internal/data/gorm/ai_boilerplate_dao"
	"github.com/fzf-labs/ai-boilerplate-backend/internal/data/gorm/ai_boilerplate_model"
	"github.com/fzf-labs/godb/orm/condition"
	"github.com/fzf-labs/godb/orm/dbcache"
	"github.com/fzf-labs/godb/orm/encoding"
	"github.com/fzf-labs/godb/orm/gen/config"
	"github.com/jinzhu/copier"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

var _ IDictTypeRepo = (*DictTypeRepo)(nil)

var (
	CacheDictTypeByConditionPrefix         = "DBCache:ai_boilerplate:DictTypeByCondition"
	CacheDictTypeUnscopedByConditionPrefix = "DBCache:ai_boilerplate:DictTypeUnscopedByCondition"
	CacheDictTypeByIDPrefix                = "DBCache:ai_boilerplate:DictTypeByID"
	CacheDictTypeUnscopedByIDPrefix        = "DBCache:ai_boilerplate:DictTypeUnscopedByID"
	CacheDictTypeByTypePrefix              = "DBCache:ai_boilerplate:DictTypeByType"
	CacheDictTypeUnscopedByTypePrefix      = "DBCache:ai_boilerplate:DictTypeUnscopedByType"
)

type (
	IDictTypeRepo interface {
		// NewData 实例化
		NewData() *ai_boilerplate_model.DictType
		// DeepCopy 深拷贝
		DeepCopy(data *ai_boilerplate_model.DictType) *ai_boilerplate_model.DictType
		// CreateOne 创建一条数据
		CreateOne(ctx context.Context, data *ai_boilerplate_model.DictType) error
		// CreateOneCache 创建一条数据, 并删除缓存
		CreateOneCache(ctx context.Context, data *ai_boilerplate_model.DictType) error
		// CreateOneByTx 创建一条数据(事务)
		CreateOneByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, data *ai_boilerplate_model.DictType) error
		// CreateOneCacheByTx 创建一条数据(事务), 并删除缓存
		CreateOneCacheByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, data *ai_boilerplate_model.DictType) error
		// CreateBatch 批量创建数据
		CreateBatch(ctx context.Context, data []*ai_boilerplate_model.DictType, batchSize int) error
		// CreateBatchCache 批量创建数据, 并删除缓存
		CreateBatchCache(ctx context.Context, data []*ai_boilerplate_model.DictType, batchSize int) error
		// CreateBatchByTx 批量创建数据(事务)
		CreateBatchByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, data []*ai_boilerplate_model.DictType, batchSize int) error
		// CreateBatchCacheByTx 批量创建数据(事务), 并删除缓存
		CreateBatchCacheByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, data []*ai_boilerplate_model.DictType, batchSize int) error
		// UpsertOne Upsert一条数据
		UpsertOne(ctx context.Context, data *ai_boilerplate_model.DictType) error
		// UpsertOneCache Upsert一条数据, 并删除缓存
		UpsertOneCache(ctx context.Context, data *ai_boilerplate_model.DictType) error
		// UpsertOneByTx Upsert一条数据(事务)
		UpsertOneByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, data *ai_boilerplate_model.DictType) error
		// UpsertOneCacheByTx Upsert一条数据(事务), 并删除缓存
		UpsertOneCacheByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, data *ai_boilerplate_model.DictType) error
		// UpsertOneByFields 根据fields字段Upsert一条数据
		UpsertOneByFields(ctx context.Context, data *ai_boilerplate_model.DictType, fields []string) error
		// UpsertOneCacheByFields 根据fields字段Upsert一条数据, 并删除缓存
		UpsertOneCacheByFields(ctx context.Context, data *ai_boilerplate_model.DictType, fields []string) error
		// UpsertOneByFieldsTx 根据fields字段Upsert一条数据(事务)
		UpsertOneByFieldsTx(ctx context.Context, tx *ai_boilerplate_dao.Query, data *ai_boilerplate_model.DictType, fields []string) error
		// UpsertOneCacheByFieldsTx 根据fields字段Upsert一条数据(事务), 并删除缓存
		UpsertOneCacheByFieldsTx(ctx context.Context, tx *ai_boilerplate_dao.Query, data *ai_boilerplate_model.DictType, fields []string) error
		// UpdateOne 更新一条数据
		UpdateOne(ctx context.Context, newData *ai_boilerplate_model.DictType) error
		// UpdateOneUnscoped 更新一条数据（包括软删除）
		UpdateOneUnscoped(ctx context.Context, newData *ai_boilerplate_model.DictType) error
		// UpdateOneCache 更新一条数据，并删除缓存
		UpdateOneCache(ctx context.Context, newData *ai_boilerplate_model.DictType, oldData *ai_boilerplate_model.DictType) error
		// UpdateOneUnscopedCache 更新一条数据，并删除缓存（包括软删除）
		UpdateOneUnscopedCache(ctx context.Context, newData *ai_boilerplate_model.DictType, oldData *ai_boilerplate_model.DictType) error
		// UpdateOneByTx 更新一条数据(事务)
		UpdateOneByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, newData *ai_boilerplate_model.DictType) error
		// UpdateOneUnscopedByTx 更新一条数据(事务)（包括软删除）
		UpdateOneUnscopedByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, newData *ai_boilerplate_model.DictType) error
		// UpdateOneCacheByTx 更新一条数据(事务)，并删除缓存
		UpdateOneCacheByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, newData *ai_boilerplate_model.DictType, oldData *ai_boilerplate_model.DictType) error
		// UpdateOneUnscopedCacheByTx 更新一条数据(事务)，并删除缓存（包括软删除）
		UpdateOneUnscopedCacheByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, newData *ai_boilerplate_model.DictType, oldData *ai_boilerplate_model.DictType) error
		// UpdateOneWithZero 更新一条数据,包含零值，并删除缓存
		UpdateOneWithZero(ctx context.Context, newData *ai_boilerplate_model.DictType) error
		// UpdateOneUnscopedWithZero 更新一条数据,包含零值（包括软删除）
		UpdateOneUnscopedWithZero(ctx context.Context, newData *ai_boilerplate_model.DictType) error
		// UpdateOneCacheWithZero 更新一条数据,包含零值，并删除缓存
		UpdateOneCacheWithZero(ctx context.Context, newData *ai_boilerplate_model.DictType, oldData *ai_boilerplate_model.DictType) error
		// UpdateOneUnscopedCacheWithZero 更新一条数据,包含零值，并删除缓存（包括软删除）
		UpdateOneUnscopedCacheWithZero(ctx context.Context, newData *ai_boilerplate_model.DictType, oldData *ai_boilerplate_model.DictType) error
		// UpdateOneWithZeroByTx 更新一条数据(事务),包含零值，并删除缓存
		UpdateOneWithZeroByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, newData *ai_boilerplate_model.DictType) error
		// UpdateOneUnscopedWithZeroByTx 更新一条数据(事务),包含零值（包括软删除）
		UpdateOneUnscopedWithZeroByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, newData *ai_boilerplate_model.DictType) error
		// UpdateOneCacheWithZeroByTx 更新一条数据(事务),包含零值，并删除缓存
		UpdateOneCacheWithZeroByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, newData *ai_boilerplate_model.DictType, oldData *ai_boilerplate_model.DictType) error
		// UpdateOneUnscopedCacheWithZeroByTx 更新一条数据(事务),包含零值，并删除缓存（包括软删除）
		UpdateOneUnscopedCacheWithZeroByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, newData *ai_boilerplate_model.DictType, oldData *ai_boilerplate_model.DictType) error
		// UpdateBatchByID 根据字段ID批量更新,零值会被更新
		UpdateBatchByID(ctx context.Context, ID string, data map[string]interface{}) error
		// UpdateBatchUnscopedByID 根据字段ID批量更新,零值会被更新（包括软删除）
		UpdateBatchUnscopedByID(ctx context.Context, ID string, data map[string]interface{}) error
		// UpdateBatchByIDTx 根据主键ID批量更新(事务),零值会被更新
		UpdateBatchByIDTx(ctx context.Context, tx *ai_boilerplate_dao.Query, ID string, data map[string]interface{}) error
		// UpdateBatchUnscopedByIDTx 根据主键ID批量更新(事务),零值会被更新（包括软删除）
		UpdateBatchUnscopedByIDTx(ctx context.Context, tx *ai_boilerplate_dao.Query, ID string, data map[string]interface{}) error
		// UpdateBatchByIDS 根据字段IDS批量更新,零值会被更新
		UpdateBatchByIDS(ctx context.Context, IDS []string, data map[string]interface{}) error
		// UpdateBatchUnscopedByIDS 根据字段IDS批量更新,零值会被更新（包括软删除）
		UpdateBatchUnscopedByIDS(ctx context.Context, IDS []string, data map[string]interface{}) error
		// UpdateBatchByIDSTx 根据字段IDS批量更新(事务),零值会被更新
		UpdateBatchByIDSTx(ctx context.Context, tx *ai_boilerplate_dao.Query, IDS []string, data map[string]interface{}) error
		// UpdateBatchUnscopedByIDSTx 根据字段IDS批量更新(事务),零值会被更新（包括软删除）
		UpdateBatchUnscopedByIDSTx(ctx context.Context, tx *ai_boilerplate_dao.Query, IDS []string, data map[string]interface{}) error
		// UpdateBatchByType 根据字段Type批量更新,零值会被更新
		UpdateBatchByType(ctx context.Context, _type string, data map[string]interface{}) error
		// UpdateBatchUnscopedByType 根据字段Type批量更新,零值会被更新（包括软删除）
		UpdateBatchUnscopedByType(ctx context.Context, _type string, data map[string]interface{}) error
		// UpdateBatchByTypeTx 根据主键Type批量更新(事务),零值会被更新
		UpdateBatchByTypeTx(ctx context.Context, tx *ai_boilerplate_dao.Query, _type string, data map[string]interface{}) error
		// UpdateBatchUnscopedByTypeTx 根据主键Type批量更新(事务),零值会被更新（包括软删除）
		UpdateBatchUnscopedByTypeTx(ctx context.Context, tx *ai_boilerplate_dao.Query, _type string, data map[string]interface{}) error
		// UpdateBatchByTypes 根据字段Types批量更新,零值会被更新
		UpdateBatchByTypes(ctx context.Context, _types []string, data map[string]interface{}) error
		// UpdateBatchUnscopedByTypes 根据字段Types批量更新,零值会被更新（包括软删除）
		UpdateBatchUnscopedByTypes(ctx context.Context, _types []string, data map[string]interface{}) error
		// UpdateBatchByTypesTx 根据字段Types批量更新(事务),零值会被更新
		UpdateBatchByTypesTx(ctx context.Context, tx *ai_boilerplate_dao.Query, _types []string, data map[string]interface{}) error
		// UpdateBatchUnscopedByTypesTx 根据字段Types批量更新(事务),零值会被更新（包括软删除）
		UpdateBatchUnscopedByTypesTx(ctx context.Context, tx *ai_boilerplate_dao.Query, _types []string, data map[string]interface{}) error
		// FindOneByID 根据ID查询一条数据
		FindOneByID(ctx context.Context, ID string) (*ai_boilerplate_model.DictType, error)
		// FindOneUnscopedByID 根据ID查询一条数据（包括软删除）
		FindOneUnscopedByID(ctx context.Context, ID string) (*ai_boilerplate_model.DictType, error)
		// FindOneCacheByID 根据ID查询一条数据，并设置缓存
		FindOneCacheByID(ctx context.Context, ID string) (*ai_boilerplate_model.DictType, error)
		// FindOneUnscopedCacheByID 根据ID查询一条数据（包括软删除），并设置缓存
		FindOneUnscopedCacheByID(ctx context.Context, ID string) (*ai_boilerplate_model.DictType, error)
		// FindMultiByIDS 根据IDS查询多条数据
		FindMultiByIDS(ctx context.Context, IDS []string) ([]*ai_boilerplate_model.DictType, error)
		// FindMultiUnscopedByIDS 根据IDS查询多条数据（包括软删除）
		FindMultiUnscopedByIDS(ctx context.Context, IDS []string) ([]*ai_boilerplate_model.DictType, error)
		// FindMultiCacheByIDS 根据IDS查询多条数据，并设置缓存
		FindMultiCacheByIDS(ctx context.Context, IDS []string) ([]*ai_boilerplate_model.DictType, error)
		// FindMultiUnscopedCacheByIDS 根据IDS查询多条数据（包括软删除），并设置缓存
		FindMultiUnscopedCacheByIDS(ctx context.Context, IDS []string) ([]*ai_boilerplate_model.DictType, error)
		// FindOneByType 根据_type查询一条数据
		FindOneByType(ctx context.Context, _type string) (*ai_boilerplate_model.DictType, error)
		// FindOneUnscopedByType 根据_type查询一条数据（包括软删除）
		FindOneUnscopedByType(ctx context.Context, _type string) (*ai_boilerplate_model.DictType, error)
		// FindOneCacheByType 根据_type查询一条数据，并设置缓存
		FindOneCacheByType(ctx context.Context, _type string) (*ai_boilerplate_model.DictType, error)
		// FindOneUnscopedCacheByType 根据_type查询一条数据（包括软删除），并设置缓存
		FindOneUnscopedCacheByType(ctx context.Context, _type string) (*ai_boilerplate_model.DictType, error)
		// FindMultiByTypes 根据_types查询多条数据
		FindMultiByTypes(ctx context.Context, _types []string) ([]*ai_boilerplate_model.DictType, error)
		// FindMultiUnscopedByTypes 根据_types查询多条数据（包括软删除）
		FindMultiUnscopedByTypes(ctx context.Context, _types []string) ([]*ai_boilerplate_model.DictType, error)
		// FindMultiCacheByTypes 根据_types查询多条数据，并设置缓存
		FindMultiCacheByTypes(ctx context.Context, _types []string) ([]*ai_boilerplate_model.DictType, error)
		// FindMultiUnscopedCacheByTypes 根据_types查询多条数据（包括软删除），并设置缓存
		FindMultiUnscopedCacheByTypes(ctx context.Context, _types []string) ([]*ai_boilerplate_model.DictType, error)
		// FindMultiByCondition 自定义查询数据(通用)
		FindMultiByCondition(ctx context.Context, conditionReq *condition.Req) ([]*ai_boilerplate_model.DictType, *condition.Reply, error)
		// FindMultiUnscopedByCondition 自定义查询数据(通用)（包括软删除）
		FindMultiUnscopedByCondition(ctx context.Context, conditionReq *condition.Req) ([]*ai_boilerplate_model.DictType, *condition.Reply, error)
		// FindMultiCacheByCondition 自定义查询数据(通用),并设置缓存
		FindMultiCacheByCondition(ctx context.Context, conditionReq *condition.Req) ([]*ai_boilerplate_model.DictType, *condition.Reply, error)
		// FindMultiUnscopedCacheByCondition 自定义查询数据(通用)（包括软删除）,并设置缓存
		FindMultiUnscopedCacheByCondition(ctx context.Context, conditionReq *condition.Req) ([]*ai_boilerplate_model.DictType, *condition.Reply, error)
		// DeleteOneByID 根据ID删除一条数据
		DeleteOneByID(ctx context.Context, ID string) error
		// DeleteOneUnscopedByID 根据ID删除一条数据
		DeleteOneUnscopedByID(ctx context.Context, ID string) error
		// DeleteOneCacheByID 根据ID删除一条数据，并删除缓存
		DeleteOneCacheByID(ctx context.Context, ID string) error
		// DeleteOneUnscopedCacheByID 根据ID删除一条数据，并删除缓存
		DeleteOneUnscopedCacheByID(ctx context.Context, ID string) error
		// DeleteOneByIDTx 根据ID删除一条数据(事务)
		DeleteOneByIDTx(ctx context.Context, tx *ai_boilerplate_dao.Query, ID string) error
		// DeleteOneUnscopedByIDTx 根据ID删除一条数据(事务)
		DeleteOneUnscopedByIDTx(ctx context.Context, tx *ai_boilerplate_dao.Query, ID string) error
		// DeleteOneCacheByIDTx 根据ID删除一条数据，并删除缓存(事务)
		DeleteOneCacheByIDTx(ctx context.Context, tx *ai_boilerplate_dao.Query, ID string) error
		// DeleteOneUnscopedCacheByIDTx 根据ID删除一条数据，并删除缓存(事务)
		DeleteOneUnscopedCacheByIDTx(ctx context.Context, tx *ai_boilerplate_dao.Query, ID string) error
		// DeleteMultiByIDS 根据IDS删除多条数据
		DeleteMultiByIDS(ctx context.Context, IDS []string) error
		// DeleteMultiUnscopedByIDS 根据IDS删除多条数据
		DeleteMultiUnscopedByIDS(ctx context.Context, IDS []string) error
		// DeleteMultiCacheByIDS 根据IDS删除多条数据，并删除缓存
		DeleteMultiCacheByIDS(ctx context.Context, IDS []string) error
		// DeleteMultiUnscopedCacheByIDS 根据IDS删除多条数据，并删除缓存
		DeleteMultiUnscopedCacheByIDS(ctx context.Context, IDS []string) error
		// DeleteMultiByIDSTx 根据IDS删除多条数据(事务)
		DeleteMultiByIDSTx(ctx context.Context, tx *ai_boilerplate_dao.Query, IDS []string) error
		// DeleteMultiUnscopedByIDSTx 根据IDS删除多条数据(事务)
		DeleteMultiUnscopedByIDSTx(ctx context.Context, tx *ai_boilerplate_dao.Query, IDS []string) error
		// DeleteMultiCacheByIDSTx 根据IDS删除多条数据，并删除缓存(事务)
		DeleteMultiCacheByIDSTx(ctx context.Context, tx *ai_boilerplate_dao.Query, IDS []string) error
		// DeleteMultiUnscopedCacheByIDSTx 根据IDS删除多条数据，并删除缓存(事务)
		DeleteMultiUnscopedCacheByIDSTx(ctx context.Context, tx *ai_boilerplate_dao.Query, IDS []string) error
		// DeleteOneByType 根据_type删除一条数据
		DeleteOneByType(ctx context.Context, _type string) error
		// DeleteOneUnscopedByType 根据_type删除一条数据
		DeleteOneUnscopedByType(ctx context.Context, _type string) error
		// DeleteOneCacheByType 根据_type删除一条数据，并删除缓存
		DeleteOneCacheByType(ctx context.Context, _type string) error
		// DeleteOneUnscopedCacheByType 根据_type删除一条数据，并删除缓存
		DeleteOneUnscopedCacheByType(ctx context.Context, _type string) error
		// DeleteOneByTypeTx 根据_type删除一条数据(事务)
		DeleteOneByTypeTx(ctx context.Context, tx *ai_boilerplate_dao.Query, _type string) error
		// DeleteOneUnscopedByTypeTx 根据_type删除一条数据(事务)
		DeleteOneUnscopedByTypeTx(ctx context.Context, tx *ai_boilerplate_dao.Query, _type string) error
		// DeleteOneCacheByTypeTx 根据_type删除一条数据，并删除缓存(事务)
		DeleteOneCacheByTypeTx(ctx context.Context, tx *ai_boilerplate_dao.Query, _type string) error
		// DeleteOneUnscopedCacheByTypeTx 根据_type删除一条数据，并删除缓存(事务)
		DeleteOneUnscopedCacheByTypeTx(ctx context.Context, tx *ai_boilerplate_dao.Query, _type string) error
		// DeleteMultiByTypes 根据Types删除多条数据
		DeleteMultiByTypes(ctx context.Context, _types []string) error
		// DeleteMultiUnscopedByTypes 根据Types删除多条数据
		DeleteMultiUnscopedByTypes(ctx context.Context, _types []string) error
		// DeleteMultiCacheByTypes 根据Types删除多条数据，并删除缓存
		DeleteMultiCacheByTypes(ctx context.Context, _types []string) error
		// DeleteMultiUnscopedCacheByTypes 根据Types删除多条数据，并删除缓存
		DeleteMultiUnscopedCacheByTypes(ctx context.Context, _types []string) error
		// DeleteMultiByTypesTx 根据Types删除多条数据(事务)
		DeleteMultiByTypesTx(ctx context.Context, tx *ai_boilerplate_dao.Query, _types []string) error
		// DeleteMultiUnscopedByTypesTx 根据Types删除多条数据(事务)
		DeleteMultiUnscopedByTypesTx(ctx context.Context, tx *ai_boilerplate_dao.Query, _types []string) error
		// DeleteMultiCacheByTypesTx 根据Types删除多条数据，并删除缓存(事务)
		DeleteMultiCacheByTypesTx(ctx context.Context, tx *ai_boilerplate_dao.Query, _types []string) error
		// DeleteMultiUnscopedCacheByTypesTx 根据Types删除多条数据，并删除缓存(事务)
		DeleteMultiUnscopedCacheByTypesTx(ctx context.Context, tx *ai_boilerplate_dao.Query, _types []string) error
		// DeleteIndexCache 删除索引存在的缓存
		DeleteIndexCache(ctx context.Context, data ...*ai_boilerplate_model.DictType) error
	}
	DictTypeRepo struct {
		db       *gorm.DB
		cache    dbcache.IDBCache
		encoding encoding.API
	}
)

func NewDictTypeRepo(cfg *config.Repo) *DictTypeRepo {
	return &DictTypeRepo{
		db:       cfg.DB,
		cache:    cfg.Cache,
		encoding: cfg.Encoding,
	}
}

// NewData 实例化
func (d *DictTypeRepo) NewData() *ai_boilerplate_model.DictType {
	return &ai_boilerplate_model.DictType{}
}

// DeepCopy 深拷贝
func (d *DictTypeRepo) DeepCopy(data *ai_boilerplate_model.DictType) *ai_boilerplate_model.DictType {
	newData := new(ai_boilerplate_model.DictType)
	_ = copier.CopyWithOption(newData, data, copier.Option{DeepCopy: true})
	return newData
}

// CreateOne 创建一条数据
func (d *DictTypeRepo) CreateOne(ctx context.Context, data *ai_boilerplate_model.DictType) error {
	dao := ai_boilerplate_dao.Use(d.db).DictType
	err := dao.WithContext(ctx).Create(data)
	if err != nil {
		return err
	}
	return nil
}

// CreateOneCache 创建一条数据, 并删除缓存
func (d *DictTypeRepo) CreateOneCache(ctx context.Context, data *ai_boilerplate_model.DictType) error {
	dao := ai_boilerplate_dao.Use(d.db).DictType
	err := dao.WithContext(ctx).Create(data)
	if err != nil {
		return err
	}
	err = d.DeleteIndexCache(ctx, data)
	if err != nil {
		return err
	}
	return nil
}

// CreateOneByTx 创建一条数据(事务)
func (d *DictTypeRepo) CreateOneByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, data *ai_boilerplate_model.DictType) error {
	dao := tx.DictType
	err := dao.WithContext(ctx).Create(data)
	if err != nil {
		return err
	}
	return nil
}

// CreateOneCacheByTx 创建一条数据(事务), 并删除缓存
func (d *DictTypeRepo) CreateOneCacheByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, data *ai_boilerplate_model.DictType) error {
	dao := tx.DictType
	err := dao.WithContext(ctx).Create(data)
	if err != nil {
		return err
	}
	err = d.DeleteIndexCache(ctx, data)
	if err != nil {
		return err
	}
	return nil
}

// CreateBatch 批量创建数据
func (d *DictTypeRepo) CreateBatch(ctx context.Context, data []*ai_boilerplate_model.DictType, batchSize int) error {
	dao := ai_boilerplate_dao.Use(d.db).DictType
	err := dao.WithContext(ctx).CreateInBatches(data, batchSize)
	if err != nil {
		return err
	}
	return nil
}

// CreateBatchCache 批量创建数据, 并删除缓存
func (d *DictTypeRepo) CreateBatchCache(ctx context.Context, data []*ai_boilerplate_model.DictType, batchSize int) error {
	dao := ai_boilerplate_dao.Use(d.db).DictType
	err := dao.WithContext(ctx).CreateInBatches(data, batchSize)
	if err != nil {
		return err
	}
	err = d.DeleteIndexCache(ctx, data...)
	if err != nil {
		return err
	}
	return nil
}

// CreateBatchByTx 批量创建数据(事务)
func (d *DictTypeRepo) CreateBatchByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, data []*ai_boilerplate_model.DictType, batchSize int) error {
	dao := tx.DictType
	err := dao.WithContext(ctx).CreateInBatches(data, batchSize)
	if err != nil {
		return err
	}
	return nil
}

// CreateBatchCacheByTx 批量创建数据(事务), 并删除缓存
func (d *DictTypeRepo) CreateBatchCacheByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, data []*ai_boilerplate_model.DictType, batchSize int) error {
	dao := tx.DictType
	err := dao.WithContext(ctx).CreateInBatches(data, batchSize)
	if err != nil {
		return err
	}
	err = d.DeleteIndexCache(ctx, data...)
	if err != nil {
		return err
	}
	return nil
}

// UpsertOne Upsert一条数据
// Update all columns, except primary keys, to new value on conflict
func (d *DictTypeRepo) UpsertOne(ctx context.Context, data *ai_boilerplate_model.DictType) error {
	dao := ai_boilerplate_dao.Use(d.db).DictType
	err := dao.WithContext(ctx).Save(data)
	if err != nil {
		return err
	}
	return nil
}

// UpsertOneCache Upsert一条数据, 并删除缓存
// Update all columns, except primary keys, to new value on conflict
func (d *DictTypeRepo) UpsertOneCache(ctx context.Context, data *ai_boilerplate_model.DictType) error {
	dao := ai_boilerplate_dao.Use(d.db).DictType
	oldData, err := dao.WithContext(ctx).Where(dao.ID.Eq(data.ID)).Unscoped().First()
	if err != nil && !errors.Is(err, gorm.ErrRecordNotFound) {
		return err
	}
	err = dao.WithContext(ctx).Save(data)
	if err != nil {
		return err
	}
	err = d.DeleteIndexCache(ctx, oldData, data)
	if err != nil {
		return err
	}
	return nil
}

// UpsertOneByTx Upsert一条数据(事务)
// Update all columns, except primary keys, to new value on conflict
func (d *DictTypeRepo) UpsertOneByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, data *ai_boilerplate_model.DictType) error {
	dao := tx.DictType
	err := dao.WithContext(ctx).Save(data)
	if err != nil {
		return err
	}
	return nil
}

// UpsertOneCacheByTx Upsert一条数据(事务), 并删除缓存
// Update all columns, except primary keys, to new value on conflict
func (d *DictTypeRepo) UpsertOneCacheByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, data *ai_boilerplate_model.DictType) error {
	dao := tx.DictType
	oldData, err := dao.WithContext(ctx).Where(dao.ID.Eq(data.ID)).Unscoped().First()
	if err != nil && !errors.Is(err, gorm.ErrRecordNotFound) {
		return err
	}
	err = dao.WithContext(ctx).Save(data)
	if err != nil {
		return err
	}
	err = d.DeleteIndexCache(ctx, oldData, data)
	if err != nil {
		return err
	}
	return nil
}

// UpsertOneByFields 根据fields字段Upsert一条数据
func (d *DictTypeRepo) UpsertOneByFields(ctx context.Context, data *ai_boilerplate_model.DictType, fields []string) error {
	if len(fields) == 0 {
		return errors.New("UpsertOneByFields fields is empty")
	}
	columns := make([]clause.Column, 0)
	for _, item := range fields {
		columns = append(columns, clause.Column{Name: item})
	}
	dao := ai_boilerplate_dao.Use(d.db).DictType
	err := dao.WithContext(ctx).Clauses(clause.OnConflict{
		Columns:   columns,
		UpdateAll: true,
	}).Create(data)
	if err != nil {
		return err
	}
	return nil
}

// UpsertOneCacheByFields 根据fields字段Upsert一条数据, 并删除缓存
func (d *DictTypeRepo) UpsertOneCacheByFields(ctx context.Context, data *ai_boilerplate_model.DictType, fields []string) error {
	if len(fields) == 0 {
		return errors.New("UpsertOneByFields fields is empty")
	}
	fieldNameToValue := make(map[string]interface{})
	typ := reflect.TypeOf(data).Elem()
	val := reflect.ValueOf(data).Elem()
	for i := 0; i < typ.NumField(); i++ {
		field := typ.Field(i)
		gormTag := field.Tag.Get("gorm")
		if gormTag != "" {
			gormTags := strings.Split(gormTag, ";")
			for _, item := range gormTags {
				if strings.Contains(item, "column") {
					columnName := strings.TrimPrefix(item, "column:")
					fieldValue := val.Field(i).Interface()
					fieldNameToValue[columnName] = fieldValue
					break
				}
			}
		}
	}
	whereExpressions := make([]clause.Expression, 0)
	columns := make([]clause.Column, 0)
	for _, item := range fields {
		whereExpressions = append(whereExpressions, clause.And(clause.Eq{Column: item, Value: fieldNameToValue[item]}))
		columns = append(columns, clause.Column{Name: item})
	}
	oldData := &ai_boilerplate_model.DictType{}
	err := d.db.Model(&ai_boilerplate_model.DictType{}).Clauses(whereExpressions...).Unscoped().First(oldData).Error
	if err != nil && !errors.Is(err, gorm.ErrRecordNotFound) {
		return err
	}
	dao := ai_boilerplate_dao.Use(d.db).DictType
	err = dao.WithContext(ctx).Clauses(clause.OnConflict{
		Columns:   columns,
		UpdateAll: true,
	}).Create(data)
	if err != nil {
		return err
	}
	err = d.DeleteIndexCache(ctx, oldData, data)
	if err != nil {
		return err
	}
	return nil
}

// UpsertOneByFieldsTx 根据fields字段Upsert一条数据(事务)
func (d *DictTypeRepo) UpsertOneByFieldsTx(ctx context.Context, tx *ai_boilerplate_dao.Query, data *ai_boilerplate_model.DictType, fields []string) error {
	if len(fields) == 0 {
		return errors.New("UpsertOneByFieldsTx fields is empty")
	}
	columns := make([]clause.Column, 0)
	for _, item := range fields {
		columns = append(columns, clause.Column{Name: item})
	}
	dao := tx.DictType
	err := dao.WithContext(ctx).Clauses(clause.OnConflict{
		Columns:   columns,
		UpdateAll: true,
	}).Create(data)
	if err != nil {
		return err
	}
	return nil
}

// UpsertOneCacheByFieldsTx 根据fields字段Upsert一条数据(事务), 并删除缓存
func (d *DictTypeRepo) UpsertOneCacheByFieldsTx(ctx context.Context, tx *ai_boilerplate_dao.Query, data *ai_boilerplate_model.DictType, fields []string) error {
	if len(fields) == 0 {
		return errors.New("UpsertOneByFieldsTx fields is empty")
	}
	fieldNameToValue := make(map[string]interface{})
	typ := reflect.TypeOf(data).Elem()
	val := reflect.ValueOf(data).Elem()
	for i := 0; i < typ.NumField(); i++ {
		field := typ.Field(i)
		gormTag := field.Tag.Get("gorm")
		if gormTag != "" {
			gormTags := strings.Split(gormTag, ";")
			for _, item := range gormTags {
				if strings.Contains(item, "column") {
					columnName := strings.TrimPrefix(item, "column:")
					fieldValue := val.Field(i).Interface()
					fieldNameToValue[columnName] = fieldValue
					break
				}
			}
		}
	}
	whereExpressions := make([]clause.Expression, 0)
	columns := make([]clause.Column, 0)
	for _, item := range fields {
		whereExpressions = append(whereExpressions, clause.And(clause.Eq{Column: item, Value: fieldNameToValue[item]}))
		columns = append(columns, clause.Column{Name: item})
	}
	oldData := &ai_boilerplate_model.DictType{}
	err := d.db.Model(&ai_boilerplate_model.DictType{}).Clauses(whereExpressions...).Unscoped().First(oldData).Error
	if err != nil && !errors.Is(err, gorm.ErrRecordNotFound) {
		return err
	}
	dao := tx.DictType
	err = dao.WithContext(ctx).Clauses(clause.OnConflict{
		Columns:   columns,
		UpdateAll: true,
	}).Create(data)
	if err != nil {
		return err
	}
	err = d.DeleteIndexCache(ctx, oldData, data)
	if err != nil {
		return err
	}
	return nil
}

// UpdateOne 更新一条数据
// data 中主键字段必须有值，零值不会被更新
func (d *DictTypeRepo) UpdateOne(ctx context.Context, newData *ai_boilerplate_model.DictType) error {
	dao := ai_boilerplate_dao.Use(d.db).DictType
	_, err := dao.WithContext(ctx).Updates(newData)
	if err != nil {
		return err
	}
	return nil
}

// UpdateOneUnscoped 更新一条数据（包括软删除）
// data 中主键字段必须有值，零值不会被更新
func (d *DictTypeRepo) UpdateOneUnscoped(ctx context.Context, newData *ai_boilerplate_model.DictType) error {
	dao := ai_boilerplate_dao.Use(d.db).DictType
	_, err := dao.WithContext(ctx).Unscoped().Updates(newData)
	if err != nil {
		return err
	}
	return nil
}

// UpdateOneCache 更新一条数据，并删除缓存
// data 中主键字段必须有值，零值不会被更新
// oldData 旧数据，删除缓存时使用
func (d *DictTypeRepo) UpdateOneCache(ctx context.Context, newData *ai_boilerplate_model.DictType, oldData *ai_boilerplate_model.DictType) error {
	dao := ai_boilerplate_dao.Use(d.db).DictType
	_, err := dao.WithContext(ctx).Updates(newData)
	if err != nil {
		return err
	}
	err = d.DeleteIndexCache(ctx, oldData, newData)
	if err != nil {
		return err
	}
	return nil
}

// UpdateOneUnscopedCache 更新一条数据，并删除缓存（包括软删除）
// data 中主键字段必须有值，零值不会被更新
// oldData 旧数据，删除缓存时使用
func (d *DictTypeRepo) UpdateOneUnscopedCache(ctx context.Context, newData *ai_boilerplate_model.DictType, oldData *ai_boilerplate_model.DictType) error {
	dao := ai_boilerplate_dao.Use(d.db).DictType
	_, err := dao.WithContext(ctx).Unscoped().Updates(newData)
	if err != nil {
		return err
	}
	err = d.DeleteIndexCache(ctx, oldData, newData)
	if err != nil {
		return err
	}
	return nil
}

// UpdateOneByTx 更新一条数据(事务)
// data 中主键字段必须有值，零值不会被更新
func (d *DictTypeRepo) UpdateOneByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, newData *ai_boilerplate_model.DictType) error {
	dao := tx.DictType
	_, err := dao.WithContext(ctx).Updates(newData)
	if err != nil {
		return err
	}
	return nil
}

// UpdateOneUnscopedByTx 更新一条数据(事务)（包括软删除）
// data 中主键字段必须有值，零值不会被更新
func (d *DictTypeRepo) UpdateOneUnscopedByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, newData *ai_boilerplate_model.DictType) error {
	dao := tx.DictType
	_, err := dao.WithContext(ctx).Unscoped().Updates(newData)
	if err != nil {
		return err
	}
	return nil
}

// UpdateOneCacheByTx 更新一条数据(事务)，并删除缓存
// data 中主键字段必须有值，零值不会被更新
// oldData 旧数据，删除缓存时使用
func (d *DictTypeRepo) UpdateOneCacheByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, newData *ai_boilerplate_model.DictType, oldData *ai_boilerplate_model.DictType) error {
	dao := tx.DictType
	_, err := dao.WithContext(ctx).Updates(newData)
	if err != nil {
		return err
	}
	err = d.DeleteIndexCache(ctx, oldData, newData)
	if err != nil {
		return err
	}
	return nil
}

// UpdateOneUnscopedCacheByTx 更新一条数据(事务)，并删除缓存（包括软删除）
// data 中主键字段必须有值，零值不会被更新
// oldData 旧数据，删除缓存时使用
func (d *DictTypeRepo) UpdateOneUnscopedCacheByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, newData *ai_boilerplate_model.DictType, oldData *ai_boilerplate_model.DictType) error {
	dao := tx.DictType
	_, err := dao.WithContext(ctx).Unscoped().Updates(newData)
	if err != nil {
		return err
	}
	err = d.DeleteIndexCache(ctx, oldData, newData)
	if err != nil {
		return err
	}
	return nil
}

// UpdateOneWithZero 更新一条数据,包含零值
// data 中主键字段必须有值,并且会更新所有字段,包括零值
func (d *DictTypeRepo) UpdateOneWithZero(ctx context.Context, newData *ai_boilerplate_model.DictType) error {
	dao := ai_boilerplate_dao.Use(d.db).DictType
	_, err := dao.WithContext(ctx).Select(dao.ALL.WithTable("")).Updates(newData)
	if err != nil {
		return err
	}
	return nil
}

// UpdateOneUnscopedWithZero 更新一条数据,包含零值（包括软删除）
// data 中主键字段必须有值,并且会更新所有字段,包括零值
func (d *DictTypeRepo) UpdateOneUnscopedWithZero(ctx context.Context, newData *ai_boilerplate_model.DictType) error {
	dao := ai_boilerplate_dao.Use(d.db).DictType
	_, err := dao.WithContext(ctx).Unscoped().Select(dao.ALL.WithTable("")).Updates(newData)
	if err != nil {
		return err
	}
	return nil
}

// UpdateOneCacheWithZero 更新一条数据,包含零值，并删除缓存
// data 中主键字段必须有值,并且会更新所有字段,包括零值
// oldData 旧数据，删除缓存时使用
func (d *DictTypeRepo) UpdateOneCacheWithZero(ctx context.Context, newData *ai_boilerplate_model.DictType, oldData *ai_boilerplate_model.DictType) error {
	dao := ai_boilerplate_dao.Use(d.db).DictType
	_, err := dao.WithContext(ctx).Select(dao.ALL.WithTable("")).Updates(newData)
	if err != nil {
		return err
	}
	err = d.DeleteIndexCache(ctx, oldData, newData)
	if err != nil {
		return err
	}
	return nil
}

// UpdateOneUnscopedCacheWithZero 更新一条数据,包含零值，并删除缓存（包括软删除）
// data 中主键字段必须有值,并且会更新所有字段,包括零值
// oldData 旧数据，删除缓存时使用
func (d *DictTypeRepo) UpdateOneUnscopedCacheWithZero(ctx context.Context, newData *ai_boilerplate_model.DictType, oldData *ai_boilerplate_model.DictType) error {
	dao := ai_boilerplate_dao.Use(d.db).DictType
	_, err := dao.WithContext(ctx).Unscoped().Select(dao.ALL.WithTable("")).Updates(newData)
	if err != nil {
		return err
	}
	err = d.DeleteIndexCache(ctx, oldData, newData)
	if err != nil {
		return err
	}
	return nil
}

// UpdateOneWithZeroByTx 更新一条数据(事务),包含零值，
// data 中主键字段必须有值,并且会更新所有字段,包括零值
func (d *DictTypeRepo) UpdateOneWithZeroByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, newData *ai_boilerplate_model.DictType) error {
	dao := tx.DictType
	_, err := dao.WithContext(ctx).Select(dao.ALL.WithTable("")).Updates(newData)
	if err != nil {
		return err
	}
	return nil
}

// UpdateOneUnscopedWithZeroByTx 更新一条数据(事务),包含零值（包括软删除）
// data 中主键字段必须有值,并且会更新所有字段,包括零值
func (d *DictTypeRepo) UpdateOneUnscopedWithZeroByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, newData *ai_boilerplate_model.DictType) error {
	dao := tx.DictType
	_, err := dao.WithContext(ctx).Unscoped().Select(dao.ALL.WithTable("")).Updates(newData)
	if err != nil {
		return err
	}
	return nil
}

// UpdateOneCacheWithZeroByTx 更新一条数据(事务),包含零值，并删除缓存
// data 中主键字段必须有值,并且会更新所有字段,包括零值
// oldData 旧数据，删除缓存时使用
func (d *DictTypeRepo) UpdateOneCacheWithZeroByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, newData *ai_boilerplate_model.DictType, oldData *ai_boilerplate_model.DictType) error {
	dao := tx.DictType
	_, err := dao.WithContext(ctx).Select(dao.ALL.WithTable("")).Updates(newData)
	if err != nil {
		return err
	}
	err = d.DeleteIndexCache(ctx, oldData, newData)
	if err != nil {
		return err
	}
	return nil
}

// UpdateOneUnscopedCacheWithZeroByTx 更新一条数据(事务),包含零值，并删除缓存（包括软删除）
// data 中主键字段必须有值,并且会更新所有字段,包括零值
// oldData 旧数据，删除缓存时使用
func (d *DictTypeRepo) UpdateOneUnscopedCacheWithZeroByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, newData *ai_boilerplate_model.DictType, oldData *ai_boilerplate_model.DictType) error {
	dao := tx.DictType
	_, err := dao.WithContext(ctx).Unscoped().Select(dao.ALL.WithTable("")).Updates(newData)
	if err != nil {
		return err
	}
	err = d.DeleteIndexCache(ctx, oldData, newData)
	if err != nil {
		return err
	}
	return nil
}

// UpdateBatchByID 根据字段ID批量更新,零值会被更新
func (d *DictTypeRepo) UpdateBatchByID(ctx context.Context, ID string, data map[string]interface{}) error {
	dao := ai_boilerplate_dao.Use(d.db).DictType
	_, err := dao.WithContext(ctx).Where(dao.ID.Eq(ID)).Updates(data)
	if err != nil {
		return err
	}
	return nil
}

// UpdateBatchUnscopedByID 根据字段ID批量更新,零值会被更新（包括软删除）
func (d *DictTypeRepo) UpdateBatchUnscopedByID(ctx context.Context, ID string, data map[string]interface{}) error {
	dao := ai_boilerplate_dao.Use(d.db).DictType
	_, err := dao.WithContext(ctx).Unscoped().Where(dao.ID.Eq(ID)).Updates(data)
	if err != nil {
		return err
	}
	return nil
}

// UpdateBatchByIDTx 根据字段ID批量更新(事务),零值会被更新
func (d *DictTypeRepo) UpdateBatchByIDTx(ctx context.Context, tx *ai_boilerplate_dao.Query, ID string, data map[string]interface{}) error {
	dao := tx.DictType
	_, err := dao.WithContext(ctx).Where(dao.ID.Eq(ID)).Updates(data)
	if err != nil {
		return err
	}
	return nil
}

// UpdateBatchUnscopedByIDTx 根据字段ID批量更新(事务),零值会被更新（包括软删除）
func (d *DictTypeRepo) UpdateBatchUnscopedByIDTx(ctx context.Context, tx *ai_boilerplate_dao.Query, ID string, data map[string]interface{}) error {
	dao := tx.DictType
	_, err := dao.WithContext(ctx).Unscoped().Where(dao.ID.Eq(ID)).Updates(data)
	if err != nil {
		return err
	}
	return nil
}

// UpdateBatchByIDS 根据字段IDS批量更新,零值会被更新
func (d *DictTypeRepo) UpdateBatchByIDS(ctx context.Context, IDS []string, data map[string]interface{}) error {
	dao := ai_boilerplate_dao.Use(d.db).DictType
	_, err := dao.WithContext(ctx).Where(dao.ID.In(IDS...)).Updates(data)
	if err != nil {
		return err
	}
	return nil
}

// UpdateBatchUnscopedByIDS 根据字段IDS批量更新,零值会被更新（包括软删除）
func (d *DictTypeRepo) UpdateBatchUnscopedByIDS(ctx context.Context, IDS []string, data map[string]interface{}) error {
	dao := ai_boilerplate_dao.Use(d.db).DictType
	_, err := dao.WithContext(ctx).Unscoped().Where(dao.ID.In(IDS...)).Updates(data)
	if err != nil {
		return err
	}
	return nil
}

// UpdateBatchByIDSTx 根据字段IDS批量更新(事务),零值会被更新
func (d *DictTypeRepo) UpdateBatchByIDSTx(ctx context.Context, tx *ai_boilerplate_dao.Query, IDS []string, data map[string]interface{}) error {
	dao := tx.DictType
	_, err := dao.WithContext(ctx).Where(dao.ID.In(IDS...)).Updates(data)
	if err != nil {
		return err
	}
	return nil
}

// UpdateBatchUnscopedByIDSTx 根据字段IDS批量更新(事务),零值会被更新（包括软删除）
func (d *DictTypeRepo) UpdateBatchUnscopedByIDSTx(ctx context.Context, tx *ai_boilerplate_dao.Query, IDS []string, data map[string]interface{}) error {
	dao := tx.DictType
	_, err := dao.WithContext(ctx).Unscoped().Where(dao.ID.In(IDS...)).Updates(data)
	if err != nil {
		return err
	}
	return nil
}

// UpdateBatchByType 根据字段Type批量更新,零值会被更新
func (d *DictTypeRepo) UpdateBatchByType(ctx context.Context, _type string, data map[string]interface{}) error {
	dao := ai_boilerplate_dao.Use(d.db).DictType
	_, err := dao.WithContext(ctx).Where(dao.Type.Eq(_type)).Updates(data)
	if err != nil {
		return err
	}
	return nil
}

// UpdateBatchUnscopedByType 根据字段Type批量更新,零值会被更新（包括软删除）
func (d *DictTypeRepo) UpdateBatchUnscopedByType(ctx context.Context, _type string, data map[string]interface{}) error {
	dao := ai_boilerplate_dao.Use(d.db).DictType
	_, err := dao.WithContext(ctx).Unscoped().Where(dao.Type.Eq(_type)).Updates(data)
	if err != nil {
		return err
	}
	return nil
}

// UpdateBatchByTypeTx 根据字段Type批量更新(事务),零值会被更新
func (d *DictTypeRepo) UpdateBatchByTypeTx(ctx context.Context, tx *ai_boilerplate_dao.Query, _type string, data map[string]interface{}) error {
	dao := tx.DictType
	_, err := dao.WithContext(ctx).Where(dao.Type.Eq(_type)).Updates(data)
	if err != nil {
		return err
	}
	return nil
}

// UpdateBatchUnscopedByTypeTx 根据字段Type批量更新(事务),零值会被更新（包括软删除）
func (d *DictTypeRepo) UpdateBatchUnscopedByTypeTx(ctx context.Context, tx *ai_boilerplate_dao.Query, _type string, data map[string]interface{}) error {
	dao := tx.DictType
	_, err := dao.WithContext(ctx).Unscoped().Where(dao.Type.Eq(_type)).Updates(data)
	if err != nil {
		return err
	}
	return nil
}

// UpdateBatchByTypes 根据字段Types批量更新,零值会被更新
func (d *DictTypeRepo) UpdateBatchByTypes(ctx context.Context, _types []string, data map[string]interface{}) error {
	dao := ai_boilerplate_dao.Use(d.db).DictType
	_, err := dao.WithContext(ctx).Where(dao.Type.In(_types...)).Updates(data)
	if err != nil {
		return err
	}
	return nil
}

// UpdateBatchUnscopedByTypes 根据字段Types批量更新,零值会被更新（包括软删除）
func (d *DictTypeRepo) UpdateBatchUnscopedByTypes(ctx context.Context, _types []string, data map[string]interface{}) error {
	dao := ai_boilerplate_dao.Use(d.db).DictType
	_, err := dao.WithContext(ctx).Unscoped().Where(dao.Type.In(_types...)).Updates(data)
	if err != nil {
		return err
	}
	return nil
}

// UpdateBatchByTypesTx 根据字段Types批量更新(事务),零值会被更新
func (d *DictTypeRepo) UpdateBatchByTypesTx(ctx context.Context, tx *ai_boilerplate_dao.Query, _types []string, data map[string]interface{}) error {
	dao := tx.DictType
	_, err := dao.WithContext(ctx).Where(dao.Type.In(_types...)).Updates(data)
	if err != nil {
		return err
	}
	return nil
}

// UpdateBatchUnscopedByTypesTx 根据字段Types批量更新(事务),零值会被更新（包括软删除）
func (d *DictTypeRepo) UpdateBatchUnscopedByTypesTx(ctx context.Context, tx *ai_boilerplate_dao.Query, _types []string, data map[string]interface{}) error {
	dao := tx.DictType
	_, err := dao.WithContext(ctx).Unscoped().Where(dao.Type.In(_types...)).Updates(data)
	if err != nil {
		return err
	}
	return nil
}

// FindOneByID 根据ID查询一条数据
func (d *DictTypeRepo) FindOneByID(ctx context.Context, ID string) (*ai_boilerplate_model.DictType, error) {
	dao := ai_boilerplate_dao.Use(d.db).DictType
	result, err := dao.WithContext(ctx).Where(dao.ID.Eq(ID)).First()
	if err != nil && !errors.Is(err, gorm.ErrRecordNotFound) {
		return nil, err
	}
	return result, nil
}

// FindOneUnscopedByID 根据ID查询一条数据（包括软删除）
func (d *DictTypeRepo) FindOneUnscopedByID(ctx context.Context, ID string) (*ai_boilerplate_model.DictType, error) {
	dao := ai_boilerplate_dao.Use(d.db).DictType
	result, err := dao.WithContext(ctx).Unscoped().Where(dao.ID.Eq(ID)).First()
	if err != nil && !errors.Is(err, gorm.ErrRecordNotFound) {
		return nil, err
	}
	return result, nil
}

// FindOneCacheByID 根据ID查询一条数据，并设置缓存
func (d *DictTypeRepo) FindOneCacheByID(ctx context.Context, ID string) (*ai_boilerplate_model.DictType, error) {
	resp := new(ai_boilerplate_model.DictType)
	cacheKey := d.cache.Key(CacheDictTypeByIDPrefix, ID)
	cacheValue, err := d.cache.Fetch(ctx, cacheKey, func() (string, error) {
		dao := ai_boilerplate_dao.Use(d.db).DictType
		result, err := dao.WithContext(ctx).Where(dao.ID.Eq(ID)).First()
		if err != nil && !errors.Is(err, gorm.ErrRecordNotFound) {
			return "", err
		}
		marshal, err := d.encoding.Marshal(result)
		if err != nil {
			return "", err
		}
		return string(marshal), nil
	}, d.cache.TTL())
	if err != nil {
		return nil, err
	}
	if cacheValue != "" {
		err = d.encoding.Unmarshal([]byte(cacheValue), resp)
		if err != nil {
			return nil, err
		}
	}
	return resp, nil
}

// FindOneUnscopedCacheByID 根据ID查询一条数据（包括软删除），并设置缓存
func (d *DictTypeRepo) FindOneUnscopedCacheByID(ctx context.Context, ID string) (*ai_boilerplate_model.DictType, error) {
	resp := new(ai_boilerplate_model.DictType)
	cacheKey := d.cache.Key(CacheDictTypeUnscopedByIDPrefix, ID)
	cacheValue, err := d.cache.Fetch(ctx, cacheKey, func() (string, error) {
		dao := ai_boilerplate_dao.Use(d.db).DictType
		result, err := dao.WithContext(ctx).Unscoped().Where(dao.ID.Eq(ID)).First()
		if err != nil && !errors.Is(err, gorm.ErrRecordNotFound) {
			return "", err
		}
		marshal, err := d.encoding.Marshal(result)
		if err != nil {
			return "", err
		}
		return string(marshal), nil
	}, d.cache.TTL())
	if err != nil {
		return nil, err
	}
	if cacheValue != "" {
		err = d.encoding.Unmarshal([]byte(cacheValue), resp)
		if err != nil {
			return nil, err
		}
	}
	return resp, nil
}

// FindMultiByIDS 根据IDS查询多条数据
func (d *DictTypeRepo) FindMultiByIDS(ctx context.Context, IDS []string) ([]*ai_boilerplate_model.DictType, error) {
	dao := ai_boilerplate_dao.Use(d.db).DictType
	result, err := dao.WithContext(ctx).Where(dao.ID.In(IDS...)).Find()
	if err != nil {
		return nil, err
	}
	return result, nil
}

// FindMultiUnscopedByIDS 根据IDS查询多条数据（包括软删除）
func (d *DictTypeRepo) FindMultiUnscopedByIDS(ctx context.Context, IDS []string) ([]*ai_boilerplate_model.DictType, error) {
	dao := ai_boilerplate_dao.Use(d.db).DictType
	result, err := dao.WithContext(ctx).Unscoped().Where(dao.ID.In(IDS...)).Find()
	if err != nil {
		return nil, err
	}
	return result, nil
}

// FindMultiCacheByIDS 根据IDS查询多条数据，并设置缓存
func (d *DictTypeRepo) FindMultiCacheByIDS(ctx context.Context, IDS []string) ([]*ai_boilerplate_model.DictType, error) {
	resp := make([]*ai_boilerplate_model.DictType, 0)
	cacheKeys := make([]string, 0)
	keyToParam := make(map[string]string)
	for _, item := range IDS {
		cacheKey := d.cache.Key(CacheDictTypeByIDPrefix, item)
		cacheKeys = append(cacheKeys, cacheKey)
		keyToParam[cacheKey] = item
	}
	cacheValue, err := d.cache.FetchBatch(ctx, cacheKeys, func(miss []string) (map[string]string, error) {
		dbValue := make(map[string]string)
		params := make([]string, 0)
		for _, item := range miss {
			dbValue[item] = ""
			params = append(params, keyToParam[item])
		}
		dao := ai_boilerplate_dao.Use(d.db).DictType
		result, err := dao.WithContext(ctx).Where(dao.ID.In(params...)).Find()
		if err != nil {
			return nil, err
		}
		for _, item := range result {
			marshal, err := d.encoding.Marshal(item)
			if err != nil {
				return nil, err
			}
			dbValue[d.cache.Key(CacheDictTypeByIDPrefix, item.ID)] = string(marshal)
		}
		return dbValue, nil
	}, d.cache.TTL())
	if err != nil {
		return nil, err
	}
	for _, cacheKey := range cacheKeys {
		if cacheValue[cacheKey] != "" {
			tmp := new(ai_boilerplate_model.DictType)
			err := d.encoding.Unmarshal([]byte(cacheValue[cacheKey]), tmp)
			if err != nil {
				return nil, err
			}
			resp = append(resp, tmp)
		}
	}
	return resp, nil
}

// FindMultiUnscopedCacheByIDS 根据IDS查询多条数据（包括软删除），并设置缓存
func (d *DictTypeRepo) FindMultiUnscopedCacheByIDS(ctx context.Context, IDS []string) ([]*ai_boilerplate_model.DictType, error) {
	resp := make([]*ai_boilerplate_model.DictType, 0)
	cacheKeys := make([]string, 0)
	keyToParam := make(map[string]string)
	for _, item := range IDS {
		cacheKey := d.cache.Key(CacheDictTypeUnscopedByIDPrefix, item)
		cacheKeys = append(cacheKeys, cacheKey)
		keyToParam[cacheKey] = item
	}
	cacheValue, err := d.cache.FetchBatch(ctx, cacheKeys, func(miss []string) (map[string]string, error) {
		dbValue := make(map[string]string)
		params := make([]string, 0)
		for _, item := range miss {
			dbValue[item] = ""
			params = append(params, keyToParam[item])
		}
		dao := ai_boilerplate_dao.Use(d.db).DictType
		result, err := dao.WithContext(ctx).Unscoped().Where(dao.ID.In(params...)).Find()
		if err != nil {
			return nil, err
		}
		for _, item := range result {
			marshal, err := d.encoding.Marshal(item)
			if err != nil {
				return nil, err
			}
			dbValue[d.cache.Key(CacheDictTypeUnscopedByIDPrefix, item.ID)] = string(marshal)
		}
		return dbValue, nil
	}, d.cache.TTL())
	if err != nil {
		return nil, err
	}
	for _, cacheKey := range cacheKeys {
		if cacheValue[cacheKey] != "" {
			tmp := new(ai_boilerplate_model.DictType)
			err := d.encoding.Unmarshal([]byte(cacheValue[cacheKey]), tmp)
			if err != nil {
				return nil, err
			}
			resp = append(resp, tmp)
		}
	}
	return resp, nil
}

// FindOneByType 根据_type查询一条数据
func (d *DictTypeRepo) FindOneByType(ctx context.Context, _type string) (*ai_boilerplate_model.DictType, error) {
	dao := ai_boilerplate_dao.Use(d.db).DictType
	result, err := dao.WithContext(ctx).Where(dao.Type.Eq(_type)).First()
	if err != nil && !errors.Is(err, gorm.ErrRecordNotFound) {
		return nil, err
	}
	return result, nil
}

// FindOneUnscopedByType 根据_type查询一条数据（包括软删除）
func (d *DictTypeRepo) FindOneUnscopedByType(ctx context.Context, _type string) (*ai_boilerplate_model.DictType, error) {
	dao := ai_boilerplate_dao.Use(d.db).DictType
	result, err := dao.WithContext(ctx).Unscoped().Where(dao.Type.Eq(_type)).First()
	if err != nil && !errors.Is(err, gorm.ErrRecordNotFound) {
		return nil, err
	}
	return result, nil
}

// FindOneCacheByType 根据_type查询一条数据，并设置缓存
func (d *DictTypeRepo) FindOneCacheByType(ctx context.Context, _type string) (*ai_boilerplate_model.DictType, error) {
	resp := new(ai_boilerplate_model.DictType)
	cacheKey := d.cache.Key(CacheDictTypeByTypePrefix, _type)
	cacheValue, err := d.cache.Fetch(ctx, cacheKey, func() (string, error) {
		dao := ai_boilerplate_dao.Use(d.db).DictType
		result, err := dao.WithContext(ctx).Where(dao.Type.Eq(_type)).First()
		if err != nil && !errors.Is(err, gorm.ErrRecordNotFound) {
			return "", err
		}
		marshal, err := d.encoding.Marshal(result)
		if err != nil {
			return "", err
		}
		return string(marshal), nil
	}, d.cache.TTL())
	if err != nil {
		return nil, err
	}
	if cacheValue != "" {
		err = d.encoding.Unmarshal([]byte(cacheValue), resp)
		if err != nil {
			return nil, err
		}
	}
	return resp, nil
}

// FindOneUnscopedCacheByType 根据_type查询一条数据（包括软删除），并设置缓存
func (d *DictTypeRepo) FindOneUnscopedCacheByType(ctx context.Context, _type string) (*ai_boilerplate_model.DictType, error) {
	resp := new(ai_boilerplate_model.DictType)
	cacheKey := d.cache.Key(CacheDictTypeUnscopedByTypePrefix, _type)
	cacheValue, err := d.cache.Fetch(ctx, cacheKey, func() (string, error) {
		dao := ai_boilerplate_dao.Use(d.db).DictType
		result, err := dao.WithContext(ctx).Unscoped().Where(dao.Type.Eq(_type)).First()
		if err != nil && !errors.Is(err, gorm.ErrRecordNotFound) {
			return "", err
		}
		marshal, err := d.encoding.Marshal(result)
		if err != nil {
			return "", err
		}
		return string(marshal), nil
	}, d.cache.TTL())
	if err != nil {
		return nil, err
	}
	if cacheValue != "" {
		err = d.encoding.Unmarshal([]byte(cacheValue), resp)
		if err != nil {
			return nil, err
		}
	}
	return resp, nil
}

// FindMultiByTypes 根据_types查询多条数据
func (d *DictTypeRepo) FindMultiByTypes(ctx context.Context, _types []string) ([]*ai_boilerplate_model.DictType, error) {
	dao := ai_boilerplate_dao.Use(d.db).DictType
	result, err := dao.WithContext(ctx).Where(dao.Type.In(_types...)).Find()
	if err != nil {
		return nil, err
	}
	return result, nil
}

// FindMultiUnscopedByTypes 根据_types查询多条数据（包括软删除）
func (d *DictTypeRepo) FindMultiUnscopedByTypes(ctx context.Context, _types []string) ([]*ai_boilerplate_model.DictType, error) {
	dao := ai_boilerplate_dao.Use(d.db).DictType
	result, err := dao.WithContext(ctx).Unscoped().Where(dao.Type.In(_types...)).Find()
	if err != nil {
		return nil, err
	}
	return result, nil
}

// FindMultiCacheByTypes 根据_types查询多条数据，并设置缓存
func (d *DictTypeRepo) FindMultiCacheByTypes(ctx context.Context, _types []string) ([]*ai_boilerplate_model.DictType, error) {
	resp := make([]*ai_boilerplate_model.DictType, 0)
	cacheKeys := make([]string, 0)
	keyToParam := make(map[string]string)
	for _, item := range _types {
		cacheKey := d.cache.Key(CacheDictTypeByTypePrefix, item)
		cacheKeys = append(cacheKeys, cacheKey)
		keyToParam[cacheKey] = item
	}
	cacheValue, err := d.cache.FetchBatch(ctx, cacheKeys, func(miss []string) (map[string]string, error) {
		dbValue := make(map[string]string)
		params := make([]string, 0)
		for _, item := range miss {
			dbValue[item] = ""
			params = append(params, keyToParam[item])
		}
		dao := ai_boilerplate_dao.Use(d.db).DictType
		result, err := dao.WithContext(ctx).Where(dao.Type.In(params...)).Find()
		if err != nil {
			return nil, err
		}
		for _, item := range result {
			marshal, err := d.encoding.Marshal(item)
			if err != nil {
				return nil, err
			}
			dbValue[d.cache.Key(CacheDictTypeByTypePrefix, item.Type)] = string(marshal)
		}
		return dbValue, nil
	}, d.cache.TTL())
	if err != nil {
		return nil, err
	}
	for _, cacheKey := range cacheKeys {
		if cacheValue[cacheKey] != "" {
			tmp := new(ai_boilerplate_model.DictType)
			err := d.encoding.Unmarshal([]byte(cacheValue[cacheKey]), tmp)
			if err != nil {
				return nil, err
			}
			resp = append(resp, tmp)
		}
	}
	return resp, nil
}

// FindMultiUnscopedCacheByTypes 根据_types查询多条数据（包括软删除），并设置缓存
func (d *DictTypeRepo) FindMultiUnscopedCacheByTypes(ctx context.Context, _types []string) ([]*ai_boilerplate_model.DictType, error) {
	resp := make([]*ai_boilerplate_model.DictType, 0)
	cacheKeys := make([]string, 0)
	keyToParam := make(map[string]string)
	for _, item := range _types {
		cacheKey := d.cache.Key(CacheDictTypeUnscopedByTypePrefix, item)
		cacheKeys = append(cacheKeys, cacheKey)
		keyToParam[cacheKey] = item
	}
	cacheValue, err := d.cache.FetchBatch(ctx, cacheKeys, func(miss []string) (map[string]string, error) {
		dbValue := make(map[string]string)
		params := make([]string, 0)
		for _, item := range miss {
			dbValue[item] = ""
			params = append(params, keyToParam[item])
		}
		dao := ai_boilerplate_dao.Use(d.db).DictType
		result, err := dao.WithContext(ctx).Unscoped().Where(dao.Type.In(params...)).Find()
		if err != nil {
			return nil, err
		}
		for _, item := range result {
			marshal, err := d.encoding.Marshal(item)
			if err != nil {
				return nil, err
			}
			dbValue[d.cache.Key(CacheDictTypeUnscopedByTypePrefix, item.Type)] = string(marshal)
		}
		return dbValue, nil
	}, d.cache.TTL())
	if err != nil {
		return nil, err
	}
	for _, cacheKey := range cacheKeys {
		if cacheValue[cacheKey] != "" {
			tmp := new(ai_boilerplate_model.DictType)
			err := d.encoding.Unmarshal([]byte(cacheValue[cacheKey]), tmp)
			if err != nil {
				return nil, err
			}
			resp = append(resp, tmp)
		}
	}
	return resp, nil
}

// FindMultiByCondition 自定义查询数据(通用)
// 非万能查询方法,请评估后谨慎使用
func (d *DictTypeRepo) FindMultiByCondition(ctx context.Context, conditionReq *condition.Req) ([]*ai_boilerplate_model.DictType, *condition.Reply, error) {
	result := make([]*ai_boilerplate_model.DictType, 0)
	conditionReply := &condition.Reply{}
	var total int64
	whereExpressions, orderExpressions, err := conditionReq.ConvertToGormExpression(ai_boilerplate_model.DictType{})
	if err != nil {
		return result, conditionReply, err
	}
	if conditionReq.Page != 0 && conditionReq.PageSize != 0 {
		err = d.db.WithContext(ctx).Model(&ai_boilerplate_model.DictType{}).Clauses(whereExpressions...).Count(&total).Error
		if err != nil {
			return result, conditionReply, err
		}
		if total == 0 {
			return result, conditionReply, nil
		}
		conditionReply, err = conditionReq.ConvertToPage(int32(total))
		if err != nil {
			return result, conditionReply, err
		}
		query := d.db.WithContext(ctx).Model(&ai_boilerplate_model.DictType{}).Clauses(whereExpressions...).Clauses(orderExpressions...)
		if conditionReply.Page != 0 && conditionReply.PageSize != 0 {
			query = query.Offset(int((conditionReply.Page - 1) * conditionReply.PageSize))
			query = query.Limit(int(conditionReply.PageSize))
		}
		err = query.Find(&result).Error
		if err != nil {
			return result, conditionReply, err
		}
	} else {
		err = d.db.WithContext(ctx).Model(&ai_boilerplate_model.DictType{}).Clauses(whereExpressions...).Clauses(orderExpressions...).Find(&result).Error
		if err != nil {
			return result, conditionReply, err
		}
		conditionReply.Total = int32(len(result))
	}
	return result, conditionReply, err
}

// FindMultiUnscopedByCondition 自定义查询数据(通用)（包括软删除）
// 非万能查询方法,请评估后谨慎使用
func (d *DictTypeRepo) FindMultiUnscopedByCondition(ctx context.Context, conditionReq *condition.Req) ([]*ai_boilerplate_model.DictType, *condition.Reply, error) {
	result := make([]*ai_boilerplate_model.DictType, 0)
	conditionReply := &condition.Reply{}
	var total int64
	whereExpressions, orderExpressions, err := conditionReq.ConvertToGormExpression(ai_boilerplate_model.DictType{})
	if err != nil {
		return result, conditionReply, err
	}
	if conditionReq.Page != 0 && conditionReq.PageSize != 0 {
		err = d.db.WithContext(ctx).Model(&ai_boilerplate_model.DictType{}).Unscoped().Clauses(whereExpressions...).Count(&total).Error
		if err != nil {
			return result, conditionReply, err
		}
		if total == 0 {
			return result, conditionReply, nil
		}
		conditionReply, err = conditionReq.ConvertToPage(int32(total))
		if err != nil {
			return result, conditionReply, err
		}
		query := d.db.WithContext(ctx).Model(&ai_boilerplate_model.DictType{}).Unscoped().Clauses(whereExpressions...).Clauses(orderExpressions...)
		if conditionReply.Page != 0 && conditionReply.PageSize != 0 {
			query = query.Offset(int((conditionReply.Page - 1) * conditionReply.PageSize))
			query = query.Limit(int(conditionReply.PageSize))
		}
		err = query.Find(&result).Error
		if err != nil {
			return result, conditionReply, err
		}
	} else {
		err = d.db.WithContext(ctx).Model(&ai_boilerplate_model.DictType{}).Unscoped().Clauses(whereExpressions...).Clauses(orderExpressions...).Find(&result).Error
		if err != nil {
			return result, conditionReply, err
		}
		conditionReply.Total = int32(len(result))
	}
	return result, conditionReply, err
}

// FindMultiCacheByCondition 自定义查询数据(通用),并设置缓存
// 非万能查询方法,缓存命中率低,请评估后谨慎使用
func (d *DictTypeRepo) FindMultiCacheByCondition(ctx context.Context, conditionReq *condition.Req) ([]*ai_boilerplate_model.DictType, *condition.Reply, error) {
	type Tmp struct {
		Result         []*ai_boilerplate_model.DictType
		ConditionReply *condition.Reply
	}
	tmp := Tmp{
		Result:         make([]*ai_boilerplate_model.DictType, 0),
		ConditionReply: &condition.Reply{},
	}
	cacheKey := d.cache.Key(CacheDictTypeByConditionPrefix)
	cacheField := conditionReq.ConvertToCacheField()
	cacheValue, err := d.cache.FetchHash(ctx, cacheKey, cacheField, func() (string, error) {
		result, conditionReply, err := d.FindMultiByCondition(ctx, conditionReq)
		if err != nil {
			return "", err
		}
		tmp.Result = result
		tmp.ConditionReply = conditionReply
		marshal, err := d.encoding.Marshal(tmp)
		if err != nil {
			return "", err
		}
		return string(marshal), nil
	}, d.cache.TTL())
	if err != nil {
		return tmp.Result, tmp.ConditionReply, err
	}
	if cacheValue != "" {
		err = d.encoding.Unmarshal([]byte(cacheValue), &tmp)
		if err != nil {
			return tmp.Result, tmp.ConditionReply, err
		}
	}
	return tmp.Result, tmp.ConditionReply, nil
}

// FindMultiUnscopedCacheByCondition 自定义查询数据(通用)（包括软删除）,并设置缓存
// 非万能查询方法,缓存命中率低,请评估后谨慎使用
func (d *DictTypeRepo) FindMultiUnscopedCacheByCondition(ctx context.Context, conditionReq *condition.Req) ([]*ai_boilerplate_model.DictType, *condition.Reply, error) {
	type Tmp struct {
		Result         []*ai_boilerplate_model.DictType
		ConditionReply *condition.Reply
	}
	tmp := Tmp{
		Result:         make([]*ai_boilerplate_model.DictType, 0),
		ConditionReply: &condition.Reply{},
	}
	cacheKey := d.cache.Key(CacheDictTypeUnscopedByConditionPrefix)
	cacheField := conditionReq.ConvertToCacheField()
	cacheValue, err := d.cache.FetchHash(ctx, cacheKey, cacheField, func() (string, error) {
		result, conditionReply, err := d.FindMultiUnscopedByCondition(ctx, conditionReq)
		if err != nil {
			return "", err
		}
		tmp.Result = result
		tmp.ConditionReply = conditionReply
		marshal, err := d.encoding.Marshal(tmp)
		if err != nil {
			return "", err
		}
		return string(marshal), nil
	}, d.cache.TTL())
	if err != nil {
		return tmp.Result, tmp.ConditionReply, err
	}
	if cacheValue != "" {
		err = d.encoding.Unmarshal([]byte(cacheValue), &tmp)
		if err != nil {
			return tmp.Result, tmp.ConditionReply, err
		}
	}
	return tmp.Result, tmp.ConditionReply, nil
}

// DeleteOneByID 根据ID删除一条数据
func (d *DictTypeRepo) DeleteOneByID(ctx context.Context, ID string) error {
	dao := ai_boilerplate_dao.Use(d.db).DictType
	_, err := dao.WithContext(ctx).Where(dao.ID.Eq(ID)).Delete()
	if err != nil {
		return err
	}
	return nil
}

// DeleteOneUnscopedByID 根据ID删除一条数据
func (d *DictTypeRepo) DeleteOneUnscopedByID(ctx context.Context, ID string) error {
	dao := ai_boilerplate_dao.Use(d.db).DictType
	_, err := dao.WithContext(ctx).Unscoped().Where(dao.ID.Eq(ID)).Delete()
	if err != nil {
		return err
	}
	return nil
}

// DeleteOneCacheByID 根据ID删除一条数据，并删除缓存
func (d *DictTypeRepo) DeleteOneCacheByID(ctx context.Context, ID string) error {
	dao := ai_boilerplate_dao.Use(d.db).DictType
	result, err := dao.WithContext(ctx).Where(dao.ID.Eq(ID)).First()
	if err != nil && !errors.Is(err, gorm.ErrRecordNotFound) {
		return err
	}
	if result == nil {
		return nil
	}
	_, err = dao.WithContext(ctx).Where(dao.ID.Eq(ID)).Delete()
	if err != nil {
		return err
	}
	err = d.DeleteIndexCache(ctx, result)
	if err != nil {
		return err
	}
	return nil
}

// DeleteOneUnscopedCacheByID 根据ID删除一条数据，并删除缓存
func (d *DictTypeRepo) DeleteOneUnscopedCacheByID(ctx context.Context, ID string) error {
	dao := ai_boilerplate_dao.Use(d.db).DictType
	result, err := dao.WithContext(ctx).Unscoped().Where(dao.ID.Eq(ID)).First()
	if err != nil && !errors.Is(err, gorm.ErrRecordNotFound) {
		return err
	}
	if result == nil {
		return nil
	}
	_, err = dao.WithContext(ctx).Unscoped().Where(dao.ID.Eq(ID)).Delete()
	if err != nil {
		return err
	}
	err = d.DeleteIndexCache(ctx, result)
	if err != nil {
		return err
	}
	return nil
}

// DeleteOneByIDTx 根据ID删除一条数据
func (d *DictTypeRepo) DeleteOneByIDTx(ctx context.Context, tx *ai_boilerplate_dao.Query, ID string) error {
	dao := tx.DictType
	_, err := dao.WithContext(ctx).Where(dao.ID.Eq(ID)).Delete()
	if err != nil {
		return err
	}
	return nil
}

// DeleteOneUnscopedByIDTx 根据ID删除一条数据
func (d *DictTypeRepo) DeleteOneUnscopedByIDTx(ctx context.Context, tx *ai_boilerplate_dao.Query, ID string) error {
	dao := tx.DictType
	_, err := dao.WithContext(ctx).Unscoped().Where(dao.ID.Eq(ID)).Delete()
	if err != nil {
		return err
	}
	return nil
}

// DeleteOneCacheByIDTx 根据ID删除一条数据，并删除缓存
func (d *DictTypeRepo) DeleteOneCacheByIDTx(ctx context.Context, tx *ai_boilerplate_dao.Query, ID string) error {
	dao := tx.DictType
	result, err := dao.WithContext(ctx).Where(dao.ID.Eq(ID)).First()
	if err != nil && !errors.Is(err, gorm.ErrRecordNotFound) {
		return err
	}
	if result == nil {
		return nil
	}
	_, err = dao.WithContext(ctx).Where(dao.ID.Eq(ID)).Delete()
	if err != nil {
		return err
	}
	err = d.DeleteIndexCache(ctx, result)
	if err != nil {
		return err
	}
	return nil
}

// DeleteOneUnscopedCacheByIDTx 根据ID删除一条数据，并删除缓存
func (d *DictTypeRepo) DeleteOneUnscopedCacheByIDTx(ctx context.Context, tx *ai_boilerplate_dao.Query, ID string) error {
	dao := tx.DictType
	result, err := dao.WithContext(ctx).Unscoped().Where(dao.ID.Eq(ID)).First()
	if err != nil && !errors.Is(err, gorm.ErrRecordNotFound) {
		return err
	}
	if result == nil {
		return nil
	}
	_, err = dao.WithContext(ctx).Unscoped().Where(dao.ID.Eq(ID)).Delete()
	if err != nil {
		return err
	}
	err = d.DeleteIndexCache(ctx, result)
	if err != nil {
		return err
	}
	return nil
}

// DeleteMultiByIDS 根据IDS删除多条数据
func (d *DictTypeRepo) DeleteMultiByIDS(ctx context.Context, IDS []string) error {
	dao := ai_boilerplate_dao.Use(d.db).DictType
	_, err := dao.WithContext(ctx).Where(dao.ID.In(IDS...)).Delete()
	if err != nil {
		return err
	}
	return nil
}

// DeleteMultiUnscopedByIDS 根据IDS删除多条数据
func (d *DictTypeRepo) DeleteMultiUnscopedByIDS(ctx context.Context, IDS []string) error {
	dao := ai_boilerplate_dao.Use(d.db).DictType
	_, err := dao.WithContext(ctx).Unscoped().Where(dao.ID.In(IDS...)).Delete()
	if err != nil {
		return err
	}
	return nil
}

// DeleteMultiCacheByIDS 根据IDS删除多条数据，并删除缓存
func (d *DictTypeRepo) DeleteMultiCacheByIDS(ctx context.Context, IDS []string) error {
	dao := ai_boilerplate_dao.Use(d.db).DictType
	result, err := dao.WithContext(ctx).Where(dao.ID.In(IDS...)).Find()
	if err != nil {
		return err
	}
	if len(result) == 0 {
		return nil
	}
	_, err = dao.WithContext(ctx).Where(dao.ID.In(IDS...)).Delete()
	if err != nil {
		return err
	}
	err = d.DeleteIndexCache(ctx, result...)
	if err != nil {
		return err
	}
	return nil
}

// DeleteMultiUnscopedCacheByIDS 根据IDS删除多条数据，并删除缓存
func (d *DictTypeRepo) DeleteMultiUnscopedCacheByIDS(ctx context.Context, IDS []string) error {
	dao := ai_boilerplate_dao.Use(d.db).DictType
	result, err := dao.WithContext(ctx).Unscoped().Where(dao.ID.In(IDS...)).Find()
	if err != nil {
		return err
	}
	if len(result) == 0 {
		return nil
	}
	_, err = dao.WithContext(ctx).Unscoped().Where(dao.ID.In(IDS...)).Delete()
	if err != nil {
		return err
	}
	err = d.DeleteIndexCache(ctx, result...)
	if err != nil {
		return err
	}
	return nil
}

// DeleteMultiByIDSTx 根据IDS删除多条数据
func (d *DictTypeRepo) DeleteMultiByIDSTx(ctx context.Context, tx *ai_boilerplate_dao.Query, IDS []string) error {
	dao := tx.DictType
	_, err := dao.WithContext(ctx).Where(dao.ID.In(IDS...)).Delete()
	if err != nil {
		return err
	}
	return nil
}

// DeleteMultiUnscopedByIDSTx 根据IDS删除多条数据
func (d *DictTypeRepo) DeleteMultiUnscopedByIDSTx(ctx context.Context, tx *ai_boilerplate_dao.Query, IDS []string) error {
	dao := tx.DictType
	_, err := dao.WithContext(ctx).Unscoped().Where(dao.ID.In(IDS...)).Delete()
	if err != nil {
		return err
	}
	return nil
}

// DeleteMultiCacheByIDSTx 根据IDS删除多条数据，并删除缓存
func (d *DictTypeRepo) DeleteMultiCacheByIDSTx(ctx context.Context, tx *ai_boilerplate_dao.Query, IDS []string) error {
	dao := tx.DictType
	result, err := dao.WithContext(ctx).Where(dao.ID.In(IDS...)).Find()
	if err != nil {
		return err
	}
	if len(result) == 0 {
		return nil
	}
	_, err = dao.WithContext(ctx).Where(dao.ID.In(IDS...)).Delete()
	if err != nil {
		return err
	}
	err = d.DeleteIndexCache(ctx, result...)
	if err != nil {
		return err
	}
	return nil
}

// DeleteMultiUnscopedCacheByIDSTx 根据IDS删除多条数据，并删除缓存
func (d *DictTypeRepo) DeleteMultiUnscopedCacheByIDSTx(ctx context.Context, tx *ai_boilerplate_dao.Query, IDS []string) error {
	dao := tx.DictType
	result, err := dao.WithContext(ctx).Unscoped().Where(dao.ID.In(IDS...)).Find()
	if err != nil {
		return err
	}
	if len(result) == 0 {
		return nil
	}
	_, err = dao.WithContext(ctx).Unscoped().Where(dao.ID.In(IDS...)).Delete()
	if err != nil {
		return err
	}
	err = d.DeleteIndexCache(ctx, result...)
	if err != nil {
		return err
	}
	return nil
}

// DeleteOneByType 根据_type删除一条数据
func (d *DictTypeRepo) DeleteOneByType(ctx context.Context, _type string) error {
	dao := ai_boilerplate_dao.Use(d.db).DictType
	_, err := dao.WithContext(ctx).Where(dao.Type.Eq(_type)).Delete()
	if err != nil {
		return err
	}
	return nil
}

// DeleteOneUnscopedByType 根据_type删除一条数据
func (d *DictTypeRepo) DeleteOneUnscopedByType(ctx context.Context, _type string) error {
	dao := ai_boilerplate_dao.Use(d.db).DictType
	_, err := dao.WithContext(ctx).Unscoped().Where(dao.Type.Eq(_type)).Delete()
	if err != nil {
		return err
	}
	return nil
}

// DeleteOneCacheByType 根据_type删除一条数据，并删除缓存
func (d *DictTypeRepo) DeleteOneCacheByType(ctx context.Context, _type string) error {
	dao := ai_boilerplate_dao.Use(d.db).DictType
	result, err := dao.WithContext(ctx).Where(dao.Type.Eq(_type)).First()
	if err != nil && !errors.Is(err, gorm.ErrRecordNotFound) {
		return err
	}
	if result == nil {
		return nil
	}
	_, err = dao.WithContext(ctx).Where(dao.Type.Eq(_type)).Delete()
	if err != nil {
		return err
	}
	err = d.DeleteIndexCache(ctx, result)
	if err != nil {
		return err
	}
	return nil
}

// DeleteOneUnscopedCacheByType 根据_type删除一条数据，并删除缓存
func (d *DictTypeRepo) DeleteOneUnscopedCacheByType(ctx context.Context, _type string) error {
	dao := ai_boilerplate_dao.Use(d.db).DictType
	result, err := dao.WithContext(ctx).Unscoped().Where(dao.Type.Eq(_type)).First()
	if err != nil && !errors.Is(err, gorm.ErrRecordNotFound) {
		return err
	}
	if result == nil {
		return nil
	}
	_, err = dao.WithContext(ctx).Unscoped().Where(dao.Type.Eq(_type)).Delete()
	if err != nil {
		return err
	}
	err = d.DeleteIndexCache(ctx, result)
	if err != nil {
		return err
	}
	return nil
}

// DeleteOneByTypeTx 根据_type删除一条数据
func (d *DictTypeRepo) DeleteOneByTypeTx(ctx context.Context, tx *ai_boilerplate_dao.Query, _type string) error {
	dao := tx.DictType
	_, err := dao.WithContext(ctx).Where(dao.Type.Eq(_type)).Delete()
	if err != nil {
		return err
	}
	return nil
}

// DeleteOneUnscopedByTypeTx 根据_type删除一条数据
func (d *DictTypeRepo) DeleteOneUnscopedByTypeTx(ctx context.Context, tx *ai_boilerplate_dao.Query, _type string) error {
	dao := tx.DictType
	_, err := dao.WithContext(ctx).Unscoped().Where(dao.Type.Eq(_type)).Delete()
	if err != nil {
		return err
	}
	return nil
}

// DeleteOneCacheByTypeTx 根据_type删除一条数据，并删除缓存
func (d *DictTypeRepo) DeleteOneCacheByTypeTx(ctx context.Context, tx *ai_boilerplate_dao.Query, _type string) error {
	dao := tx.DictType
	result, err := dao.WithContext(ctx).Where(dao.Type.Eq(_type)).First()
	if err != nil && !errors.Is(err, gorm.ErrRecordNotFound) {
		return err
	}
	if result == nil {
		return nil
	}
	_, err = dao.WithContext(ctx).Where(dao.Type.Eq(_type)).Delete()
	if err != nil {
		return err
	}
	err = d.DeleteIndexCache(ctx, result)
	if err != nil {
		return err
	}
	return nil
}

// DeleteOneUnscopedCacheByTypeTx 根据_type删除一条数据，并删除缓存
func (d *DictTypeRepo) DeleteOneUnscopedCacheByTypeTx(ctx context.Context, tx *ai_boilerplate_dao.Query, _type string) error {
	dao := tx.DictType
	result, err := dao.WithContext(ctx).Unscoped().Where(dao.Type.Eq(_type)).First()
	if err != nil && !errors.Is(err, gorm.ErrRecordNotFound) {
		return err
	}
	if result == nil {
		return nil
	}
	_, err = dao.WithContext(ctx).Unscoped().Where(dao.Type.Eq(_type)).Delete()
	if err != nil {
		return err
	}
	err = d.DeleteIndexCache(ctx, result)
	if err != nil {
		return err
	}
	return nil
}

// DeleteMultiByTypes 根据_types删除多条数据
func (d *DictTypeRepo) DeleteMultiByTypes(ctx context.Context, _types []string) error {
	dao := ai_boilerplate_dao.Use(d.db).DictType
	_, err := dao.WithContext(ctx).Where(dao.Type.In(_types...)).Delete()
	if err != nil {
		return err
	}
	return nil
}

// DeleteMultiUnscopedByTypes 根据_types删除多条数据
func (d *DictTypeRepo) DeleteMultiUnscopedByTypes(ctx context.Context, _types []string) error {
	dao := ai_boilerplate_dao.Use(d.db).DictType
	_, err := dao.WithContext(ctx).Unscoped().Where(dao.Type.In(_types...)).Delete()
	if err != nil {
		return err
	}
	return nil
}

// DeleteMultiCacheByTypes 根据_types删除多条数据，并删除缓存
func (d *DictTypeRepo) DeleteMultiCacheByTypes(ctx context.Context, _types []string) error {
	dao := ai_boilerplate_dao.Use(d.db).DictType
	result, err := dao.WithContext(ctx).Where(dao.Type.In(_types...)).Find()
	if err != nil {
		return err
	}
	if len(result) == 0 {
		return nil
	}
	_, err = dao.WithContext(ctx).Where(dao.Type.In(_types...)).Delete()
	if err != nil {
		return err
	}
	err = d.DeleteIndexCache(ctx, result...)
	if err != nil {
		return err
	}
	return nil
}

// DeleteMultiUnscopedCacheByTypes 根据_types删除多条数据，并删除缓存
func (d *DictTypeRepo) DeleteMultiUnscopedCacheByTypes(ctx context.Context, _types []string) error {
	dao := ai_boilerplate_dao.Use(d.db).DictType
	result, err := dao.WithContext(ctx).Unscoped().Where(dao.Type.In(_types...)).Find()
	if err != nil {
		return err
	}
	if len(result) == 0 {
		return nil
	}
	_, err = dao.WithContext(ctx).Unscoped().Where(dao.Type.In(_types...)).Delete()
	if err != nil {
		return err
	}
	err = d.DeleteIndexCache(ctx, result...)
	if err != nil {
		return err
	}
	return nil
}

// DeleteMultiByTypesTx 根据_types删除多条数据
func (d *DictTypeRepo) DeleteMultiByTypesTx(ctx context.Context, tx *ai_boilerplate_dao.Query, _types []string) error {
	dao := tx.DictType
	_, err := dao.WithContext(ctx).Where(dao.Type.In(_types...)).Delete()
	if err != nil {
		return err
	}
	return nil
}

// DeleteMultiUnscopedByTypesTx 根据_types删除多条数据
func (d *DictTypeRepo) DeleteMultiUnscopedByTypesTx(ctx context.Context, tx *ai_boilerplate_dao.Query, _types []string) error {
	dao := tx.DictType
	_, err := dao.WithContext(ctx).Unscoped().Where(dao.Type.In(_types...)).Delete()
	if err != nil {
		return err
	}
	return nil
}

// DeleteMultiCacheByTypesTx 根据_types删除多条数据，并删除缓存
func (d *DictTypeRepo) DeleteMultiCacheByTypesTx(ctx context.Context, tx *ai_boilerplate_dao.Query, _types []string) error {
	dao := tx.DictType
	result, err := dao.WithContext(ctx).Where(dao.Type.In(_types...)).Find()
	if err != nil {
		return err
	}
	if len(result) == 0 {
		return nil
	}
	_, err = dao.WithContext(ctx).Where(dao.Type.In(_types...)).Delete()
	if err != nil {
		return err
	}
	err = d.DeleteIndexCache(ctx, result...)
	if err != nil {
		return err
	}
	return nil
}

// DeleteMultiUnscopedCacheByTypesTx 根据_types删除多条数据，并删除缓存
func (d *DictTypeRepo) DeleteMultiUnscopedCacheByTypesTx(ctx context.Context, tx *ai_boilerplate_dao.Query, _types []string) error {
	dao := tx.DictType
	result, err := dao.WithContext(ctx).Unscoped().Where(dao.Type.In(_types...)).Find()
	if err != nil {
		return err
	}
	if len(result) == 0 {
		return nil
	}
	_, err = dao.WithContext(ctx).Unscoped().Where(dao.Type.In(_types...)).Delete()
	if err != nil {
		return err
	}
	err = d.DeleteIndexCache(ctx, result...)
	if err != nil {
		return err
	}
	return nil
}

// DeleteUniqueIndexCache 删除索引存在的缓存
func (d *DictTypeRepo) DeleteIndexCache(ctx context.Context, data ...*ai_boilerplate_model.DictType) error {
	KeyMap := make(map[string]struct{})
	keys := make([]string, 0)
	keys = append(keys, d.cache.Key(CacheDictTypeByConditionPrefix))
	keys = append(keys, d.cache.Key(CacheDictTypeUnscopedByConditionPrefix))
	for _, item := range data {
		if item != nil {
			KeyMap[d.cache.Key(CacheDictTypeByIDPrefix, item.ID)] = struct{}{}
			KeyMap[d.cache.Key(CacheDictTypeUnscopedByIDPrefix, item.ID)] = struct{}{}
			KeyMap[d.cache.Key(CacheDictTypeByTypePrefix, item.Type)] = struct{}{}
			KeyMap[d.cache.Key(CacheDictTypeUnscopedByTypePrefix, item.Type)] = struct{}{}
		}
	}
	for item := range KeyMap {
		keys = append(keys, item)
	}
	err := d.cache.DelBatch(ctx, keys)
	if err != nil {
		return err
	}
	return nil
}
