package service

import "github.com/google/wire"

// ProviderSet is service providers.
var ProviderSet = wire.NewSet(
	NewAdminV1AiAudioRecordService,
	NewAdminV1AiChatConversationService,
	NewAdminV1AiChatMessageService,
	NewAdminV1AiImageRecordService,
	NewAdminV1AiIndexAudioService,
	NewAdminV1AiIndexChatService,
	NewAdminV1AiIndexImageService,
	NewAdminV1AiIndexPromptService,
	NewAdminV1AiIndexVideoService,
	NewAdminV1AiPromptService,
	NewAdminV1AiProviderModelService,
	NewAdminV1AiProviderPlatformService,
	NewAdminV1AiVideoRecordService,
	NewAdminV1AiWriteRecordService,
	NewAdminV1ConfigDatumService,
	NewAdminV1DeviceService,
	NewAdminV1DictDatumService,
	NewAdminV1DictTypeService,
	NewAdminV1FileConfigService,
	NewAdminV1FileDatumService,
	NewAdminV1MailAccountService,
	NewAdminV1MailLogService,
	NewAdminV1MailTemplateService,
	NewAdminV1MallActivationCodeService,
	NewAdminV1MallOrderService,
	NewAdminV1MallPaymentRecordService,
	NewAdminV1MallProductService,
	NewAdminV1MembershipBenefitService,
	NewAdminV1MembershipService,
	NewAdminV1SelfAppReleaseService,
	NewAdminV1SelfAppService,
	NewAdminV1SensitiveWordService,
	NewAdminV1SmsChannelService,
	NewAdminV1SmsLogService,
	NewAdminV1SmsTemplateService,
	NewAdminV1SysAPIService,
	NewAdminV1SysAdminService,
	NewAdminV1SysAuthService,
	NewAdminV1SysDeptService,
	NewAdminV1SysMenuService,
	NewAdminV1SysNoticeService,
	NewAdminV1SysNotifyMessageService,
	NewAdminV1SysOperateLogService,
	NewAdminV1SysPostService,
	NewAdminV1SysRoleService,
	NewAdminV1SysTenantService,
	NewAdminV1UserMembershipService,
	NewAdminV1UserService,
	NewAdminV1WxGzhAccountService,
	NewAdminV1WxGzhAutoReplyService,
	NewAdminV1WxGzhMaterialService,
	NewAdminV1WxGzhMenuService,
	NewAdminV1WxGzhMessageService,
	NewAdminV1WxGzhTagService,
	NewAdminV1WxGzhUserService,
	NewAdminV1WxXcxUserService,
)
