// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.9
// source: admin/v1/membership_benefit.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MembershipBenefitClient is the client API for MembershipBenefit service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MembershipBenefitClient interface {
	// 会员权益配置表-获取权益标识选择器
	GetMembershipBenefitKeySelect(ctx context.Context, in *GetMembershipBenefitKeySelectReq, opts ...grpc.CallOption) (*GetMembershipBenefitKeySelectReply, error)
	// 会员权益配置表-创建一条数据
	CreateMembershipBenefit(ctx context.Context, in *CreateMembershipBenefitReq, opts ...grpc.CallOption) (*CreateMembershipBenefitReply, error)
	// 会员权益配置表-更新一条数据
	UpdateMembershipBenefit(ctx context.Context, in *UpdateMembershipBenefitReq, opts ...grpc.CallOption) (*UpdateMembershipBenefitReply, error)
	// 会员权益配置表-更新状态
	UpdateMembershipBenefitStatus(ctx context.Context, in *UpdateMembershipBenefitStatusReq, opts ...grpc.CallOption) (*UpdateMembershipBenefitStatusReply, error)
	// 会员权益配置表-删除一条数据
	DeleteMembershipBenefit(ctx context.Context, in *DeleteMembershipBenefitReq, opts ...grpc.CallOption) (*DeleteMembershipBenefitReply, error)
	// 会员权益配置表-单条数据查询
	GetMembershipBenefitInfo(ctx context.Context, in *GetMembershipBenefitInfoReq, opts ...grpc.CallOption) (*GetMembershipBenefitInfoReply, error)
	// 会员权益配置表-列表数据查询
	GetMembershipBenefitList(ctx context.Context, in *GetMembershipBenefitListReq, opts ...grpc.CallOption) (*GetMembershipBenefitListReply, error)
}

type membershipBenefitClient struct {
	cc grpc.ClientConnInterface
}

func NewMembershipBenefitClient(cc grpc.ClientConnInterface) MembershipBenefitClient {
	return &membershipBenefitClient{cc}
}

func (c *membershipBenefitClient) GetMembershipBenefitKeySelect(ctx context.Context, in *GetMembershipBenefitKeySelectReq, opts ...grpc.CallOption) (*GetMembershipBenefitKeySelectReply, error) {
	out := new(GetMembershipBenefitKeySelectReply)
	err := c.cc.Invoke(ctx, "/admin.v1.MembershipBenefit/GetMembershipBenefitKeySelect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipBenefitClient) CreateMembershipBenefit(ctx context.Context, in *CreateMembershipBenefitReq, opts ...grpc.CallOption) (*CreateMembershipBenefitReply, error) {
	out := new(CreateMembershipBenefitReply)
	err := c.cc.Invoke(ctx, "/admin.v1.MembershipBenefit/CreateMembershipBenefit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipBenefitClient) UpdateMembershipBenefit(ctx context.Context, in *UpdateMembershipBenefitReq, opts ...grpc.CallOption) (*UpdateMembershipBenefitReply, error) {
	out := new(UpdateMembershipBenefitReply)
	err := c.cc.Invoke(ctx, "/admin.v1.MembershipBenefit/UpdateMembershipBenefit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipBenefitClient) UpdateMembershipBenefitStatus(ctx context.Context, in *UpdateMembershipBenefitStatusReq, opts ...grpc.CallOption) (*UpdateMembershipBenefitStatusReply, error) {
	out := new(UpdateMembershipBenefitStatusReply)
	err := c.cc.Invoke(ctx, "/admin.v1.MembershipBenefit/UpdateMembershipBenefitStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipBenefitClient) DeleteMembershipBenefit(ctx context.Context, in *DeleteMembershipBenefitReq, opts ...grpc.CallOption) (*DeleteMembershipBenefitReply, error) {
	out := new(DeleteMembershipBenefitReply)
	err := c.cc.Invoke(ctx, "/admin.v1.MembershipBenefit/DeleteMembershipBenefit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipBenefitClient) GetMembershipBenefitInfo(ctx context.Context, in *GetMembershipBenefitInfoReq, opts ...grpc.CallOption) (*GetMembershipBenefitInfoReply, error) {
	out := new(GetMembershipBenefitInfoReply)
	err := c.cc.Invoke(ctx, "/admin.v1.MembershipBenefit/GetMembershipBenefitInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipBenefitClient) GetMembershipBenefitList(ctx context.Context, in *GetMembershipBenefitListReq, opts ...grpc.CallOption) (*GetMembershipBenefitListReply, error) {
	out := new(GetMembershipBenefitListReply)
	err := c.cc.Invoke(ctx, "/admin.v1.MembershipBenefit/GetMembershipBenefitList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MembershipBenefitServer is the server API for MembershipBenefit service.
// All implementations must embed UnimplementedMembershipBenefitServer
// for forward compatibility
type MembershipBenefitServer interface {
	// 会员权益配置表-获取权益标识选择器
	GetMembershipBenefitKeySelect(context.Context, *GetMembershipBenefitKeySelectReq) (*GetMembershipBenefitKeySelectReply, error)
	// 会员权益配置表-创建一条数据
	CreateMembershipBenefit(context.Context, *CreateMembershipBenefitReq) (*CreateMembershipBenefitReply, error)
	// 会员权益配置表-更新一条数据
	UpdateMembershipBenefit(context.Context, *UpdateMembershipBenefitReq) (*UpdateMembershipBenefitReply, error)
	// 会员权益配置表-更新状态
	UpdateMembershipBenefitStatus(context.Context, *UpdateMembershipBenefitStatusReq) (*UpdateMembershipBenefitStatusReply, error)
	// 会员权益配置表-删除一条数据
	DeleteMembershipBenefit(context.Context, *DeleteMembershipBenefitReq) (*DeleteMembershipBenefitReply, error)
	// 会员权益配置表-单条数据查询
	GetMembershipBenefitInfo(context.Context, *GetMembershipBenefitInfoReq) (*GetMembershipBenefitInfoReply, error)
	// 会员权益配置表-列表数据查询
	GetMembershipBenefitList(context.Context, *GetMembershipBenefitListReq) (*GetMembershipBenefitListReply, error)
	mustEmbedUnimplementedMembershipBenefitServer()
}

// UnimplementedMembershipBenefitServer must be embedded to have forward compatible implementations.
type UnimplementedMembershipBenefitServer struct {
}

func (UnimplementedMembershipBenefitServer) GetMembershipBenefitKeySelect(context.Context, *GetMembershipBenefitKeySelectReq) (*GetMembershipBenefitKeySelectReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMembershipBenefitKeySelect not implemented")
}
func (UnimplementedMembershipBenefitServer) CreateMembershipBenefit(context.Context, *CreateMembershipBenefitReq) (*CreateMembershipBenefitReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMembershipBenefit not implemented")
}
func (UnimplementedMembershipBenefitServer) UpdateMembershipBenefit(context.Context, *UpdateMembershipBenefitReq) (*UpdateMembershipBenefitReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateMembershipBenefit not implemented")
}
func (UnimplementedMembershipBenefitServer) UpdateMembershipBenefitStatus(context.Context, *UpdateMembershipBenefitStatusReq) (*UpdateMembershipBenefitStatusReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateMembershipBenefitStatus not implemented")
}
func (UnimplementedMembershipBenefitServer) DeleteMembershipBenefit(context.Context, *DeleteMembershipBenefitReq) (*DeleteMembershipBenefitReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteMembershipBenefit not implemented")
}
func (UnimplementedMembershipBenefitServer) GetMembershipBenefitInfo(context.Context, *GetMembershipBenefitInfoReq) (*GetMembershipBenefitInfoReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMembershipBenefitInfo not implemented")
}
func (UnimplementedMembershipBenefitServer) GetMembershipBenefitList(context.Context, *GetMembershipBenefitListReq) (*GetMembershipBenefitListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMembershipBenefitList not implemented")
}
func (UnimplementedMembershipBenefitServer) mustEmbedUnimplementedMembershipBenefitServer() {}

// UnsafeMembershipBenefitServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MembershipBenefitServer will
// result in compilation errors.
type UnsafeMembershipBenefitServer interface {
	mustEmbedUnimplementedMembershipBenefitServer()
}

func RegisterMembershipBenefitServer(s grpc.ServiceRegistrar, srv MembershipBenefitServer) {
	s.RegisterService(&MembershipBenefit_ServiceDesc, srv)
}

func _MembershipBenefit_GetMembershipBenefitKeySelect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMembershipBenefitKeySelectReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipBenefitServer).GetMembershipBenefitKeySelect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin.v1.MembershipBenefit/GetMembershipBenefitKeySelect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipBenefitServer).GetMembershipBenefitKeySelect(ctx, req.(*GetMembershipBenefitKeySelectReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipBenefit_CreateMembershipBenefit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMembershipBenefitReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipBenefitServer).CreateMembershipBenefit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin.v1.MembershipBenefit/CreateMembershipBenefit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipBenefitServer).CreateMembershipBenefit(ctx, req.(*CreateMembershipBenefitReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipBenefit_UpdateMembershipBenefit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMembershipBenefitReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipBenefitServer).UpdateMembershipBenefit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin.v1.MembershipBenefit/UpdateMembershipBenefit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipBenefitServer).UpdateMembershipBenefit(ctx, req.(*UpdateMembershipBenefitReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipBenefit_UpdateMembershipBenefitStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMembershipBenefitStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipBenefitServer).UpdateMembershipBenefitStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin.v1.MembershipBenefit/UpdateMembershipBenefitStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipBenefitServer).UpdateMembershipBenefitStatus(ctx, req.(*UpdateMembershipBenefitStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipBenefit_DeleteMembershipBenefit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMembershipBenefitReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipBenefitServer).DeleteMembershipBenefit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin.v1.MembershipBenefit/DeleteMembershipBenefit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipBenefitServer).DeleteMembershipBenefit(ctx, req.(*DeleteMembershipBenefitReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipBenefit_GetMembershipBenefitInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMembershipBenefitInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipBenefitServer).GetMembershipBenefitInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin.v1.MembershipBenefit/GetMembershipBenefitInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipBenefitServer).GetMembershipBenefitInfo(ctx, req.(*GetMembershipBenefitInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipBenefit_GetMembershipBenefitList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMembershipBenefitListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipBenefitServer).GetMembershipBenefitList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin.v1.MembershipBenefit/GetMembershipBenefitList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipBenefitServer).GetMembershipBenefitList(ctx, req.(*GetMembershipBenefitListReq))
	}
	return interceptor(ctx, in, info, handler)
}

// MembershipBenefit_ServiceDesc is the grpc.ServiceDesc for MembershipBenefit service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MembershipBenefit_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "admin.v1.MembershipBenefit",
	HandlerType: (*MembershipBenefitServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMembershipBenefitKeySelect",
			Handler:    _MembershipBenefit_GetMembershipBenefitKeySelect_Handler,
		},
		{
			MethodName: "CreateMembershipBenefit",
			Handler:    _MembershipBenefit_CreateMembershipBenefit_Handler,
		},
		{
			MethodName: "UpdateMembershipBenefit",
			Handler:    _MembershipBenefit_UpdateMembershipBenefit_Handler,
		},
		{
			MethodName: "UpdateMembershipBenefitStatus",
			Handler:    _MembershipBenefit_UpdateMembershipBenefitStatus_Handler,
		},
		{
			MethodName: "DeleteMembershipBenefit",
			Handler:    _MembershipBenefit_DeleteMembershipBenefit_Handler,
		},
		{
			MethodName: "GetMembershipBenefitInfo",
			Handler:    _MembershipBenefit_GetMembershipBenefitInfo_Handler,
		},
		{
			MethodName: "GetMembershipBenefitList",
			Handler:    _MembershipBenefit_GetMembershipBenefitList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "admin/v1/membership_benefit.proto",
}
