// Code generated by gen/repo. DO NOT EDIT.
// Code generated by gen/repo. DO NOT EDIT.
// Code generated by gen/repo. DO NOT EDIT.

package ai_boilerplate_repo

import (
	"context"
	"errors"
	"reflect"
	"strings"

	"github.com/fzf-labs/ai-boilerplate-backend/internal/data/gorm/ai_boilerplate_dao"
	"github.com/fzf-labs/ai-boilerplate-backend/internal/data/gorm/ai_boilerplate_model"
	"github.com/fzf-labs/godb/orm/condition"
	"github.com/fzf-labs/godb/orm/dbcache"
	"github.com/fzf-labs/godb/orm/encoding"
	"github.com/fzf-labs/godb/orm/gen/config"
	"github.com/jinzhu/copier"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

var _ ISysAPIRepo = (*SysAPIRepo)(nil)

var (
	CacheSysAPIByConditionPrefix            = "DBCache:ai_boilerplate:SysAPIByCondition"
	CacheSysAPIUnscopedByConditionPrefix    = "DBCache:ai_boilerplate:SysAPIUnscopedByCondition"
	CacheSysAPIByIDPrefix                   = "DBCache:ai_boilerplate:SysAPIByID"
	CacheSysAPIUnscopedByIDPrefix           = "DBCache:ai_boilerplate:SysAPIUnscopedByID"
	CacheSysAPIByPermissionIDPrefix         = "DBCache:ai_boilerplate:SysAPIByPermissionID"
	CacheSysAPIUnscopedByPermissionIDPrefix = "DBCache:ai_boilerplate:SysAPIUnscopedByPermissionID"
)

type (
	ISysAPIRepo interface {
		// NewData 实例化
		NewData() *ai_boilerplate_model.SysAPI
		// DeepCopy 深拷贝
		DeepCopy(data *ai_boilerplate_model.SysAPI) *ai_boilerplate_model.SysAPI
		// CreateOne 创建一条数据
		CreateOne(ctx context.Context, data *ai_boilerplate_model.SysAPI) error
		// CreateOneCache 创建一条数据, 并删除缓存
		CreateOneCache(ctx context.Context, data *ai_boilerplate_model.SysAPI) error
		// CreateOneByTx 创建一条数据(事务)
		CreateOneByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, data *ai_boilerplate_model.SysAPI) error
		// CreateOneCacheByTx 创建一条数据(事务), 并删除缓存
		CreateOneCacheByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, data *ai_boilerplate_model.SysAPI) error
		// CreateBatch 批量创建数据
		CreateBatch(ctx context.Context, data []*ai_boilerplate_model.SysAPI, batchSize int) error
		// CreateBatchCache 批量创建数据, 并删除缓存
		CreateBatchCache(ctx context.Context, data []*ai_boilerplate_model.SysAPI, batchSize int) error
		// CreateBatchByTx 批量创建数据(事务)
		CreateBatchByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, data []*ai_boilerplate_model.SysAPI, batchSize int) error
		// CreateBatchCacheByTx 批量创建数据(事务), 并删除缓存
		CreateBatchCacheByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, data []*ai_boilerplate_model.SysAPI, batchSize int) error
		// UpsertOne Upsert一条数据
		UpsertOne(ctx context.Context, data *ai_boilerplate_model.SysAPI) error
		// UpsertOneCache Upsert一条数据, 并删除缓存
		UpsertOneCache(ctx context.Context, data *ai_boilerplate_model.SysAPI) error
		// UpsertOneByTx Upsert一条数据(事务)
		UpsertOneByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, data *ai_boilerplate_model.SysAPI) error
		// UpsertOneCacheByTx Upsert一条数据(事务), 并删除缓存
		UpsertOneCacheByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, data *ai_boilerplate_model.SysAPI) error
		// UpsertOneByFields 根据fields字段Upsert一条数据
		UpsertOneByFields(ctx context.Context, data *ai_boilerplate_model.SysAPI, fields []string) error
		// UpsertOneCacheByFields 根据fields字段Upsert一条数据, 并删除缓存
		UpsertOneCacheByFields(ctx context.Context, data *ai_boilerplate_model.SysAPI, fields []string) error
		// UpsertOneByFieldsTx 根据fields字段Upsert一条数据(事务)
		UpsertOneByFieldsTx(ctx context.Context, tx *ai_boilerplate_dao.Query, data *ai_boilerplate_model.SysAPI, fields []string) error
		// UpsertOneCacheByFieldsTx 根据fields字段Upsert一条数据(事务), 并删除缓存
		UpsertOneCacheByFieldsTx(ctx context.Context, tx *ai_boilerplate_dao.Query, data *ai_boilerplate_model.SysAPI, fields []string) error
		// UpdateOne 更新一条数据
		UpdateOne(ctx context.Context, newData *ai_boilerplate_model.SysAPI) error
		// UpdateOneUnscoped 更新一条数据（包括软删除）
		UpdateOneUnscoped(ctx context.Context, newData *ai_boilerplate_model.SysAPI) error
		// UpdateOneCache 更新一条数据，并删除缓存
		UpdateOneCache(ctx context.Context, newData *ai_boilerplate_model.SysAPI, oldData *ai_boilerplate_model.SysAPI) error
		// UpdateOneUnscopedCache 更新一条数据，并删除缓存（包括软删除）
		UpdateOneUnscopedCache(ctx context.Context, newData *ai_boilerplate_model.SysAPI, oldData *ai_boilerplate_model.SysAPI) error
		// UpdateOneByTx 更新一条数据(事务)
		UpdateOneByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, newData *ai_boilerplate_model.SysAPI) error
		// UpdateOneUnscopedByTx 更新一条数据(事务)（包括软删除）
		UpdateOneUnscopedByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, newData *ai_boilerplate_model.SysAPI) error
		// UpdateOneCacheByTx 更新一条数据(事务)，并删除缓存
		UpdateOneCacheByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, newData *ai_boilerplate_model.SysAPI, oldData *ai_boilerplate_model.SysAPI) error
		// UpdateOneUnscopedCacheByTx 更新一条数据(事务)，并删除缓存（包括软删除）
		UpdateOneUnscopedCacheByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, newData *ai_boilerplate_model.SysAPI, oldData *ai_boilerplate_model.SysAPI) error
		// UpdateOneWithZero 更新一条数据,包含零值，并删除缓存
		UpdateOneWithZero(ctx context.Context, newData *ai_boilerplate_model.SysAPI) error
		// UpdateOneUnscopedWithZero 更新一条数据,包含零值（包括软删除）
		UpdateOneUnscopedWithZero(ctx context.Context, newData *ai_boilerplate_model.SysAPI) error
		// UpdateOneCacheWithZero 更新一条数据,包含零值，并删除缓存
		UpdateOneCacheWithZero(ctx context.Context, newData *ai_boilerplate_model.SysAPI, oldData *ai_boilerplate_model.SysAPI) error
		// UpdateOneUnscopedCacheWithZero 更新一条数据,包含零值，并删除缓存（包括软删除）
		UpdateOneUnscopedCacheWithZero(ctx context.Context, newData *ai_boilerplate_model.SysAPI, oldData *ai_boilerplate_model.SysAPI) error
		// UpdateOneWithZeroByTx 更新一条数据(事务),包含零值，并删除缓存
		UpdateOneWithZeroByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, newData *ai_boilerplate_model.SysAPI) error
		// UpdateOneUnscopedWithZeroByTx 更新一条数据(事务),包含零值（包括软删除）
		UpdateOneUnscopedWithZeroByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, newData *ai_boilerplate_model.SysAPI) error
		// UpdateOneCacheWithZeroByTx 更新一条数据(事务),包含零值，并删除缓存
		UpdateOneCacheWithZeroByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, newData *ai_boilerplate_model.SysAPI, oldData *ai_boilerplate_model.SysAPI) error
		// UpdateOneUnscopedCacheWithZeroByTx 更新一条数据(事务),包含零值，并删除缓存（包括软删除）
		UpdateOneUnscopedCacheWithZeroByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, newData *ai_boilerplate_model.SysAPI, oldData *ai_boilerplate_model.SysAPI) error
		// UpdateBatchByID 根据字段ID批量更新,零值会被更新
		UpdateBatchByID(ctx context.Context, ID string, data map[string]interface{}) error
		// UpdateBatchUnscopedByID 根据字段ID批量更新,零值会被更新（包括软删除）
		UpdateBatchUnscopedByID(ctx context.Context, ID string, data map[string]interface{}) error
		// UpdateBatchByIDTx 根据主键ID批量更新(事务),零值会被更新
		UpdateBatchByIDTx(ctx context.Context, tx *ai_boilerplate_dao.Query, ID string, data map[string]interface{}) error
		// UpdateBatchUnscopedByIDTx 根据主键ID批量更新(事务),零值会被更新（包括软删除）
		UpdateBatchUnscopedByIDTx(ctx context.Context, tx *ai_boilerplate_dao.Query, ID string, data map[string]interface{}) error
		// UpdateBatchByIDS 根据字段IDS批量更新,零值会被更新
		UpdateBatchByIDS(ctx context.Context, IDS []string, data map[string]interface{}) error
		// UpdateBatchUnscopedByIDS 根据字段IDS批量更新,零值会被更新（包括软删除）
		UpdateBatchUnscopedByIDS(ctx context.Context, IDS []string, data map[string]interface{}) error
		// UpdateBatchByIDSTx 根据字段IDS批量更新(事务),零值会被更新
		UpdateBatchByIDSTx(ctx context.Context, tx *ai_boilerplate_dao.Query, IDS []string, data map[string]interface{}) error
		// UpdateBatchUnscopedByIDSTx 根据字段IDS批量更新(事务),零值会被更新（包括软删除）
		UpdateBatchUnscopedByIDSTx(ctx context.Context, tx *ai_boilerplate_dao.Query, IDS []string, data map[string]interface{}) error
		// UpdateBatchByPermissionID 根据字段PermissionID批量更新,零值会被更新
		UpdateBatchByPermissionID(ctx context.Context, permissionID string, data map[string]interface{}) error
		// UpdateBatchUnscopedByPermissionID 根据字段PermissionID批量更新,零值会被更新（包括软删除）
		UpdateBatchUnscopedByPermissionID(ctx context.Context, permissionID string, data map[string]interface{}) error
		// UpdateBatchByPermissionIDTx 根据主键PermissionID批量更新(事务),零值会被更新
		UpdateBatchByPermissionIDTx(ctx context.Context, tx *ai_boilerplate_dao.Query, permissionID string, data map[string]interface{}) error
		// UpdateBatchUnscopedByPermissionIDTx 根据主键PermissionID批量更新(事务),零值会被更新（包括软删除）
		UpdateBatchUnscopedByPermissionIDTx(ctx context.Context, tx *ai_boilerplate_dao.Query, permissionID string, data map[string]interface{}) error
		// UpdateBatchByPermissionIDS 根据字段PermissionIDS批量更新,零值会被更新
		UpdateBatchByPermissionIDS(ctx context.Context, permissionIDS []string, data map[string]interface{}) error
		// UpdateBatchUnscopedByPermissionIDS 根据字段PermissionIDS批量更新,零值会被更新（包括软删除）
		UpdateBatchUnscopedByPermissionIDS(ctx context.Context, permissionIDS []string, data map[string]interface{}) error
		// UpdateBatchByPermissionIDSTx 根据字段PermissionIDS批量更新(事务),零值会被更新
		UpdateBatchByPermissionIDSTx(ctx context.Context, tx *ai_boilerplate_dao.Query, permissionIDS []string, data map[string]interface{}) error
		// UpdateBatchUnscopedByPermissionIDSTx 根据字段PermissionIDS批量更新(事务),零值会被更新（包括软删除）
		UpdateBatchUnscopedByPermissionIDSTx(ctx context.Context, tx *ai_boilerplate_dao.Query, permissionIDS []string, data map[string]interface{}) error
		// FindOneByID 根据ID查询一条数据
		FindOneByID(ctx context.Context, ID string) (*ai_boilerplate_model.SysAPI, error)
		// FindOneUnscopedByID 根据ID查询一条数据（包括软删除）
		FindOneUnscopedByID(ctx context.Context, ID string) (*ai_boilerplate_model.SysAPI, error)
		// FindOneCacheByID 根据ID查询一条数据，并设置缓存
		FindOneCacheByID(ctx context.Context, ID string) (*ai_boilerplate_model.SysAPI, error)
		// FindOneUnscopedCacheByID 根据ID查询一条数据（包括软删除），并设置缓存
		FindOneUnscopedCacheByID(ctx context.Context, ID string) (*ai_boilerplate_model.SysAPI, error)
		// FindMultiByIDS 根据IDS查询多条数据
		FindMultiByIDS(ctx context.Context, IDS []string) ([]*ai_boilerplate_model.SysAPI, error)
		// FindMultiUnscopedByIDS 根据IDS查询多条数据（包括软删除）
		FindMultiUnscopedByIDS(ctx context.Context, IDS []string) ([]*ai_boilerplate_model.SysAPI, error)
		// FindMultiCacheByIDS 根据IDS查询多条数据，并设置缓存
		FindMultiCacheByIDS(ctx context.Context, IDS []string) ([]*ai_boilerplate_model.SysAPI, error)
		// FindMultiUnscopedCacheByIDS 根据IDS查询多条数据（包括软删除），并设置缓存
		FindMultiUnscopedCacheByIDS(ctx context.Context, IDS []string) ([]*ai_boilerplate_model.SysAPI, error)
		// FindMultiByPermissionID 根据permissionID查询多条数据
		FindMultiByPermissionID(ctx context.Context, permissionID string) ([]*ai_boilerplate_model.SysAPI, error)
		// FindMultiUnscopedByPermissionID 根据permissionID查询多条数据（包括软删除）
		FindMultiUnscopedByPermissionID(ctx context.Context, permissionID string) ([]*ai_boilerplate_model.SysAPI, error)
		// FindMultiCacheByPermissionID 根据permissionID查询多条数据并设置缓存
		FindMultiCacheByPermissionID(ctx context.Context, permissionID string) ([]*ai_boilerplate_model.SysAPI, error)
		// FindMultiUnscopedCacheByPermissionID 根据permissionID查询多条数据（包括软删除）并设置缓存
		FindMultiUnscopedCacheByPermissionID(ctx context.Context, permissionID string) ([]*ai_boilerplate_model.SysAPI, error)
		// FindMultiByPermissionIDS 根据permissionIDS查询多条数据
		FindMultiByPermissionIDS(ctx context.Context, permissionIDS []string) ([]*ai_boilerplate_model.SysAPI, error)
		// FindMultiUnscopedByPermissionIDS 根据permissionIDS查询多条数据（包括软删除）
		FindMultiUnscopedByPermissionIDS(ctx context.Context, permissionIDS []string) ([]*ai_boilerplate_model.SysAPI, error)
		// FindMultiCacheByPermissionIDS 根据permissionIDS查询多条数据，并设置缓存
		FindMultiCacheByPermissionIDS(ctx context.Context, permissionIDS []string) ([]*ai_boilerplate_model.SysAPI, error)
		// FindMultiUnscopedCacheByPermissionIDS 根据permissionIDS查询多条数据（包括软删除），并设置缓存
		FindMultiUnscopedCacheByPermissionIDS(ctx context.Context, permissionIDS []string) ([]*ai_boilerplate_model.SysAPI, error)
		// FindMultiByCondition 自定义查询数据(通用)
		FindMultiByCondition(ctx context.Context, conditionReq *condition.Req) ([]*ai_boilerplate_model.SysAPI, *condition.Reply, error)
		// FindMultiUnscopedByCondition 自定义查询数据(通用)（包括软删除）
		FindMultiUnscopedByCondition(ctx context.Context, conditionReq *condition.Req) ([]*ai_boilerplate_model.SysAPI, *condition.Reply, error)
		// FindMultiCacheByCondition 自定义查询数据(通用),并设置缓存
		FindMultiCacheByCondition(ctx context.Context, conditionReq *condition.Req) ([]*ai_boilerplate_model.SysAPI, *condition.Reply, error)
		// FindMultiUnscopedCacheByCondition 自定义查询数据(通用)（包括软删除）,并设置缓存
		FindMultiUnscopedCacheByCondition(ctx context.Context, conditionReq *condition.Req) ([]*ai_boilerplate_model.SysAPI, *condition.Reply, error)
		// DeleteOneByID 根据ID删除一条数据
		DeleteOneByID(ctx context.Context, ID string) error
		// DeleteOneUnscopedByID 根据ID删除一条数据
		DeleteOneUnscopedByID(ctx context.Context, ID string) error
		// DeleteOneCacheByID 根据ID删除一条数据，并删除缓存
		DeleteOneCacheByID(ctx context.Context, ID string) error
		// DeleteOneUnscopedCacheByID 根据ID删除一条数据，并删除缓存
		DeleteOneUnscopedCacheByID(ctx context.Context, ID string) error
		// DeleteOneByIDTx 根据ID删除一条数据(事务)
		DeleteOneByIDTx(ctx context.Context, tx *ai_boilerplate_dao.Query, ID string) error
		// DeleteOneUnscopedByIDTx 根据ID删除一条数据(事务)
		DeleteOneUnscopedByIDTx(ctx context.Context, tx *ai_boilerplate_dao.Query, ID string) error
		// DeleteOneCacheByIDTx 根据ID删除一条数据，并删除缓存(事务)
		DeleteOneCacheByIDTx(ctx context.Context, tx *ai_boilerplate_dao.Query, ID string) error
		// DeleteOneUnscopedCacheByIDTx 根据ID删除一条数据，并删除缓存(事务)
		DeleteOneUnscopedCacheByIDTx(ctx context.Context, tx *ai_boilerplate_dao.Query, ID string) error
		// DeleteMultiByIDS 根据IDS删除多条数据
		DeleteMultiByIDS(ctx context.Context, IDS []string) error
		// DeleteMultiUnscopedByIDS 根据IDS删除多条数据
		DeleteMultiUnscopedByIDS(ctx context.Context, IDS []string) error
		// DeleteMultiCacheByIDS 根据IDS删除多条数据，并删除缓存
		DeleteMultiCacheByIDS(ctx context.Context, IDS []string) error
		// DeleteMultiUnscopedCacheByIDS 根据IDS删除多条数据，并删除缓存
		DeleteMultiUnscopedCacheByIDS(ctx context.Context, IDS []string) error
		// DeleteMultiByIDSTx 根据IDS删除多条数据(事务)
		DeleteMultiByIDSTx(ctx context.Context, tx *ai_boilerplate_dao.Query, IDS []string) error
		// DeleteMultiUnscopedByIDSTx 根据IDS删除多条数据(事务)
		DeleteMultiUnscopedByIDSTx(ctx context.Context, tx *ai_boilerplate_dao.Query, IDS []string) error
		// DeleteMultiCacheByIDSTx 根据IDS删除多条数据，并删除缓存(事务)
		DeleteMultiCacheByIDSTx(ctx context.Context, tx *ai_boilerplate_dao.Query, IDS []string) error
		// DeleteMultiUnscopedCacheByIDSTx 根据IDS删除多条数据，并删除缓存(事务)
		DeleteMultiUnscopedCacheByIDSTx(ctx context.Context, tx *ai_boilerplate_dao.Query, IDS []string) error
		// DeleteMultiByPermissionID 根据PermissionID删除多条数据
		DeleteMultiByPermissionID(ctx context.Context, permissionID string) error
		// DeleteMultiUnscopedByPermissionID 根据PermissionID删除多条数据
		DeleteMultiUnscopedByPermissionID(ctx context.Context, permissionID string) error
		// DeleteMultiCacheByPermissionID 根据permissionID删除多条数据，并删除缓存
		DeleteMultiCacheByPermissionID(ctx context.Context, permissionID string) error
		// DeleteMultiUnscopedCacheByPermissionID 根据permissionID删除多条数据，并删除缓存
		DeleteMultiUnscopedCacheByPermissionID(ctx context.Context, permissionID string) error
		// DeleteMultiByPermissionIDTx 根据permissionID删除多条数据
		DeleteMultiByPermissionIDTx(ctx context.Context, tx *ai_boilerplate_dao.Query, permissionID string) error
		// DeleteMultiUnscopedByPermissionIDTx 根据permissionID删除多条数据
		DeleteMultiUnscopedByPermissionIDTx(ctx context.Context, tx *ai_boilerplate_dao.Query, permissionID string) error
		// DeleteMultiCacheByPermissionIDTx 根据permissionID删除多条数据，并删除缓存
		DeleteMultiCacheByPermissionIDTx(ctx context.Context, tx *ai_boilerplate_dao.Query, permissionID string) error
		// DeleteMultiUnscopedCacheByPermissionIDTx 根据permissionID删除多条数据，并删除缓存
		DeleteMultiUnscopedCacheByPermissionIDTx(ctx context.Context, tx *ai_boilerplate_dao.Query, permissionID string) error
		// DeleteMultiByPermissionIDS 根据PermissionIDS删除多条数据
		DeleteMultiByPermissionIDS(ctx context.Context, permissionIDS []string) error
		// DeleteMultiUnscopedByPermissionIDS 根据PermissionIDS删除多条数据
		DeleteMultiUnscopedByPermissionIDS(ctx context.Context, permissionIDS []string) error
		// DeleteMultiCacheByPermissionIDS 根据PermissionIDS删除多条数据，并删除缓存
		DeleteMultiCacheByPermissionIDS(ctx context.Context, permissionIDS []string) error
		// DeleteMultiUnscopedCacheByPermissionIDS 根据PermissionIDS删除多条数据，并删除缓存
		DeleteMultiUnscopedCacheByPermissionIDS(ctx context.Context, permissionIDS []string) error
		// DeleteMultiByPermissionIDSTx 根据PermissionIDS删除多条数据(事务)
		DeleteMultiByPermissionIDSTx(ctx context.Context, tx *ai_boilerplate_dao.Query, permissionIDS []string) error
		// DeleteMultiUnscopedByPermissionIDSTx 根据PermissionIDS删除多条数据(事务)
		DeleteMultiUnscopedByPermissionIDSTx(ctx context.Context, tx *ai_boilerplate_dao.Query, permissionIDS []string) error
		// DeleteMultiCacheByPermissionIDSTx 根据PermissionIDS删除多条数据，并删除缓存(事务)
		DeleteMultiCacheByPermissionIDSTx(ctx context.Context, tx *ai_boilerplate_dao.Query, permissionIDS []string) error
		// DeleteMultiUnscopedCacheByPermissionIDSTx 根据PermissionIDS删除多条数据，并删除缓存(事务)
		DeleteMultiUnscopedCacheByPermissionIDSTx(ctx context.Context, tx *ai_boilerplate_dao.Query, permissionIDS []string) error
		// DeleteIndexCache 删除索引存在的缓存
		DeleteIndexCache(ctx context.Context, data ...*ai_boilerplate_model.SysAPI) error
	}
	SysAPIRepo struct {
		db       *gorm.DB
		cache    dbcache.IDBCache
		encoding encoding.API
	}
)

func NewSysAPIRepo(cfg *config.Repo) *SysAPIRepo {
	return &SysAPIRepo{
		db:       cfg.DB,
		cache:    cfg.Cache,
		encoding: cfg.Encoding,
	}
}

// NewData 实例化
func (s *SysAPIRepo) NewData() *ai_boilerplate_model.SysAPI {
	return &ai_boilerplate_model.SysAPI{}
}

// DeepCopy 深拷贝
func (s *SysAPIRepo) DeepCopy(data *ai_boilerplate_model.SysAPI) *ai_boilerplate_model.SysAPI {
	newData := new(ai_boilerplate_model.SysAPI)
	_ = copier.CopyWithOption(newData, data, copier.Option{DeepCopy: true})
	return newData
}

// CreateOne 创建一条数据
func (s *SysAPIRepo) CreateOne(ctx context.Context, data *ai_boilerplate_model.SysAPI) error {
	dao := ai_boilerplate_dao.Use(s.db).SysAPI
	err := dao.WithContext(ctx).Create(data)
	if err != nil {
		return err
	}
	return nil
}

// CreateOneCache 创建一条数据, 并删除缓存
func (s *SysAPIRepo) CreateOneCache(ctx context.Context, data *ai_boilerplate_model.SysAPI) error {
	dao := ai_boilerplate_dao.Use(s.db).SysAPI
	err := dao.WithContext(ctx).Create(data)
	if err != nil {
		return err
	}
	err = s.DeleteIndexCache(ctx, data)
	if err != nil {
		return err
	}
	return nil
}

// CreateOneByTx 创建一条数据(事务)
func (s *SysAPIRepo) CreateOneByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, data *ai_boilerplate_model.SysAPI) error {
	dao := tx.SysAPI
	err := dao.WithContext(ctx).Create(data)
	if err != nil {
		return err
	}
	return nil
}

// CreateOneCacheByTx 创建一条数据(事务), 并删除缓存
func (s *SysAPIRepo) CreateOneCacheByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, data *ai_boilerplate_model.SysAPI) error {
	dao := tx.SysAPI
	err := dao.WithContext(ctx).Create(data)
	if err != nil {
		return err
	}
	err = s.DeleteIndexCache(ctx, data)
	if err != nil {
		return err
	}
	return nil
}

// CreateBatch 批量创建数据
func (s *SysAPIRepo) CreateBatch(ctx context.Context, data []*ai_boilerplate_model.SysAPI, batchSize int) error {
	dao := ai_boilerplate_dao.Use(s.db).SysAPI
	err := dao.WithContext(ctx).CreateInBatches(data, batchSize)
	if err != nil {
		return err
	}
	return nil
}

// CreateBatchCache 批量创建数据, 并删除缓存
func (s *SysAPIRepo) CreateBatchCache(ctx context.Context, data []*ai_boilerplate_model.SysAPI, batchSize int) error {
	dao := ai_boilerplate_dao.Use(s.db).SysAPI
	err := dao.WithContext(ctx).CreateInBatches(data, batchSize)
	if err != nil {
		return err
	}
	err = s.DeleteIndexCache(ctx, data...)
	if err != nil {
		return err
	}
	return nil
}

// CreateBatchByTx 批量创建数据(事务)
func (s *SysAPIRepo) CreateBatchByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, data []*ai_boilerplate_model.SysAPI, batchSize int) error {
	dao := tx.SysAPI
	err := dao.WithContext(ctx).CreateInBatches(data, batchSize)
	if err != nil {
		return err
	}
	return nil
}

// CreateBatchCacheByTx 批量创建数据(事务), 并删除缓存
func (s *SysAPIRepo) CreateBatchCacheByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, data []*ai_boilerplate_model.SysAPI, batchSize int) error {
	dao := tx.SysAPI
	err := dao.WithContext(ctx).CreateInBatches(data, batchSize)
	if err != nil {
		return err
	}
	err = s.DeleteIndexCache(ctx, data...)
	if err != nil {
		return err
	}
	return nil
}

// UpsertOne Upsert一条数据
// Update all columns, except primary keys, to new value on conflict
func (s *SysAPIRepo) UpsertOne(ctx context.Context, data *ai_boilerplate_model.SysAPI) error {
	dao := ai_boilerplate_dao.Use(s.db).SysAPI
	err := dao.WithContext(ctx).Save(data)
	if err != nil {
		return err
	}
	return nil
}

// UpsertOneCache Upsert一条数据, 并删除缓存
// Update all columns, except primary keys, to new value on conflict
func (s *SysAPIRepo) UpsertOneCache(ctx context.Context, data *ai_boilerplate_model.SysAPI) error {
	dao := ai_boilerplate_dao.Use(s.db).SysAPI
	oldData, err := dao.WithContext(ctx).Where(dao.ID.Eq(data.ID)).Unscoped().First()
	if err != nil && !errors.Is(err, gorm.ErrRecordNotFound) {
		return err
	}
	err = dao.WithContext(ctx).Save(data)
	if err != nil {
		return err
	}
	err = s.DeleteIndexCache(ctx, oldData, data)
	if err != nil {
		return err
	}
	return nil
}

// UpsertOneByTx Upsert一条数据(事务)
// Update all columns, except primary keys, to new value on conflict
func (s *SysAPIRepo) UpsertOneByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, data *ai_boilerplate_model.SysAPI) error {
	dao := tx.SysAPI
	err := dao.WithContext(ctx).Save(data)
	if err != nil {
		return err
	}
	return nil
}

// UpsertOneCacheByTx Upsert一条数据(事务), 并删除缓存
// Update all columns, except primary keys, to new value on conflict
func (s *SysAPIRepo) UpsertOneCacheByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, data *ai_boilerplate_model.SysAPI) error {
	dao := tx.SysAPI
	oldData, err := dao.WithContext(ctx).Where(dao.ID.Eq(data.ID)).Unscoped().First()
	if err != nil && !errors.Is(err, gorm.ErrRecordNotFound) {
		return err
	}
	err = dao.WithContext(ctx).Save(data)
	if err != nil {
		return err
	}
	err = s.DeleteIndexCache(ctx, oldData, data)
	if err != nil {
		return err
	}
	return nil
}

// UpsertOneByFields 根据fields字段Upsert一条数据
func (s *SysAPIRepo) UpsertOneByFields(ctx context.Context, data *ai_boilerplate_model.SysAPI, fields []string) error {
	if len(fields) == 0 {
		return errors.New("UpsertOneByFields fields is empty")
	}
	columns := make([]clause.Column, 0)
	for _, item := range fields {
		columns = append(columns, clause.Column{Name: item})
	}
	dao := ai_boilerplate_dao.Use(s.db).SysAPI
	err := dao.WithContext(ctx).Clauses(clause.OnConflict{
		Columns:   columns,
		UpdateAll: true,
	}).Create(data)
	if err != nil {
		return err
	}
	return nil
}

// UpsertOneCacheByFields 根据fields字段Upsert一条数据, 并删除缓存
func (s *SysAPIRepo) UpsertOneCacheByFields(ctx context.Context, data *ai_boilerplate_model.SysAPI, fields []string) error {
	if len(fields) == 0 {
		return errors.New("UpsertOneByFields fields is empty")
	}
	fieldNameToValue := make(map[string]interface{})
	typ := reflect.TypeOf(data).Elem()
	val := reflect.ValueOf(data).Elem()
	for i := 0; i < typ.NumField(); i++ {
		field := typ.Field(i)
		gormTag := field.Tag.Get("gorm")
		if gormTag != "" {
			gormTags := strings.Split(gormTag, ";")
			for _, item := range gormTags {
				if strings.Contains(item, "column") {
					columnName := strings.TrimPrefix(item, "column:")
					fieldValue := val.Field(i).Interface()
					fieldNameToValue[columnName] = fieldValue
					break
				}
			}
		}
	}
	whereExpressions := make([]clause.Expression, 0)
	columns := make([]clause.Column, 0)
	for _, item := range fields {
		whereExpressions = append(whereExpressions, clause.And(clause.Eq{Column: item, Value: fieldNameToValue[item]}))
		columns = append(columns, clause.Column{Name: item})
	}
	oldData := &ai_boilerplate_model.SysAPI{}
	err := s.db.Model(&ai_boilerplate_model.SysAPI{}).Clauses(whereExpressions...).Unscoped().First(oldData).Error
	if err != nil && !errors.Is(err, gorm.ErrRecordNotFound) {
		return err
	}
	dao := ai_boilerplate_dao.Use(s.db).SysAPI
	err = dao.WithContext(ctx).Clauses(clause.OnConflict{
		Columns:   columns,
		UpdateAll: true,
	}).Create(data)
	if err != nil {
		return err
	}
	err = s.DeleteIndexCache(ctx, oldData, data)
	if err != nil {
		return err
	}
	return nil
}

// UpsertOneByFieldsTx 根据fields字段Upsert一条数据(事务)
func (s *SysAPIRepo) UpsertOneByFieldsTx(ctx context.Context, tx *ai_boilerplate_dao.Query, data *ai_boilerplate_model.SysAPI, fields []string) error {
	if len(fields) == 0 {
		return errors.New("UpsertOneByFieldsTx fields is empty")
	}
	columns := make([]clause.Column, 0)
	for _, item := range fields {
		columns = append(columns, clause.Column{Name: item})
	}
	dao := tx.SysAPI
	err := dao.WithContext(ctx).Clauses(clause.OnConflict{
		Columns:   columns,
		UpdateAll: true,
	}).Create(data)
	if err != nil {
		return err
	}
	return nil
}

// UpsertOneCacheByFieldsTx 根据fields字段Upsert一条数据(事务), 并删除缓存
func (s *SysAPIRepo) UpsertOneCacheByFieldsTx(ctx context.Context, tx *ai_boilerplate_dao.Query, data *ai_boilerplate_model.SysAPI, fields []string) error {
	if len(fields) == 0 {
		return errors.New("UpsertOneByFieldsTx fields is empty")
	}
	fieldNameToValue := make(map[string]interface{})
	typ := reflect.TypeOf(data).Elem()
	val := reflect.ValueOf(data).Elem()
	for i := 0; i < typ.NumField(); i++ {
		field := typ.Field(i)
		gormTag := field.Tag.Get("gorm")
		if gormTag != "" {
			gormTags := strings.Split(gormTag, ";")
			for _, item := range gormTags {
				if strings.Contains(item, "column") {
					columnName := strings.TrimPrefix(item, "column:")
					fieldValue := val.Field(i).Interface()
					fieldNameToValue[columnName] = fieldValue
					break
				}
			}
		}
	}
	whereExpressions := make([]clause.Expression, 0)
	columns := make([]clause.Column, 0)
	for _, item := range fields {
		whereExpressions = append(whereExpressions, clause.And(clause.Eq{Column: item, Value: fieldNameToValue[item]}))
		columns = append(columns, clause.Column{Name: item})
	}
	oldData := &ai_boilerplate_model.SysAPI{}
	err := s.db.Model(&ai_boilerplate_model.SysAPI{}).Clauses(whereExpressions...).Unscoped().First(oldData).Error
	if err != nil && !errors.Is(err, gorm.ErrRecordNotFound) {
		return err
	}
	dao := tx.SysAPI
	err = dao.WithContext(ctx).Clauses(clause.OnConflict{
		Columns:   columns,
		UpdateAll: true,
	}).Create(data)
	if err != nil {
		return err
	}
	err = s.DeleteIndexCache(ctx, oldData, data)
	if err != nil {
		return err
	}
	return nil
}

// UpdateOne 更新一条数据
// data 中主键字段必须有值，零值不会被更新
func (s *SysAPIRepo) UpdateOne(ctx context.Context, newData *ai_boilerplate_model.SysAPI) error {
	dao := ai_boilerplate_dao.Use(s.db).SysAPI
	_, err := dao.WithContext(ctx).Updates(newData)
	if err != nil {
		return err
	}
	return nil
}

// UpdateOneUnscoped 更新一条数据（包括软删除）
// data 中主键字段必须有值，零值不会被更新
func (s *SysAPIRepo) UpdateOneUnscoped(ctx context.Context, newData *ai_boilerplate_model.SysAPI) error {
	dao := ai_boilerplate_dao.Use(s.db).SysAPI
	_, err := dao.WithContext(ctx).Unscoped().Updates(newData)
	if err != nil {
		return err
	}
	return nil
}

// UpdateOneCache 更新一条数据，并删除缓存
// data 中主键字段必须有值，零值不会被更新
// oldData 旧数据，删除缓存时使用
func (s *SysAPIRepo) UpdateOneCache(ctx context.Context, newData *ai_boilerplate_model.SysAPI, oldData *ai_boilerplate_model.SysAPI) error {
	dao := ai_boilerplate_dao.Use(s.db).SysAPI
	_, err := dao.WithContext(ctx).Updates(newData)
	if err != nil {
		return err
	}
	err = s.DeleteIndexCache(ctx, oldData, newData)
	if err != nil {
		return err
	}
	return nil
}

// UpdateOneUnscopedCache 更新一条数据，并删除缓存（包括软删除）
// data 中主键字段必须有值，零值不会被更新
// oldData 旧数据，删除缓存时使用
func (s *SysAPIRepo) UpdateOneUnscopedCache(ctx context.Context, newData *ai_boilerplate_model.SysAPI, oldData *ai_boilerplate_model.SysAPI) error {
	dao := ai_boilerplate_dao.Use(s.db).SysAPI
	_, err := dao.WithContext(ctx).Unscoped().Updates(newData)
	if err != nil {
		return err
	}
	err = s.DeleteIndexCache(ctx, oldData, newData)
	if err != nil {
		return err
	}
	return nil
}

// UpdateOneByTx 更新一条数据(事务)
// data 中主键字段必须有值，零值不会被更新
func (s *SysAPIRepo) UpdateOneByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, newData *ai_boilerplate_model.SysAPI) error {
	dao := tx.SysAPI
	_, err := dao.WithContext(ctx).Updates(newData)
	if err != nil {
		return err
	}
	return nil
}

// UpdateOneUnscopedByTx 更新一条数据(事务)（包括软删除）
// data 中主键字段必须有值，零值不会被更新
func (s *SysAPIRepo) UpdateOneUnscopedByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, newData *ai_boilerplate_model.SysAPI) error {
	dao := tx.SysAPI
	_, err := dao.WithContext(ctx).Unscoped().Updates(newData)
	if err != nil {
		return err
	}
	return nil
}

// UpdateOneCacheByTx 更新一条数据(事务)，并删除缓存
// data 中主键字段必须有值，零值不会被更新
// oldData 旧数据，删除缓存时使用
func (s *SysAPIRepo) UpdateOneCacheByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, newData *ai_boilerplate_model.SysAPI, oldData *ai_boilerplate_model.SysAPI) error {
	dao := tx.SysAPI
	_, err := dao.WithContext(ctx).Updates(newData)
	if err != nil {
		return err
	}
	err = s.DeleteIndexCache(ctx, oldData, newData)
	if err != nil {
		return err
	}
	return nil
}

// UpdateOneUnscopedCacheByTx 更新一条数据(事务)，并删除缓存（包括软删除）
// data 中主键字段必须有值，零值不会被更新
// oldData 旧数据，删除缓存时使用
func (s *SysAPIRepo) UpdateOneUnscopedCacheByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, newData *ai_boilerplate_model.SysAPI, oldData *ai_boilerplate_model.SysAPI) error {
	dao := tx.SysAPI
	_, err := dao.WithContext(ctx).Unscoped().Updates(newData)
	if err != nil {
		return err
	}
	err = s.DeleteIndexCache(ctx, oldData, newData)
	if err != nil {
		return err
	}
	return nil
}

// UpdateOneWithZero 更新一条数据,包含零值
// data 中主键字段必须有值,并且会更新所有字段,包括零值
func (s *SysAPIRepo) UpdateOneWithZero(ctx context.Context, newData *ai_boilerplate_model.SysAPI) error {
	dao := ai_boilerplate_dao.Use(s.db).SysAPI
	_, err := dao.WithContext(ctx).Select(dao.ALL.WithTable("")).Updates(newData)
	if err != nil {
		return err
	}
	return nil
}

// UpdateOneUnscopedWithZero 更新一条数据,包含零值（包括软删除）
// data 中主键字段必须有值,并且会更新所有字段,包括零值
func (s *SysAPIRepo) UpdateOneUnscopedWithZero(ctx context.Context, newData *ai_boilerplate_model.SysAPI) error {
	dao := ai_boilerplate_dao.Use(s.db).SysAPI
	_, err := dao.WithContext(ctx).Unscoped().Select(dao.ALL.WithTable("")).Updates(newData)
	if err != nil {
		return err
	}
	return nil
}

// UpdateOneCacheWithZero 更新一条数据,包含零值，并删除缓存
// data 中主键字段必须有值,并且会更新所有字段,包括零值
// oldData 旧数据，删除缓存时使用
func (s *SysAPIRepo) UpdateOneCacheWithZero(ctx context.Context, newData *ai_boilerplate_model.SysAPI, oldData *ai_boilerplate_model.SysAPI) error {
	dao := ai_boilerplate_dao.Use(s.db).SysAPI
	_, err := dao.WithContext(ctx).Select(dao.ALL.WithTable("")).Updates(newData)
	if err != nil {
		return err
	}
	err = s.DeleteIndexCache(ctx, oldData, newData)
	if err != nil {
		return err
	}
	return nil
}

// UpdateOneUnscopedCacheWithZero 更新一条数据,包含零值，并删除缓存（包括软删除）
// data 中主键字段必须有值,并且会更新所有字段,包括零值
// oldData 旧数据，删除缓存时使用
func (s *SysAPIRepo) UpdateOneUnscopedCacheWithZero(ctx context.Context, newData *ai_boilerplate_model.SysAPI, oldData *ai_boilerplate_model.SysAPI) error {
	dao := ai_boilerplate_dao.Use(s.db).SysAPI
	_, err := dao.WithContext(ctx).Unscoped().Select(dao.ALL.WithTable("")).Updates(newData)
	if err != nil {
		return err
	}
	err = s.DeleteIndexCache(ctx, oldData, newData)
	if err != nil {
		return err
	}
	return nil
}

// UpdateOneWithZeroByTx 更新一条数据(事务),包含零值，
// data 中主键字段必须有值,并且会更新所有字段,包括零值
func (s *SysAPIRepo) UpdateOneWithZeroByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, newData *ai_boilerplate_model.SysAPI) error {
	dao := tx.SysAPI
	_, err := dao.WithContext(ctx).Select(dao.ALL.WithTable("")).Updates(newData)
	if err != nil {
		return err
	}
	return nil
}

// UpdateOneUnscopedWithZeroByTx 更新一条数据(事务),包含零值（包括软删除）
// data 中主键字段必须有值,并且会更新所有字段,包括零值
func (s *SysAPIRepo) UpdateOneUnscopedWithZeroByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, newData *ai_boilerplate_model.SysAPI) error {
	dao := tx.SysAPI
	_, err := dao.WithContext(ctx).Unscoped().Select(dao.ALL.WithTable("")).Updates(newData)
	if err != nil {
		return err
	}
	return nil
}

// UpdateOneCacheWithZeroByTx 更新一条数据(事务),包含零值，并删除缓存
// data 中主键字段必须有值,并且会更新所有字段,包括零值
// oldData 旧数据，删除缓存时使用
func (s *SysAPIRepo) UpdateOneCacheWithZeroByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, newData *ai_boilerplate_model.SysAPI, oldData *ai_boilerplate_model.SysAPI) error {
	dao := tx.SysAPI
	_, err := dao.WithContext(ctx).Select(dao.ALL.WithTable("")).Updates(newData)
	if err != nil {
		return err
	}
	err = s.DeleteIndexCache(ctx, oldData, newData)
	if err != nil {
		return err
	}
	return nil
}

// UpdateOneUnscopedCacheWithZeroByTx 更新一条数据(事务),包含零值，并删除缓存（包括软删除）
// data 中主键字段必须有值,并且会更新所有字段,包括零值
// oldData 旧数据，删除缓存时使用
func (s *SysAPIRepo) UpdateOneUnscopedCacheWithZeroByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, newData *ai_boilerplate_model.SysAPI, oldData *ai_boilerplate_model.SysAPI) error {
	dao := tx.SysAPI
	_, err := dao.WithContext(ctx).Unscoped().Select(dao.ALL.WithTable("")).Updates(newData)
	if err != nil {
		return err
	}
	err = s.DeleteIndexCache(ctx, oldData, newData)
	if err != nil {
		return err
	}
	return nil
}

// UpdateBatchByID 根据字段ID批量更新,零值会被更新
func (s *SysAPIRepo) UpdateBatchByID(ctx context.Context, ID string, data map[string]interface{}) error {
	dao := ai_boilerplate_dao.Use(s.db).SysAPI
	_, err := dao.WithContext(ctx).Where(dao.ID.Eq(ID)).Updates(data)
	if err != nil {
		return err
	}
	return nil
}

// UpdateBatchUnscopedByID 根据字段ID批量更新,零值会被更新（包括软删除）
func (s *SysAPIRepo) UpdateBatchUnscopedByID(ctx context.Context, ID string, data map[string]interface{}) error {
	dao := ai_boilerplate_dao.Use(s.db).SysAPI
	_, err := dao.WithContext(ctx).Unscoped().Where(dao.ID.Eq(ID)).Updates(data)
	if err != nil {
		return err
	}
	return nil
}

// UpdateBatchByIDTx 根据字段ID批量更新(事务),零值会被更新
func (s *SysAPIRepo) UpdateBatchByIDTx(ctx context.Context, tx *ai_boilerplate_dao.Query, ID string, data map[string]interface{}) error {
	dao := tx.SysAPI
	_, err := dao.WithContext(ctx).Where(dao.ID.Eq(ID)).Updates(data)
	if err != nil {
		return err
	}
	return nil
}

// UpdateBatchUnscopedByIDTx 根据字段ID批量更新(事务),零值会被更新（包括软删除）
func (s *SysAPIRepo) UpdateBatchUnscopedByIDTx(ctx context.Context, tx *ai_boilerplate_dao.Query, ID string, data map[string]interface{}) error {
	dao := tx.SysAPI
	_, err := dao.WithContext(ctx).Unscoped().Where(dao.ID.Eq(ID)).Updates(data)
	if err != nil {
		return err
	}
	return nil
}

// UpdateBatchByIDS 根据字段IDS批量更新,零值会被更新
func (s *SysAPIRepo) UpdateBatchByIDS(ctx context.Context, IDS []string, data map[string]interface{}) error {
	dao := ai_boilerplate_dao.Use(s.db).SysAPI
	_, err := dao.WithContext(ctx).Where(dao.ID.In(IDS...)).Updates(data)
	if err != nil {
		return err
	}
	return nil
}

// UpdateBatchUnscopedByIDS 根据字段IDS批量更新,零值会被更新（包括软删除）
func (s *SysAPIRepo) UpdateBatchUnscopedByIDS(ctx context.Context, IDS []string, data map[string]interface{}) error {
	dao := ai_boilerplate_dao.Use(s.db).SysAPI
	_, err := dao.WithContext(ctx).Unscoped().Where(dao.ID.In(IDS...)).Updates(data)
	if err != nil {
		return err
	}
	return nil
}

// UpdateBatchByIDSTx 根据字段IDS批量更新(事务),零值会被更新
func (s *SysAPIRepo) UpdateBatchByIDSTx(ctx context.Context, tx *ai_boilerplate_dao.Query, IDS []string, data map[string]interface{}) error {
	dao := tx.SysAPI
	_, err := dao.WithContext(ctx).Where(dao.ID.In(IDS...)).Updates(data)
	if err != nil {
		return err
	}
	return nil
}

// UpdateBatchUnscopedByIDSTx 根据字段IDS批量更新(事务),零值会被更新（包括软删除）
func (s *SysAPIRepo) UpdateBatchUnscopedByIDSTx(ctx context.Context, tx *ai_boilerplate_dao.Query, IDS []string, data map[string]interface{}) error {
	dao := tx.SysAPI
	_, err := dao.WithContext(ctx).Unscoped().Where(dao.ID.In(IDS...)).Updates(data)
	if err != nil {
		return err
	}
	return nil
}

// UpdateBatchByPermissionID 根据字段PermissionID批量更新,零值会被更新
func (s *SysAPIRepo) UpdateBatchByPermissionID(ctx context.Context, permissionID string, data map[string]interface{}) error {
	dao := ai_boilerplate_dao.Use(s.db).SysAPI
	_, err := dao.WithContext(ctx).Where(dao.PermissionID.Eq(permissionID)).Updates(data)
	if err != nil {
		return err
	}
	return nil
}

// UpdateBatchUnscopedByPermissionID 根据字段PermissionID批量更新,零值会被更新（包括软删除）
func (s *SysAPIRepo) UpdateBatchUnscopedByPermissionID(ctx context.Context, permissionID string, data map[string]interface{}) error {
	dao := ai_boilerplate_dao.Use(s.db).SysAPI
	_, err := dao.WithContext(ctx).Unscoped().Where(dao.PermissionID.Eq(permissionID)).Updates(data)
	if err != nil {
		return err
	}
	return nil
}

// UpdateBatchByPermissionIDTx 根据字段PermissionID批量更新(事务),零值会被更新
func (s *SysAPIRepo) UpdateBatchByPermissionIDTx(ctx context.Context, tx *ai_boilerplate_dao.Query, permissionID string, data map[string]interface{}) error {
	dao := tx.SysAPI
	_, err := dao.WithContext(ctx).Where(dao.PermissionID.Eq(permissionID)).Updates(data)
	if err != nil {
		return err
	}
	return nil
}

// UpdateBatchUnscopedByPermissionIDTx 根据字段PermissionID批量更新(事务),零值会被更新（包括软删除）
func (s *SysAPIRepo) UpdateBatchUnscopedByPermissionIDTx(ctx context.Context, tx *ai_boilerplate_dao.Query, permissionID string, data map[string]interface{}) error {
	dao := tx.SysAPI
	_, err := dao.WithContext(ctx).Unscoped().Where(dao.PermissionID.Eq(permissionID)).Updates(data)
	if err != nil {
		return err
	}
	return nil
}

// UpdateBatchByPermissionIDS 根据字段PermissionIDS批量更新,零值会被更新
func (s *SysAPIRepo) UpdateBatchByPermissionIDS(ctx context.Context, permissionIDS []string, data map[string]interface{}) error {
	dao := ai_boilerplate_dao.Use(s.db).SysAPI
	_, err := dao.WithContext(ctx).Where(dao.PermissionID.In(permissionIDS...)).Updates(data)
	if err != nil {
		return err
	}
	return nil
}

// UpdateBatchUnscopedByPermissionIDS 根据字段PermissionIDS批量更新,零值会被更新（包括软删除）
func (s *SysAPIRepo) UpdateBatchUnscopedByPermissionIDS(ctx context.Context, permissionIDS []string, data map[string]interface{}) error {
	dao := ai_boilerplate_dao.Use(s.db).SysAPI
	_, err := dao.WithContext(ctx).Unscoped().Where(dao.PermissionID.In(permissionIDS...)).Updates(data)
	if err != nil {
		return err
	}
	return nil
}

// UpdateBatchByPermissionIDSTx 根据字段PermissionIDS批量更新(事务),零值会被更新
func (s *SysAPIRepo) UpdateBatchByPermissionIDSTx(ctx context.Context, tx *ai_boilerplate_dao.Query, permissionIDS []string, data map[string]interface{}) error {
	dao := tx.SysAPI
	_, err := dao.WithContext(ctx).Where(dao.PermissionID.In(permissionIDS...)).Updates(data)
	if err != nil {
		return err
	}
	return nil
}

// UpdateBatchUnscopedByPermissionIDSTx 根据字段PermissionIDS批量更新(事务),零值会被更新（包括软删除）
func (s *SysAPIRepo) UpdateBatchUnscopedByPermissionIDSTx(ctx context.Context, tx *ai_boilerplate_dao.Query, permissionIDS []string, data map[string]interface{}) error {
	dao := tx.SysAPI
	_, err := dao.WithContext(ctx).Unscoped().Where(dao.PermissionID.In(permissionIDS...)).Updates(data)
	if err != nil {
		return err
	}
	return nil
}

// FindOneByID 根据ID查询一条数据
func (s *SysAPIRepo) FindOneByID(ctx context.Context, ID string) (*ai_boilerplate_model.SysAPI, error) {
	dao := ai_boilerplate_dao.Use(s.db).SysAPI
	result, err := dao.WithContext(ctx).Where(dao.ID.Eq(ID)).First()
	if err != nil && !errors.Is(err, gorm.ErrRecordNotFound) {
		return nil, err
	}
	return result, nil
}

// FindOneUnscopedByID 根据ID查询一条数据（包括软删除）
func (s *SysAPIRepo) FindOneUnscopedByID(ctx context.Context, ID string) (*ai_boilerplate_model.SysAPI, error) {
	dao := ai_boilerplate_dao.Use(s.db).SysAPI
	result, err := dao.WithContext(ctx).Unscoped().Where(dao.ID.Eq(ID)).First()
	if err != nil && !errors.Is(err, gorm.ErrRecordNotFound) {
		return nil, err
	}
	return result, nil
}

// FindOneCacheByID 根据ID查询一条数据，并设置缓存
func (s *SysAPIRepo) FindOneCacheByID(ctx context.Context, ID string) (*ai_boilerplate_model.SysAPI, error) {
	resp := new(ai_boilerplate_model.SysAPI)
	cacheKey := s.cache.Key(CacheSysAPIByIDPrefix, ID)
	cacheValue, err := s.cache.Fetch(ctx, cacheKey, func() (string, error) {
		dao := ai_boilerplate_dao.Use(s.db).SysAPI
		result, err := dao.WithContext(ctx).Where(dao.ID.Eq(ID)).First()
		if err != nil && !errors.Is(err, gorm.ErrRecordNotFound) {
			return "", err
		}
		marshal, err := s.encoding.Marshal(result)
		if err != nil {
			return "", err
		}
		return string(marshal), nil
	}, s.cache.TTL())
	if err != nil {
		return nil, err
	}
	if cacheValue != "" {
		err = s.encoding.Unmarshal([]byte(cacheValue), resp)
		if err != nil {
			return nil, err
		}
	}
	return resp, nil
}

// FindOneUnscopedCacheByID 根据ID查询一条数据（包括软删除），并设置缓存
func (s *SysAPIRepo) FindOneUnscopedCacheByID(ctx context.Context, ID string) (*ai_boilerplate_model.SysAPI, error) {
	resp := new(ai_boilerplate_model.SysAPI)
	cacheKey := s.cache.Key(CacheSysAPIUnscopedByIDPrefix, ID)
	cacheValue, err := s.cache.Fetch(ctx, cacheKey, func() (string, error) {
		dao := ai_boilerplate_dao.Use(s.db).SysAPI
		result, err := dao.WithContext(ctx).Unscoped().Where(dao.ID.Eq(ID)).First()
		if err != nil && !errors.Is(err, gorm.ErrRecordNotFound) {
			return "", err
		}
		marshal, err := s.encoding.Marshal(result)
		if err != nil {
			return "", err
		}
		return string(marshal), nil
	}, s.cache.TTL())
	if err != nil {
		return nil, err
	}
	if cacheValue != "" {
		err = s.encoding.Unmarshal([]byte(cacheValue), resp)
		if err != nil {
			return nil, err
		}
	}
	return resp, nil
}

// FindMultiByIDS 根据IDS查询多条数据
func (s *SysAPIRepo) FindMultiByIDS(ctx context.Context, IDS []string) ([]*ai_boilerplate_model.SysAPI, error) {
	dao := ai_boilerplate_dao.Use(s.db).SysAPI
	result, err := dao.WithContext(ctx).Where(dao.ID.In(IDS...)).Find()
	if err != nil {
		return nil, err
	}
	return result, nil
}

// FindMultiUnscopedByIDS 根据IDS查询多条数据（包括软删除）
func (s *SysAPIRepo) FindMultiUnscopedByIDS(ctx context.Context, IDS []string) ([]*ai_boilerplate_model.SysAPI, error) {
	dao := ai_boilerplate_dao.Use(s.db).SysAPI
	result, err := dao.WithContext(ctx).Unscoped().Where(dao.ID.In(IDS...)).Find()
	if err != nil {
		return nil, err
	}
	return result, nil
}

// FindMultiCacheByIDS 根据IDS查询多条数据，并设置缓存
func (s *SysAPIRepo) FindMultiCacheByIDS(ctx context.Context, IDS []string) ([]*ai_boilerplate_model.SysAPI, error) {
	resp := make([]*ai_boilerplate_model.SysAPI, 0)
	cacheKeys := make([]string, 0)
	keyToParam := make(map[string]string)
	for _, item := range IDS {
		cacheKey := s.cache.Key(CacheSysAPIByIDPrefix, item)
		cacheKeys = append(cacheKeys, cacheKey)
		keyToParam[cacheKey] = item
	}
	cacheValue, err := s.cache.FetchBatch(ctx, cacheKeys, func(miss []string) (map[string]string, error) {
		dbValue := make(map[string]string)
		params := make([]string, 0)
		for _, item := range miss {
			dbValue[item] = ""
			params = append(params, keyToParam[item])
		}
		dao := ai_boilerplate_dao.Use(s.db).SysAPI
		result, err := dao.WithContext(ctx).Where(dao.ID.In(params...)).Find()
		if err != nil {
			return nil, err
		}
		for _, item := range result {
			marshal, err := s.encoding.Marshal(item)
			if err != nil {
				return nil, err
			}
			dbValue[s.cache.Key(CacheSysAPIByIDPrefix, item.ID)] = string(marshal)
		}
		return dbValue, nil
	}, s.cache.TTL())
	if err != nil {
		return nil, err
	}
	for _, cacheKey := range cacheKeys {
		if cacheValue[cacheKey] != "" {
			tmp := new(ai_boilerplate_model.SysAPI)
			err := s.encoding.Unmarshal([]byte(cacheValue[cacheKey]), tmp)
			if err != nil {
				return nil, err
			}
			resp = append(resp, tmp)
		}
	}
	return resp, nil
}

// FindMultiUnscopedCacheByIDS 根据IDS查询多条数据（包括软删除），并设置缓存
func (s *SysAPIRepo) FindMultiUnscopedCacheByIDS(ctx context.Context, IDS []string) ([]*ai_boilerplate_model.SysAPI, error) {
	resp := make([]*ai_boilerplate_model.SysAPI, 0)
	cacheKeys := make([]string, 0)
	keyToParam := make(map[string]string)
	for _, item := range IDS {
		cacheKey := s.cache.Key(CacheSysAPIUnscopedByIDPrefix, item)
		cacheKeys = append(cacheKeys, cacheKey)
		keyToParam[cacheKey] = item
	}
	cacheValue, err := s.cache.FetchBatch(ctx, cacheKeys, func(miss []string) (map[string]string, error) {
		dbValue := make(map[string]string)
		params := make([]string, 0)
		for _, item := range miss {
			dbValue[item] = ""
			params = append(params, keyToParam[item])
		}
		dao := ai_boilerplate_dao.Use(s.db).SysAPI
		result, err := dao.WithContext(ctx).Unscoped().Where(dao.ID.In(params...)).Find()
		if err != nil {
			return nil, err
		}
		for _, item := range result {
			marshal, err := s.encoding.Marshal(item)
			if err != nil {
				return nil, err
			}
			dbValue[s.cache.Key(CacheSysAPIUnscopedByIDPrefix, item.ID)] = string(marshal)
		}
		return dbValue, nil
	}, s.cache.TTL())
	if err != nil {
		return nil, err
	}
	for _, cacheKey := range cacheKeys {
		if cacheValue[cacheKey] != "" {
			tmp := new(ai_boilerplate_model.SysAPI)
			err := s.encoding.Unmarshal([]byte(cacheValue[cacheKey]), tmp)
			if err != nil {
				return nil, err
			}
			resp = append(resp, tmp)
		}
	}
	return resp, nil
}

// FindMultiByPermissionID 根据permissionID查询多条数据
func (s *SysAPIRepo) FindMultiByPermissionID(ctx context.Context, permissionID string) ([]*ai_boilerplate_model.SysAPI, error) {
	dao := ai_boilerplate_dao.Use(s.db).SysAPI
	result, err := dao.WithContext(ctx).Where(dao.PermissionID.Eq(permissionID)).Find()
	if err != nil {
		return nil, err
	}
	return result, nil
}

// FindMultiUnscopedByPermissionID 根据permissionID查询多条数据（包括软删除）
func (s *SysAPIRepo) FindMultiUnscopedByPermissionID(ctx context.Context, permissionID string) ([]*ai_boilerplate_model.SysAPI, error) {
	dao := ai_boilerplate_dao.Use(s.db).SysAPI
	result, err := dao.WithContext(ctx).Unscoped().Where(dao.PermissionID.Eq(permissionID)).Find()
	if err != nil {
		return nil, err
	}
	return result, nil
}

// FindMultiCacheByPermissionID 根据permissionID查询多条数据，并设置缓存
func (s *SysAPIRepo) FindMultiCacheByPermissionID(ctx context.Context, permissionID string) ([]*ai_boilerplate_model.SysAPI, error) {
	resp := make([]*ai_boilerplate_model.SysAPI, 0)
	cacheKey := s.cache.Key(CacheSysAPIByPermissionIDPrefix, permissionID)
	cacheValue, err := s.cache.Fetch(ctx, cacheKey, func() (string, error) {
		dao := ai_boilerplate_dao.Use(s.db).SysAPI
		result, err := dao.WithContext(ctx).Where(dao.PermissionID.Eq(permissionID)).Find()
		if err != nil && !errors.Is(err, gorm.ErrRecordNotFound) {
			return "", err
		}
		marshal, err := s.encoding.Marshal(result)
		if err != nil {
			return "", err
		}
		return string(marshal), nil
	}, s.cache.TTL())
	if err != nil {
		return nil, err
	}
	if cacheValue != "" {
		err = s.encoding.Unmarshal([]byte(cacheValue), &resp)
		if err != nil {
			return nil, err
		}
	}
	return resp, nil
}

// FindMultiUnscopedCacheByPermissionID 根据permissionID查询多条数据（包括软删除），并设置缓存
func (s *SysAPIRepo) FindMultiUnscopedCacheByPermissionID(ctx context.Context, permissionID string) ([]*ai_boilerplate_model.SysAPI, error) {
	resp := make([]*ai_boilerplate_model.SysAPI, 0)
	cacheKey := s.cache.Key(CacheSysAPIUnscopedByPermissionIDPrefix, permissionID)
	cacheValue, err := s.cache.Fetch(ctx, cacheKey, func() (string, error) {
		dao := ai_boilerplate_dao.Use(s.db).SysAPI
		result, err := dao.WithContext(ctx).Unscoped().Where(dao.PermissionID.Eq(permissionID)).Find()
		if err != nil && !errors.Is(err, gorm.ErrRecordNotFound) {
			return "", err
		}
		marshal, err := s.encoding.Marshal(result)
		if err != nil {
			return "", err
		}
		return string(marshal), nil
	}, s.cache.TTL())
	if err != nil {
		return nil, err
	}
	if cacheValue != "" {
		err = s.encoding.Unmarshal([]byte(cacheValue), &resp)
		if err != nil {
			return nil, err
		}
	}
	return resp, nil
}

// FindMultiByPermissionIDS 根据permissionIDS查询多条数据
func (s *SysAPIRepo) FindMultiByPermissionIDS(ctx context.Context, permissionIDS []string) ([]*ai_boilerplate_model.SysAPI, error) {
	dao := ai_boilerplate_dao.Use(s.db).SysAPI
	result, err := dao.WithContext(ctx).Where(dao.PermissionID.In(permissionIDS...)).Find()
	if err != nil {
		return nil, err
	}
	return result, nil
}

// FindMultiUnscopedByPermissionIDS 根据permissionIDS查询多条数据（包括软删除）
func (s *SysAPIRepo) FindMultiUnscopedByPermissionIDS(ctx context.Context, permissionIDS []string) ([]*ai_boilerplate_model.SysAPI, error) {
	dao := ai_boilerplate_dao.Use(s.db).SysAPI
	result, err := dao.WithContext(ctx).Unscoped().Where(dao.PermissionID.In(permissionIDS...)).Find()
	if err != nil {
		return nil, err
	}
	return result, nil
}

// FindMultiCacheByPermissionIDS 根据permissionIDS查询多条数据，并设置缓存
func (s *SysAPIRepo) FindMultiCacheByPermissionIDS(ctx context.Context, permissionIDS []string) ([]*ai_boilerplate_model.SysAPI, error) {
	resp := make([]*ai_boilerplate_model.SysAPI, 0)
	cacheKeys := make([]string, 0)
	keyToParam := make(map[string]string)
	for _, item := range permissionIDS {
		cacheKey := s.cache.Key(CacheSysAPIByPermissionIDPrefix, item)
		cacheKeys = append(cacheKeys, cacheKey)
		keyToParam[cacheKey] = item
	}
	cacheValue, err := s.cache.FetchBatch(ctx, cacheKeys, func(miss []string) (map[string]string, error) {
		dbValue := make(map[string]string)
		params := make([]string, 0)
		for _, item := range miss {
			dbValue[item] = ""
			params = append(params, keyToParam[item])
		}
		dao := ai_boilerplate_dao.Use(s.db).SysAPI
		result, err := dao.WithContext(ctx).Where(dao.PermissionID.In(params...)).Find()
		if err != nil {
			return nil, err
		}
		keyToValues := make(map[string][]*ai_boilerplate_model.SysAPI)
		for _, item := range result {
			key := s.cache.Key(CacheSysAPIByPermissionIDPrefix, item.PermissionID)
			if keyToValues[key] == nil {
				keyToValues[key] = make([]*ai_boilerplate_model.SysAPI, 0)
			}
			keyToValues[key] = append(keyToValues[key], item)
		}
		for item := range dbValue {
			if keyToValues[item] != nil {
				marshal, err := s.encoding.Marshal(keyToValues[item])
				if err != nil {
					return nil, err
				}
				dbValue[item] = string(marshal)
			}
		}
		return dbValue, nil
	}, s.cache.TTL())
	if err != nil {
		return nil, err
	}
	for _, cacheKey := range cacheKeys {
		if cacheValue[cacheKey] != "" {
			tmp := make([]*ai_boilerplate_model.SysAPI, 0)
			err := s.encoding.Unmarshal([]byte(cacheValue[cacheKey]), &tmp)
			if err != nil {
				return nil, err
			}
			resp = append(resp, tmp...)
		}
	}
	return resp, nil
}

// FindMultiUnscopedCacheByPermissionIDS 根据permissionIDS查询多条数据（包括软删除），并设置缓存
func (s *SysAPIRepo) FindMultiUnscopedCacheByPermissionIDS(ctx context.Context, permissionIDS []string) ([]*ai_boilerplate_model.SysAPI, error) {
	resp := make([]*ai_boilerplate_model.SysAPI, 0)
	cacheKeys := make([]string, 0)
	keyToParam := make(map[string]string)
	for _, item := range permissionIDS {
		cacheKey := s.cache.Key(CacheSysAPIUnscopedByPermissionIDPrefix, item)
		cacheKeys = append(cacheKeys, cacheKey)
		keyToParam[cacheKey] = item
	}
	cacheValue, err := s.cache.FetchBatch(ctx, cacheKeys, func(miss []string) (map[string]string, error) {
		dbValue := make(map[string]string)
		params := make([]string, 0)
		for _, item := range miss {
			dbValue[item] = ""
			params = append(params, keyToParam[item])
		}
		dao := ai_boilerplate_dao.Use(s.db).SysAPI
		result, err := dao.WithContext(ctx).Unscoped().Where(dao.PermissionID.In(params...)).Find()
		if err != nil {
			return nil, err
		}
		keyToValues := make(map[string][]*ai_boilerplate_model.SysAPI)
		for _, item := range result {
			key := s.cache.Key(CacheSysAPIUnscopedByPermissionIDPrefix, item.PermissionID)
			if keyToValues[key] == nil {
				keyToValues[key] = make([]*ai_boilerplate_model.SysAPI, 0)
			}
			keyToValues[key] = append(keyToValues[key], item)
		}
		for item := range dbValue {
			if keyToValues[item] != nil {
				marshal, err := s.encoding.Marshal(keyToValues[item])
				if err != nil {
					return nil, err
				}
				dbValue[item] = string(marshal)
			}
		}
		return dbValue, nil
	}, s.cache.TTL())
	if err != nil {
		return nil, err
	}
	for _, cacheKey := range cacheKeys {
		if cacheValue[cacheKey] != "" {
			tmp := make([]*ai_boilerplate_model.SysAPI, 0)
			err := s.encoding.Unmarshal([]byte(cacheValue[cacheKey]), &tmp)
			if err != nil {
				return nil, err
			}
			resp = append(resp, tmp...)
		}
	}
	return resp, nil
}

// FindMultiByCondition 自定义查询数据(通用)
// 非万能查询方法,请评估后谨慎使用
func (s *SysAPIRepo) FindMultiByCondition(ctx context.Context, conditionReq *condition.Req) ([]*ai_boilerplate_model.SysAPI, *condition.Reply, error) {
	result := make([]*ai_boilerplate_model.SysAPI, 0)
	conditionReply := &condition.Reply{}
	var total int64
	whereExpressions, orderExpressions, err := conditionReq.ConvertToGormExpression(ai_boilerplate_model.SysAPI{})
	if err != nil {
		return result, conditionReply, err
	}
	if conditionReq.Page != 0 && conditionReq.PageSize != 0 {
		err = s.db.WithContext(ctx).Model(&ai_boilerplate_model.SysAPI{}).Clauses(whereExpressions...).Count(&total).Error
		if err != nil {
			return result, conditionReply, err
		}
		if total == 0 {
			return result, conditionReply, nil
		}
		conditionReply, err = conditionReq.ConvertToPage(int32(total))
		if err != nil {
			return result, conditionReply, err
		}
		query := s.db.WithContext(ctx).Model(&ai_boilerplate_model.SysAPI{}).Clauses(whereExpressions...).Clauses(orderExpressions...)
		if conditionReply.Page != 0 && conditionReply.PageSize != 0 {
			query = query.Offset(int((conditionReply.Page - 1) * conditionReply.PageSize))
			query = query.Limit(int(conditionReply.PageSize))
		}
		err = query.Find(&result).Error
		if err != nil {
			return result, conditionReply, err
		}
	} else {
		err = s.db.WithContext(ctx).Model(&ai_boilerplate_model.SysAPI{}).Clauses(whereExpressions...).Clauses(orderExpressions...).Find(&result).Error
		if err != nil {
			return result, conditionReply, err
		}
		conditionReply.Total = int32(len(result))
	}
	return result, conditionReply, err
}

// FindMultiUnscopedByCondition 自定义查询数据(通用)（包括软删除）
// 非万能查询方法,请评估后谨慎使用
func (s *SysAPIRepo) FindMultiUnscopedByCondition(ctx context.Context, conditionReq *condition.Req) ([]*ai_boilerplate_model.SysAPI, *condition.Reply, error) {
	result := make([]*ai_boilerplate_model.SysAPI, 0)
	conditionReply := &condition.Reply{}
	var total int64
	whereExpressions, orderExpressions, err := conditionReq.ConvertToGormExpression(ai_boilerplate_model.SysAPI{})
	if err != nil {
		return result, conditionReply, err
	}
	if conditionReq.Page != 0 && conditionReq.PageSize != 0 {
		err = s.db.WithContext(ctx).Model(&ai_boilerplate_model.SysAPI{}).Unscoped().Clauses(whereExpressions...).Count(&total).Error
		if err != nil {
			return result, conditionReply, err
		}
		if total == 0 {
			return result, conditionReply, nil
		}
		conditionReply, err = conditionReq.ConvertToPage(int32(total))
		if err != nil {
			return result, conditionReply, err
		}
		query := s.db.WithContext(ctx).Model(&ai_boilerplate_model.SysAPI{}).Unscoped().Clauses(whereExpressions...).Clauses(orderExpressions...)
		if conditionReply.Page != 0 && conditionReply.PageSize != 0 {
			query = query.Offset(int((conditionReply.Page - 1) * conditionReply.PageSize))
			query = query.Limit(int(conditionReply.PageSize))
		}
		err = query.Find(&result).Error
		if err != nil {
			return result, conditionReply, err
		}
	} else {
		err = s.db.WithContext(ctx).Model(&ai_boilerplate_model.SysAPI{}).Unscoped().Clauses(whereExpressions...).Clauses(orderExpressions...).Find(&result).Error
		if err != nil {
			return result, conditionReply, err
		}
		conditionReply.Total = int32(len(result))
	}
	return result, conditionReply, err
}

// FindMultiCacheByCondition 自定义查询数据(通用),并设置缓存
// 非万能查询方法,缓存命中率低,请评估后谨慎使用
func (s *SysAPIRepo) FindMultiCacheByCondition(ctx context.Context, conditionReq *condition.Req) ([]*ai_boilerplate_model.SysAPI, *condition.Reply, error) {
	type Tmp struct {
		Result         []*ai_boilerplate_model.SysAPI
		ConditionReply *condition.Reply
	}
	tmp := Tmp{
		Result:         make([]*ai_boilerplate_model.SysAPI, 0),
		ConditionReply: &condition.Reply{},
	}
	cacheKey := s.cache.Key(CacheSysAPIByConditionPrefix)
	cacheField := conditionReq.ConvertToCacheField()
	cacheValue, err := s.cache.FetchHash(ctx, cacheKey, cacheField, func() (string, error) {
		result, conditionReply, err := s.FindMultiByCondition(ctx, conditionReq)
		if err != nil {
			return "", err
		}
		tmp.Result = result
		tmp.ConditionReply = conditionReply
		marshal, err := s.encoding.Marshal(tmp)
		if err != nil {
			return "", err
		}
		return string(marshal), nil
	}, s.cache.TTL())
	if err != nil {
		return tmp.Result, tmp.ConditionReply, err
	}
	if cacheValue != "" {
		err = s.encoding.Unmarshal([]byte(cacheValue), &tmp)
		if err != nil {
			return tmp.Result, tmp.ConditionReply, err
		}
	}
	return tmp.Result, tmp.ConditionReply, nil
}

// FindMultiUnscopedCacheByCondition 自定义查询数据(通用)（包括软删除）,并设置缓存
// 非万能查询方法,缓存命中率低,请评估后谨慎使用
func (s *SysAPIRepo) FindMultiUnscopedCacheByCondition(ctx context.Context, conditionReq *condition.Req) ([]*ai_boilerplate_model.SysAPI, *condition.Reply, error) {
	type Tmp struct {
		Result         []*ai_boilerplate_model.SysAPI
		ConditionReply *condition.Reply
	}
	tmp := Tmp{
		Result:         make([]*ai_boilerplate_model.SysAPI, 0),
		ConditionReply: &condition.Reply{},
	}
	cacheKey := s.cache.Key(CacheSysAPIUnscopedByConditionPrefix)
	cacheField := conditionReq.ConvertToCacheField()
	cacheValue, err := s.cache.FetchHash(ctx, cacheKey, cacheField, func() (string, error) {
		result, conditionReply, err := s.FindMultiUnscopedByCondition(ctx, conditionReq)
		if err != nil {
			return "", err
		}
		tmp.Result = result
		tmp.ConditionReply = conditionReply
		marshal, err := s.encoding.Marshal(tmp)
		if err != nil {
			return "", err
		}
		return string(marshal), nil
	}, s.cache.TTL())
	if err != nil {
		return tmp.Result, tmp.ConditionReply, err
	}
	if cacheValue != "" {
		err = s.encoding.Unmarshal([]byte(cacheValue), &tmp)
		if err != nil {
			return tmp.Result, tmp.ConditionReply, err
		}
	}
	return tmp.Result, tmp.ConditionReply, nil
}

// DeleteOneByID 根据ID删除一条数据
func (s *SysAPIRepo) DeleteOneByID(ctx context.Context, ID string) error {
	dao := ai_boilerplate_dao.Use(s.db).SysAPI
	_, err := dao.WithContext(ctx).Where(dao.ID.Eq(ID)).Delete()
	if err != nil {
		return err
	}
	return nil
}

// DeleteOneUnscopedByID 根据ID删除一条数据
func (s *SysAPIRepo) DeleteOneUnscopedByID(ctx context.Context, ID string) error {
	dao := ai_boilerplate_dao.Use(s.db).SysAPI
	_, err := dao.WithContext(ctx).Unscoped().Where(dao.ID.Eq(ID)).Delete()
	if err != nil {
		return err
	}
	return nil
}

// DeleteOneCacheByID 根据ID删除一条数据，并删除缓存
func (s *SysAPIRepo) DeleteOneCacheByID(ctx context.Context, ID string) error {
	dao := ai_boilerplate_dao.Use(s.db).SysAPI
	result, err := dao.WithContext(ctx).Where(dao.ID.Eq(ID)).First()
	if err != nil && !errors.Is(err, gorm.ErrRecordNotFound) {
		return err
	}
	if result == nil {
		return nil
	}
	_, err = dao.WithContext(ctx).Where(dao.ID.Eq(ID)).Delete()
	if err != nil {
		return err
	}
	err = s.DeleteIndexCache(ctx, result)
	if err != nil {
		return err
	}
	return nil
}

// DeleteOneUnscopedCacheByID 根据ID删除一条数据，并删除缓存
func (s *SysAPIRepo) DeleteOneUnscopedCacheByID(ctx context.Context, ID string) error {
	dao := ai_boilerplate_dao.Use(s.db).SysAPI
	result, err := dao.WithContext(ctx).Unscoped().Where(dao.ID.Eq(ID)).First()
	if err != nil && !errors.Is(err, gorm.ErrRecordNotFound) {
		return err
	}
	if result == nil {
		return nil
	}
	_, err = dao.WithContext(ctx).Unscoped().Where(dao.ID.Eq(ID)).Delete()
	if err != nil {
		return err
	}
	err = s.DeleteIndexCache(ctx, result)
	if err != nil {
		return err
	}
	return nil
}

// DeleteOneByIDTx 根据ID删除一条数据
func (s *SysAPIRepo) DeleteOneByIDTx(ctx context.Context, tx *ai_boilerplate_dao.Query, ID string) error {
	dao := tx.SysAPI
	_, err := dao.WithContext(ctx).Where(dao.ID.Eq(ID)).Delete()
	if err != nil {
		return err
	}
	return nil
}

// DeleteOneUnscopedByIDTx 根据ID删除一条数据
func (s *SysAPIRepo) DeleteOneUnscopedByIDTx(ctx context.Context, tx *ai_boilerplate_dao.Query, ID string) error {
	dao := tx.SysAPI
	_, err := dao.WithContext(ctx).Unscoped().Where(dao.ID.Eq(ID)).Delete()
	if err != nil {
		return err
	}
	return nil
}

// DeleteOneCacheByIDTx 根据ID删除一条数据，并删除缓存
func (s *SysAPIRepo) DeleteOneCacheByIDTx(ctx context.Context, tx *ai_boilerplate_dao.Query, ID string) error {
	dao := tx.SysAPI
	result, err := dao.WithContext(ctx).Where(dao.ID.Eq(ID)).First()
	if err != nil && !errors.Is(err, gorm.ErrRecordNotFound) {
		return err
	}
	if result == nil {
		return nil
	}
	_, err = dao.WithContext(ctx).Where(dao.ID.Eq(ID)).Delete()
	if err != nil {
		return err
	}
	err = s.DeleteIndexCache(ctx, result)
	if err != nil {
		return err
	}
	return nil
}

// DeleteOneUnscopedCacheByIDTx 根据ID删除一条数据，并删除缓存
func (s *SysAPIRepo) DeleteOneUnscopedCacheByIDTx(ctx context.Context, tx *ai_boilerplate_dao.Query, ID string) error {
	dao := tx.SysAPI
	result, err := dao.WithContext(ctx).Unscoped().Where(dao.ID.Eq(ID)).First()
	if err != nil && !errors.Is(err, gorm.ErrRecordNotFound) {
		return err
	}
	if result == nil {
		return nil
	}
	_, err = dao.WithContext(ctx).Unscoped().Where(dao.ID.Eq(ID)).Delete()
	if err != nil {
		return err
	}
	err = s.DeleteIndexCache(ctx, result)
	if err != nil {
		return err
	}
	return nil
}

// DeleteMultiByIDS 根据IDS删除多条数据
func (s *SysAPIRepo) DeleteMultiByIDS(ctx context.Context, IDS []string) error {
	dao := ai_boilerplate_dao.Use(s.db).SysAPI
	_, err := dao.WithContext(ctx).Where(dao.ID.In(IDS...)).Delete()
	if err != nil {
		return err
	}
	return nil
}

// DeleteMultiUnscopedByIDS 根据IDS删除多条数据
func (s *SysAPIRepo) DeleteMultiUnscopedByIDS(ctx context.Context, IDS []string) error {
	dao := ai_boilerplate_dao.Use(s.db).SysAPI
	_, err := dao.WithContext(ctx).Unscoped().Where(dao.ID.In(IDS...)).Delete()
	if err != nil {
		return err
	}
	return nil
}

// DeleteMultiCacheByIDS 根据IDS删除多条数据，并删除缓存
func (s *SysAPIRepo) DeleteMultiCacheByIDS(ctx context.Context, IDS []string) error {
	dao := ai_boilerplate_dao.Use(s.db).SysAPI
	result, err := dao.WithContext(ctx).Where(dao.ID.In(IDS...)).Find()
	if err != nil {
		return err
	}
	if len(result) == 0 {
		return nil
	}
	_, err = dao.WithContext(ctx).Where(dao.ID.In(IDS...)).Delete()
	if err != nil {
		return err
	}
	err = s.DeleteIndexCache(ctx, result...)
	if err != nil {
		return err
	}
	return nil
}

// DeleteMultiUnscopedCacheByIDS 根据IDS删除多条数据，并删除缓存
func (s *SysAPIRepo) DeleteMultiUnscopedCacheByIDS(ctx context.Context, IDS []string) error {
	dao := ai_boilerplate_dao.Use(s.db).SysAPI
	result, err := dao.WithContext(ctx).Unscoped().Where(dao.ID.In(IDS...)).Find()
	if err != nil {
		return err
	}
	if len(result) == 0 {
		return nil
	}
	_, err = dao.WithContext(ctx).Unscoped().Where(dao.ID.In(IDS...)).Delete()
	if err != nil {
		return err
	}
	err = s.DeleteIndexCache(ctx, result...)
	if err != nil {
		return err
	}
	return nil
}

// DeleteMultiByIDSTx 根据IDS删除多条数据
func (s *SysAPIRepo) DeleteMultiByIDSTx(ctx context.Context, tx *ai_boilerplate_dao.Query, IDS []string) error {
	dao := tx.SysAPI
	_, err := dao.WithContext(ctx).Where(dao.ID.In(IDS...)).Delete()
	if err != nil {
		return err
	}
	return nil
}

// DeleteMultiUnscopedByIDSTx 根据IDS删除多条数据
func (s *SysAPIRepo) DeleteMultiUnscopedByIDSTx(ctx context.Context, tx *ai_boilerplate_dao.Query, IDS []string) error {
	dao := tx.SysAPI
	_, err := dao.WithContext(ctx).Unscoped().Where(dao.ID.In(IDS...)).Delete()
	if err != nil {
		return err
	}
	return nil
}

// DeleteMultiCacheByIDSTx 根据IDS删除多条数据，并删除缓存
func (s *SysAPIRepo) DeleteMultiCacheByIDSTx(ctx context.Context, tx *ai_boilerplate_dao.Query, IDS []string) error {
	dao := tx.SysAPI
	result, err := dao.WithContext(ctx).Where(dao.ID.In(IDS...)).Find()
	if err != nil {
		return err
	}
	if len(result) == 0 {
		return nil
	}
	_, err = dao.WithContext(ctx).Where(dao.ID.In(IDS...)).Delete()
	if err != nil {
		return err
	}
	err = s.DeleteIndexCache(ctx, result...)
	if err != nil {
		return err
	}
	return nil
}

// DeleteMultiUnscopedCacheByIDSTx 根据IDS删除多条数据，并删除缓存
func (s *SysAPIRepo) DeleteMultiUnscopedCacheByIDSTx(ctx context.Context, tx *ai_boilerplate_dao.Query, IDS []string) error {
	dao := tx.SysAPI
	result, err := dao.WithContext(ctx).Unscoped().Where(dao.ID.In(IDS...)).Find()
	if err != nil {
		return err
	}
	if len(result) == 0 {
		return nil
	}
	_, err = dao.WithContext(ctx).Unscoped().Where(dao.ID.In(IDS...)).Delete()
	if err != nil {
		return err
	}
	err = s.DeleteIndexCache(ctx, result...)
	if err != nil {
		return err
	}
	return nil
}

// DeleteMultiByPermissionID 根据PermissionID删除多条数据
func (s *SysAPIRepo) DeleteMultiByPermissionID(ctx context.Context, permissionID string) error {
	dao := ai_boilerplate_dao.Use(s.db).SysAPI
	_, err := dao.WithContext(ctx).Where(dao.PermissionID.Eq(permissionID)).Delete()
	if err != nil {
		return err
	}
	return nil
}

// DeleteMultiUnscopedByPermissionID 根据PermissionID删除多条数据
func (s *SysAPIRepo) DeleteMultiUnscopedByPermissionID(ctx context.Context, permissionID string) error {
	dao := ai_boilerplate_dao.Use(s.db).SysAPI
	_, err := dao.WithContext(ctx).Unscoped().Where(dao.PermissionID.Eq(permissionID)).Delete()
	if err != nil {
		return err
	}
	return nil
}

// DeleteMultiCacheByPermissionID 根据permissionID删除多条数据，并删除缓存
func (s *SysAPIRepo) DeleteMultiCacheByPermissionID(ctx context.Context, permissionID string) error {
	dao := ai_boilerplate_dao.Use(s.db).SysAPI
	result, err := dao.WithContext(ctx).Where(dao.PermissionID.Eq(permissionID)).Find()
	if err != nil {
		return err
	}
	if len(result) == 0 {
		return nil
	}
	_, err = dao.WithContext(ctx).Where(dao.PermissionID.Eq(permissionID)).Delete()
	if err != nil {
		return err
	}
	err = s.DeleteIndexCache(ctx, result...)
	if err != nil {
		return err
	}
	return nil
}

// DeleteMultiUnscopedCacheByPermissionID 根据permissionID删除多条数据，并删除缓存
func (s *SysAPIRepo) DeleteMultiUnscopedCacheByPermissionID(ctx context.Context, permissionID string) error {
	dao := ai_boilerplate_dao.Use(s.db).SysAPI
	result, err := dao.WithContext(ctx).Unscoped().Where(dao.PermissionID.Eq(permissionID)).Find()
	if err != nil {
		return err
	}
	if len(result) == 0 {
		return nil
	}
	_, err = dao.WithContext(ctx).Unscoped().Where(dao.PermissionID.Eq(permissionID)).Delete()
	if err != nil {
		return err
	}
	err = s.DeleteIndexCache(ctx, result...)
	if err != nil {
		return err
	}
	return nil
}

// DeleteMultiByPermissionIDTx 根据permissionID删除多条数据
func (s *SysAPIRepo) DeleteMultiByPermissionIDTx(ctx context.Context, tx *ai_boilerplate_dao.Query, permissionID string) error {
	dao := tx.SysAPI
	_, err := dao.WithContext(ctx).Where(dao.PermissionID.Eq(permissionID)).Delete()
	if err != nil {
		return err
	}
	return nil
}

// DeleteMultiUnscopedByPermissionIDTx 根据permissionID删除多条数据
func (s *SysAPIRepo) DeleteMultiUnscopedByPermissionIDTx(ctx context.Context, tx *ai_boilerplate_dao.Query, permissionID string) error {
	dao := tx.SysAPI
	_, err := dao.WithContext(ctx).Unscoped().Where(dao.PermissionID.Eq(permissionID)).Delete()
	if err != nil {
		return err
	}
	return nil
}

// DeleteMultiCacheByPermissionIDTx 根据permissionID删除多条数据，并删除缓存
func (s *SysAPIRepo) DeleteMultiCacheByPermissionIDTx(ctx context.Context, tx *ai_boilerplate_dao.Query, permissionID string) error {
	dao := tx.SysAPI
	result, err := dao.WithContext(ctx).Where(dao.PermissionID.Eq(permissionID)).Find()
	if err != nil {
		return err
	}
	if len(result) == 0 {
		return nil
	}
	_, err = dao.WithContext(ctx).Where(dao.PermissionID.Eq(permissionID)).Delete()
	if err != nil {
		return err
	}
	err = s.DeleteIndexCache(ctx, result...)
	if err != nil {
		return err
	}
	return nil
}

// DeleteMultiUnscopedCacheByPermissionIDTx 根据permissionID删除多条数据，并删除缓存
func (s *SysAPIRepo) DeleteMultiUnscopedCacheByPermissionIDTx(ctx context.Context, tx *ai_boilerplate_dao.Query, permissionID string) error {
	dao := tx.SysAPI
	result, err := dao.WithContext(ctx).Unscoped().Where(dao.PermissionID.Eq(permissionID)).Find()
	if err != nil {
		return err
	}
	if len(result) == 0 {
		return nil
	}
	_, err = dao.WithContext(ctx).Unscoped().Where(dao.PermissionID.Eq(permissionID)).Delete()
	if err != nil {
		return err
	}
	err = s.DeleteIndexCache(ctx, result...)
	if err != nil {
		return err
	}
	return nil
}

// DeleteMultiByPermissionIDS 根据permissionIDS删除多条数据
func (s *SysAPIRepo) DeleteMultiByPermissionIDS(ctx context.Context, permissionIDS []string) error {
	dao := ai_boilerplate_dao.Use(s.db).SysAPI
	_, err := dao.WithContext(ctx).Where(dao.PermissionID.In(permissionIDS...)).Delete()
	if err != nil {
		return err
	}
	return nil
}

// DeleteMultiUnscopedByPermissionIDS 根据permissionIDS删除多条数据
func (s *SysAPIRepo) DeleteMultiUnscopedByPermissionIDS(ctx context.Context, permissionIDS []string) error {
	dao := ai_boilerplate_dao.Use(s.db).SysAPI
	_, err := dao.WithContext(ctx).Unscoped().Where(dao.PermissionID.In(permissionIDS...)).Delete()
	if err != nil {
		return err
	}
	return nil
}

// DeleteMultiCacheByPermissionIDS 根据permissionIDS删除多条数据，并删除缓存
func (s *SysAPIRepo) DeleteMultiCacheByPermissionIDS(ctx context.Context, permissionIDS []string) error {
	dao := ai_boilerplate_dao.Use(s.db).SysAPI
	result, err := dao.WithContext(ctx).Where(dao.PermissionID.In(permissionIDS...)).Find()
	if err != nil {
		return err
	}
	if len(result) == 0 {
		return nil
	}
	_, err = dao.WithContext(ctx).Where(dao.PermissionID.In(permissionIDS...)).Delete()
	if err != nil {
		return err
	}
	err = s.DeleteIndexCache(ctx, result...)
	if err != nil {
		return err
	}
	return nil
}

// DeleteMultiUnscopedCacheByPermissionIDS 根据permissionIDS删除多条数据，并删除缓存
func (s *SysAPIRepo) DeleteMultiUnscopedCacheByPermissionIDS(ctx context.Context, permissionIDS []string) error {
	dao := ai_boilerplate_dao.Use(s.db).SysAPI
	result, err := dao.WithContext(ctx).Unscoped().Where(dao.PermissionID.In(permissionIDS...)).Find()
	if err != nil {
		return err
	}
	if len(result) == 0 {
		return nil
	}
	_, err = dao.WithContext(ctx).Unscoped().Where(dao.PermissionID.In(permissionIDS...)).Delete()
	if err != nil {
		return err
	}
	err = s.DeleteIndexCache(ctx, result...)
	if err != nil {
		return err
	}
	return nil
}

// DeleteMultiByPermissionIDSTx 根据permissionIDS删除多条数据
func (s *SysAPIRepo) DeleteMultiByPermissionIDSTx(ctx context.Context, tx *ai_boilerplate_dao.Query, permissionIDS []string) error {
	dao := tx.SysAPI
	_, err := dao.WithContext(ctx).Where(dao.PermissionID.In(permissionIDS...)).Delete()
	if err != nil {
		return err
	}
	return nil
}

// DeleteMultiUnscopedByPermissionIDSTx 根据permissionIDS删除多条数据
func (s *SysAPIRepo) DeleteMultiUnscopedByPermissionIDSTx(ctx context.Context, tx *ai_boilerplate_dao.Query, permissionIDS []string) error {
	dao := tx.SysAPI
	_, err := dao.WithContext(ctx).Unscoped().Where(dao.PermissionID.In(permissionIDS...)).Delete()
	if err != nil {
		return err
	}
	return nil
}

// DeleteMultiCacheByPermissionIDSTx 根据permissionIDS删除多条数据，并删除缓存
func (s *SysAPIRepo) DeleteMultiCacheByPermissionIDSTx(ctx context.Context, tx *ai_boilerplate_dao.Query, permissionIDS []string) error {
	dao := tx.SysAPI
	result, err := dao.WithContext(ctx).Where(dao.PermissionID.In(permissionIDS...)).Find()
	if err != nil {
		return err
	}
	if len(result) == 0 {
		return nil
	}
	_, err = dao.WithContext(ctx).Where(dao.PermissionID.In(permissionIDS...)).Delete()
	if err != nil {
		return err
	}
	err = s.DeleteIndexCache(ctx, result...)
	if err != nil {
		return err
	}
	return nil
}

// DeleteMultiUnscopedCacheByPermissionIDSTx 根据permissionIDS删除多条数据，并删除缓存
func (s *SysAPIRepo) DeleteMultiUnscopedCacheByPermissionIDSTx(ctx context.Context, tx *ai_boilerplate_dao.Query, permissionIDS []string) error {
	dao := tx.SysAPI
	result, err := dao.WithContext(ctx).Unscoped().Where(dao.PermissionID.In(permissionIDS...)).Find()
	if err != nil {
		return err
	}
	if len(result) == 0 {
		return nil
	}
	_, err = dao.WithContext(ctx).Unscoped().Where(dao.PermissionID.In(permissionIDS...)).Delete()
	if err != nil {
		return err
	}
	err = s.DeleteIndexCache(ctx, result...)
	if err != nil {
		return err
	}
	return nil
}

// DeleteUniqueIndexCache 删除索引存在的缓存
func (s *SysAPIRepo) DeleteIndexCache(ctx context.Context, data ...*ai_boilerplate_model.SysAPI) error {
	KeyMap := make(map[string]struct{})
	keys := make([]string, 0)
	keys = append(keys, s.cache.Key(CacheSysAPIByConditionPrefix))
	keys = append(keys, s.cache.Key(CacheSysAPIUnscopedByConditionPrefix))
	for _, item := range data {
		if item != nil {
			KeyMap[s.cache.Key(CacheSysAPIByIDPrefix, item.ID)] = struct{}{}
			KeyMap[s.cache.Key(CacheSysAPIUnscopedByIDPrefix, item.ID)] = struct{}{}
			KeyMap[s.cache.Key(CacheSysAPIByPermissionIDPrefix, item.PermissionID)] = struct{}{}
			KeyMap[s.cache.Key(CacheSysAPIUnscopedByPermissionIDPrefix, item.PermissionID)] = struct{}{}
		}
	}
	for item := range KeyMap {
		keys = append(keys, item)
	}
	err := s.cache.DelBatch(ctx, keys)
	if err != nil {
		return err
	}
	return nil
}
