// Code generated by gen/repo. DO NOT EDIT.
// Code generated by gen/repo. DO NOT EDIT.
// Code generated by gen/repo. DO NOT EDIT.

package ai_boilerplate_repo

import (
	"context"
	"errors"
	"reflect"
	"strings"

	"github.com/fzf-labs/ai-boilerplate-backend/internal/data/gorm/ai_boilerplate_dao"
	"github.com/fzf-labs/ai-boilerplate-backend/internal/data/gorm/ai_boilerplate_model"
	"github.com/fzf-labs/godb/orm/condition"
	"github.com/fzf-labs/godb/orm/dbcache"
	"github.com/fzf-labs/godb/orm/encoding"
	"github.com/fzf-labs/godb/orm/gen/config"
	"github.com/jinzhu/copier"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

var _ ISysRoleRepo = (*SysRoleRepo)(nil)

var (
	CacheSysRoleByConditionPrefix         = "DBCache:ai_boilerplate:SysRoleByCondition"
	CacheSysRoleUnscopedByConditionPrefix = "DBCache:ai_boilerplate:SysRoleUnscopedByCondition"
	CacheSysRoleByIDPrefix                = "DBCache:ai_boilerplate:SysRoleByID"
	CacheSysRoleUnscopedByIDPrefix        = "DBCache:ai_boilerplate:SysRoleUnscopedByID"
	CacheSysRoleByTenantIDPrefix          = "DBCache:ai_boilerplate:SysRoleByTenantID"
	CacheSysRoleUnscopedByTenantIDPrefix  = "DBCache:ai_boilerplate:SysRoleUnscopedByTenantID"
)

type (
	ISysRoleRepo interface {
		// NewData 实例化
		NewData() *ai_boilerplate_model.SysRole
		// DeepCopy 深拷贝
		DeepCopy(data *ai_boilerplate_model.SysRole) *ai_boilerplate_model.SysRole
		// CreateOne 创建一条数据
		CreateOne(ctx context.Context, data *ai_boilerplate_model.SysRole) error
		// CreateOneCache 创建一条数据, 并删除缓存
		CreateOneCache(ctx context.Context, data *ai_boilerplate_model.SysRole) error
		// CreateOneByTx 创建一条数据(事务)
		CreateOneByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, data *ai_boilerplate_model.SysRole) error
		// CreateOneCacheByTx 创建一条数据(事务), 并删除缓存
		CreateOneCacheByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, data *ai_boilerplate_model.SysRole) error
		// CreateBatch 批量创建数据
		CreateBatch(ctx context.Context, data []*ai_boilerplate_model.SysRole, batchSize int) error
		// CreateBatchCache 批量创建数据, 并删除缓存
		CreateBatchCache(ctx context.Context, data []*ai_boilerplate_model.SysRole, batchSize int) error
		// CreateBatchByTx 批量创建数据(事务)
		CreateBatchByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, data []*ai_boilerplate_model.SysRole, batchSize int) error
		// CreateBatchCacheByTx 批量创建数据(事务), 并删除缓存
		CreateBatchCacheByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, data []*ai_boilerplate_model.SysRole, batchSize int) error
		// UpsertOne Upsert一条数据
		UpsertOne(ctx context.Context, data *ai_boilerplate_model.SysRole) error
		// UpsertOneCache Upsert一条数据, 并删除缓存
		UpsertOneCache(ctx context.Context, data *ai_boilerplate_model.SysRole) error
		// UpsertOneByTx Upsert一条数据(事务)
		UpsertOneByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, data *ai_boilerplate_model.SysRole) error
		// UpsertOneCacheByTx Upsert一条数据(事务), 并删除缓存
		UpsertOneCacheByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, data *ai_boilerplate_model.SysRole) error
		// UpsertOneByFields 根据fields字段Upsert一条数据
		UpsertOneByFields(ctx context.Context, data *ai_boilerplate_model.SysRole, fields []string) error
		// UpsertOneCacheByFields 根据fields字段Upsert一条数据, 并删除缓存
		UpsertOneCacheByFields(ctx context.Context, data *ai_boilerplate_model.SysRole, fields []string) error
		// UpsertOneByFieldsTx 根据fields字段Upsert一条数据(事务)
		UpsertOneByFieldsTx(ctx context.Context, tx *ai_boilerplate_dao.Query, data *ai_boilerplate_model.SysRole, fields []string) error
		// UpsertOneCacheByFieldsTx 根据fields字段Upsert一条数据(事务), 并删除缓存
		UpsertOneCacheByFieldsTx(ctx context.Context, tx *ai_boilerplate_dao.Query, data *ai_boilerplate_model.SysRole, fields []string) error
		// UpdateOne 更新一条数据
		UpdateOne(ctx context.Context, newData *ai_boilerplate_model.SysRole) error
		// UpdateOneUnscoped 更新一条数据（包括软删除）
		UpdateOneUnscoped(ctx context.Context, newData *ai_boilerplate_model.SysRole) error
		// UpdateOneCache 更新一条数据，并删除缓存
		UpdateOneCache(ctx context.Context, newData *ai_boilerplate_model.SysRole, oldData *ai_boilerplate_model.SysRole) error
		// UpdateOneUnscopedCache 更新一条数据，并删除缓存（包括软删除）
		UpdateOneUnscopedCache(ctx context.Context, newData *ai_boilerplate_model.SysRole, oldData *ai_boilerplate_model.SysRole) error
		// UpdateOneByTx 更新一条数据(事务)
		UpdateOneByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, newData *ai_boilerplate_model.SysRole) error
		// UpdateOneUnscopedByTx 更新一条数据(事务)（包括软删除）
		UpdateOneUnscopedByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, newData *ai_boilerplate_model.SysRole) error
		// UpdateOneCacheByTx 更新一条数据(事务)，并删除缓存
		UpdateOneCacheByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, newData *ai_boilerplate_model.SysRole, oldData *ai_boilerplate_model.SysRole) error
		// UpdateOneUnscopedCacheByTx 更新一条数据(事务)，并删除缓存（包括软删除）
		UpdateOneUnscopedCacheByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, newData *ai_boilerplate_model.SysRole, oldData *ai_boilerplate_model.SysRole) error
		// UpdateOneWithZero 更新一条数据,包含零值，并删除缓存
		UpdateOneWithZero(ctx context.Context, newData *ai_boilerplate_model.SysRole) error
		// UpdateOneUnscopedWithZero 更新一条数据,包含零值（包括软删除）
		UpdateOneUnscopedWithZero(ctx context.Context, newData *ai_boilerplate_model.SysRole) error
		// UpdateOneCacheWithZero 更新一条数据,包含零值，并删除缓存
		UpdateOneCacheWithZero(ctx context.Context, newData *ai_boilerplate_model.SysRole, oldData *ai_boilerplate_model.SysRole) error
		// UpdateOneUnscopedCacheWithZero 更新一条数据,包含零值，并删除缓存（包括软删除）
		UpdateOneUnscopedCacheWithZero(ctx context.Context, newData *ai_boilerplate_model.SysRole, oldData *ai_boilerplate_model.SysRole) error
		// UpdateOneWithZeroByTx 更新一条数据(事务),包含零值，并删除缓存
		UpdateOneWithZeroByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, newData *ai_boilerplate_model.SysRole) error
		// UpdateOneUnscopedWithZeroByTx 更新一条数据(事务),包含零值（包括软删除）
		UpdateOneUnscopedWithZeroByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, newData *ai_boilerplate_model.SysRole) error
		// UpdateOneCacheWithZeroByTx 更新一条数据(事务),包含零值，并删除缓存
		UpdateOneCacheWithZeroByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, newData *ai_boilerplate_model.SysRole, oldData *ai_boilerplate_model.SysRole) error
		// UpdateOneUnscopedCacheWithZeroByTx 更新一条数据(事务),包含零值，并删除缓存（包括软删除）
		UpdateOneUnscopedCacheWithZeroByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, newData *ai_boilerplate_model.SysRole, oldData *ai_boilerplate_model.SysRole) error
		// UpdateBatchByID 根据字段ID批量更新,零值会被更新
		UpdateBatchByID(ctx context.Context, ID string, data map[string]interface{}) error
		// UpdateBatchUnscopedByID 根据字段ID批量更新,零值会被更新（包括软删除）
		UpdateBatchUnscopedByID(ctx context.Context, ID string, data map[string]interface{}) error
		// UpdateBatchByIDTx 根据主键ID批量更新(事务),零值会被更新
		UpdateBatchByIDTx(ctx context.Context, tx *ai_boilerplate_dao.Query, ID string, data map[string]interface{}) error
		// UpdateBatchUnscopedByIDTx 根据主键ID批量更新(事务),零值会被更新（包括软删除）
		UpdateBatchUnscopedByIDTx(ctx context.Context, tx *ai_boilerplate_dao.Query, ID string, data map[string]interface{}) error
		// UpdateBatchByIDS 根据字段IDS批量更新,零值会被更新
		UpdateBatchByIDS(ctx context.Context, IDS []string, data map[string]interface{}) error
		// UpdateBatchUnscopedByIDS 根据字段IDS批量更新,零值会被更新（包括软删除）
		UpdateBatchUnscopedByIDS(ctx context.Context, IDS []string, data map[string]interface{}) error
		// UpdateBatchByIDSTx 根据字段IDS批量更新(事务),零值会被更新
		UpdateBatchByIDSTx(ctx context.Context, tx *ai_boilerplate_dao.Query, IDS []string, data map[string]interface{}) error
		// UpdateBatchUnscopedByIDSTx 根据字段IDS批量更新(事务),零值会被更新（包括软删除）
		UpdateBatchUnscopedByIDSTx(ctx context.Context, tx *ai_boilerplate_dao.Query, IDS []string, data map[string]interface{}) error
		// UpdateBatchByTenantID 根据字段TenantID批量更新,零值会被更新
		UpdateBatchByTenantID(ctx context.Context, tenantID string, data map[string]interface{}) error
		// UpdateBatchUnscopedByTenantID 根据字段TenantID批量更新,零值会被更新（包括软删除）
		UpdateBatchUnscopedByTenantID(ctx context.Context, tenantID string, data map[string]interface{}) error
		// UpdateBatchByTenantIDTx 根据主键TenantID批量更新(事务),零值会被更新
		UpdateBatchByTenantIDTx(ctx context.Context, tx *ai_boilerplate_dao.Query, tenantID string, data map[string]interface{}) error
		// UpdateBatchUnscopedByTenantIDTx 根据主键TenantID批量更新(事务),零值会被更新（包括软删除）
		UpdateBatchUnscopedByTenantIDTx(ctx context.Context, tx *ai_boilerplate_dao.Query, tenantID string, data map[string]interface{}) error
		// UpdateBatchByTenantIDS 根据字段TenantIDS批量更新,零值会被更新
		UpdateBatchByTenantIDS(ctx context.Context, tenantIDS []string, data map[string]interface{}) error
		// UpdateBatchUnscopedByTenantIDS 根据字段TenantIDS批量更新,零值会被更新（包括软删除）
		UpdateBatchUnscopedByTenantIDS(ctx context.Context, tenantIDS []string, data map[string]interface{}) error
		// UpdateBatchByTenantIDSTx 根据字段TenantIDS批量更新(事务),零值会被更新
		UpdateBatchByTenantIDSTx(ctx context.Context, tx *ai_boilerplate_dao.Query, tenantIDS []string, data map[string]interface{}) error
		// UpdateBatchUnscopedByTenantIDSTx 根据字段TenantIDS批量更新(事务),零值会被更新（包括软删除）
		UpdateBatchUnscopedByTenantIDSTx(ctx context.Context, tx *ai_boilerplate_dao.Query, tenantIDS []string, data map[string]interface{}) error
		// FindOneByID 根据ID查询一条数据
		FindOneByID(ctx context.Context, ID string) (*ai_boilerplate_model.SysRole, error)
		// FindOneUnscopedByID 根据ID查询一条数据（包括软删除）
		FindOneUnscopedByID(ctx context.Context, ID string) (*ai_boilerplate_model.SysRole, error)
		// FindOneCacheByID 根据ID查询一条数据，并设置缓存
		FindOneCacheByID(ctx context.Context, ID string) (*ai_boilerplate_model.SysRole, error)
		// FindOneUnscopedCacheByID 根据ID查询一条数据（包括软删除），并设置缓存
		FindOneUnscopedCacheByID(ctx context.Context, ID string) (*ai_boilerplate_model.SysRole, error)
		// FindMultiByIDS 根据IDS查询多条数据
		FindMultiByIDS(ctx context.Context, IDS []string) ([]*ai_boilerplate_model.SysRole, error)
		// FindMultiUnscopedByIDS 根据IDS查询多条数据（包括软删除）
		FindMultiUnscopedByIDS(ctx context.Context, IDS []string) ([]*ai_boilerplate_model.SysRole, error)
		// FindMultiCacheByIDS 根据IDS查询多条数据，并设置缓存
		FindMultiCacheByIDS(ctx context.Context, IDS []string) ([]*ai_boilerplate_model.SysRole, error)
		// FindMultiUnscopedCacheByIDS 根据IDS查询多条数据（包括软删除），并设置缓存
		FindMultiUnscopedCacheByIDS(ctx context.Context, IDS []string) ([]*ai_boilerplate_model.SysRole, error)
		// FindMultiByTenantID 根据tenantID查询多条数据
		FindMultiByTenantID(ctx context.Context, tenantID string) ([]*ai_boilerplate_model.SysRole, error)
		// FindMultiUnscopedByTenantID 根据tenantID查询多条数据（包括软删除）
		FindMultiUnscopedByTenantID(ctx context.Context, tenantID string) ([]*ai_boilerplate_model.SysRole, error)
		// FindMultiCacheByTenantID 根据tenantID查询多条数据并设置缓存
		FindMultiCacheByTenantID(ctx context.Context, tenantID string) ([]*ai_boilerplate_model.SysRole, error)
		// FindMultiUnscopedCacheByTenantID 根据tenantID查询多条数据（包括软删除）并设置缓存
		FindMultiUnscopedCacheByTenantID(ctx context.Context, tenantID string) ([]*ai_boilerplate_model.SysRole, error)
		// FindMultiByTenantIDS 根据tenantIDS查询多条数据
		FindMultiByTenantIDS(ctx context.Context, tenantIDS []string) ([]*ai_boilerplate_model.SysRole, error)
		// FindMultiUnscopedByTenantIDS 根据tenantIDS查询多条数据（包括软删除）
		FindMultiUnscopedByTenantIDS(ctx context.Context, tenantIDS []string) ([]*ai_boilerplate_model.SysRole, error)
		// FindMultiCacheByTenantIDS 根据tenantIDS查询多条数据，并设置缓存
		FindMultiCacheByTenantIDS(ctx context.Context, tenantIDS []string) ([]*ai_boilerplate_model.SysRole, error)
		// FindMultiUnscopedCacheByTenantIDS 根据tenantIDS查询多条数据（包括软删除），并设置缓存
		FindMultiUnscopedCacheByTenantIDS(ctx context.Context, tenantIDS []string) ([]*ai_boilerplate_model.SysRole, error)
		// FindMultiByCondition 自定义查询数据(通用)
		FindMultiByCondition(ctx context.Context, conditionReq *condition.Req) ([]*ai_boilerplate_model.SysRole, *condition.Reply, error)
		// FindMultiUnscopedByCondition 自定义查询数据(通用)（包括软删除）
		FindMultiUnscopedByCondition(ctx context.Context, conditionReq *condition.Req) ([]*ai_boilerplate_model.SysRole, *condition.Reply, error)
		// FindMultiCacheByCondition 自定义查询数据(通用),并设置缓存
		FindMultiCacheByCondition(ctx context.Context, conditionReq *condition.Req) ([]*ai_boilerplate_model.SysRole, *condition.Reply, error)
		// FindMultiUnscopedCacheByCondition 自定义查询数据(通用)（包括软删除）,并设置缓存
		FindMultiUnscopedCacheByCondition(ctx context.Context, conditionReq *condition.Req) ([]*ai_boilerplate_model.SysRole, *condition.Reply, error)
		// DeleteOneByID 根据ID删除一条数据
		DeleteOneByID(ctx context.Context, ID string) error
		// DeleteOneUnscopedByID 根据ID删除一条数据
		DeleteOneUnscopedByID(ctx context.Context, ID string) error
		// DeleteOneCacheByID 根据ID删除一条数据，并删除缓存
		DeleteOneCacheByID(ctx context.Context, ID string) error
		// DeleteOneUnscopedCacheByID 根据ID删除一条数据，并删除缓存
		DeleteOneUnscopedCacheByID(ctx context.Context, ID string) error
		// DeleteOneByIDTx 根据ID删除一条数据(事务)
		DeleteOneByIDTx(ctx context.Context, tx *ai_boilerplate_dao.Query, ID string) error
		// DeleteOneUnscopedByIDTx 根据ID删除一条数据(事务)
		DeleteOneUnscopedByIDTx(ctx context.Context, tx *ai_boilerplate_dao.Query, ID string) error
		// DeleteOneCacheByIDTx 根据ID删除一条数据，并删除缓存(事务)
		DeleteOneCacheByIDTx(ctx context.Context, tx *ai_boilerplate_dao.Query, ID string) error
		// DeleteOneUnscopedCacheByIDTx 根据ID删除一条数据，并删除缓存(事务)
		DeleteOneUnscopedCacheByIDTx(ctx context.Context, tx *ai_boilerplate_dao.Query, ID string) error
		// DeleteMultiByIDS 根据IDS删除多条数据
		DeleteMultiByIDS(ctx context.Context, IDS []string) error
		// DeleteMultiUnscopedByIDS 根据IDS删除多条数据
		DeleteMultiUnscopedByIDS(ctx context.Context, IDS []string) error
		// DeleteMultiCacheByIDS 根据IDS删除多条数据，并删除缓存
		DeleteMultiCacheByIDS(ctx context.Context, IDS []string) error
		// DeleteMultiUnscopedCacheByIDS 根据IDS删除多条数据，并删除缓存
		DeleteMultiUnscopedCacheByIDS(ctx context.Context, IDS []string) error
		// DeleteMultiByIDSTx 根据IDS删除多条数据(事务)
		DeleteMultiByIDSTx(ctx context.Context, tx *ai_boilerplate_dao.Query, IDS []string) error
		// DeleteMultiUnscopedByIDSTx 根据IDS删除多条数据(事务)
		DeleteMultiUnscopedByIDSTx(ctx context.Context, tx *ai_boilerplate_dao.Query, IDS []string) error
		// DeleteMultiCacheByIDSTx 根据IDS删除多条数据，并删除缓存(事务)
		DeleteMultiCacheByIDSTx(ctx context.Context, tx *ai_boilerplate_dao.Query, IDS []string) error
		// DeleteMultiUnscopedCacheByIDSTx 根据IDS删除多条数据，并删除缓存(事务)
		DeleteMultiUnscopedCacheByIDSTx(ctx context.Context, tx *ai_boilerplate_dao.Query, IDS []string) error
		// DeleteMultiByTenantID 根据TenantID删除多条数据
		DeleteMultiByTenantID(ctx context.Context, tenantID string) error
		// DeleteMultiUnscopedByTenantID 根据TenantID删除多条数据
		DeleteMultiUnscopedByTenantID(ctx context.Context, tenantID string) error
		// DeleteMultiCacheByTenantID 根据tenantID删除多条数据，并删除缓存
		DeleteMultiCacheByTenantID(ctx context.Context, tenantID string) error
		// DeleteMultiUnscopedCacheByTenantID 根据tenantID删除多条数据，并删除缓存
		DeleteMultiUnscopedCacheByTenantID(ctx context.Context, tenantID string) error
		// DeleteMultiByTenantIDTx 根据tenantID删除多条数据
		DeleteMultiByTenantIDTx(ctx context.Context, tx *ai_boilerplate_dao.Query, tenantID string) error
		// DeleteMultiUnscopedByTenantIDTx 根据tenantID删除多条数据
		DeleteMultiUnscopedByTenantIDTx(ctx context.Context, tx *ai_boilerplate_dao.Query, tenantID string) error
		// DeleteMultiCacheByTenantIDTx 根据tenantID删除多条数据，并删除缓存
		DeleteMultiCacheByTenantIDTx(ctx context.Context, tx *ai_boilerplate_dao.Query, tenantID string) error
		// DeleteMultiUnscopedCacheByTenantIDTx 根据tenantID删除多条数据，并删除缓存
		DeleteMultiUnscopedCacheByTenantIDTx(ctx context.Context, tx *ai_boilerplate_dao.Query, tenantID string) error
		// DeleteMultiByTenantIDS 根据TenantIDS删除多条数据
		DeleteMultiByTenantIDS(ctx context.Context, tenantIDS []string) error
		// DeleteMultiUnscopedByTenantIDS 根据TenantIDS删除多条数据
		DeleteMultiUnscopedByTenantIDS(ctx context.Context, tenantIDS []string) error
		// DeleteMultiCacheByTenantIDS 根据TenantIDS删除多条数据，并删除缓存
		DeleteMultiCacheByTenantIDS(ctx context.Context, tenantIDS []string) error
		// DeleteMultiUnscopedCacheByTenantIDS 根据TenantIDS删除多条数据，并删除缓存
		DeleteMultiUnscopedCacheByTenantIDS(ctx context.Context, tenantIDS []string) error
		// DeleteMultiByTenantIDSTx 根据TenantIDS删除多条数据(事务)
		DeleteMultiByTenantIDSTx(ctx context.Context, tx *ai_boilerplate_dao.Query, tenantIDS []string) error
		// DeleteMultiUnscopedByTenantIDSTx 根据TenantIDS删除多条数据(事务)
		DeleteMultiUnscopedByTenantIDSTx(ctx context.Context, tx *ai_boilerplate_dao.Query, tenantIDS []string) error
		// DeleteMultiCacheByTenantIDSTx 根据TenantIDS删除多条数据，并删除缓存(事务)
		DeleteMultiCacheByTenantIDSTx(ctx context.Context, tx *ai_boilerplate_dao.Query, tenantIDS []string) error
		// DeleteMultiUnscopedCacheByTenantIDSTx 根据TenantIDS删除多条数据，并删除缓存(事务)
		DeleteMultiUnscopedCacheByTenantIDSTx(ctx context.Context, tx *ai_boilerplate_dao.Query, tenantIDS []string) error
		// DeleteIndexCache 删除索引存在的缓存
		DeleteIndexCache(ctx context.Context, data ...*ai_boilerplate_model.SysRole) error
	}
	SysRoleRepo struct {
		db       *gorm.DB
		cache    dbcache.IDBCache
		encoding encoding.API
	}
)

func NewSysRoleRepo(cfg *config.Repo) *SysRoleRepo {
	return &SysRoleRepo{
		db:       cfg.DB,
		cache:    cfg.Cache,
		encoding: cfg.Encoding,
	}
}

// NewData 实例化
func (s *SysRoleRepo) NewData() *ai_boilerplate_model.SysRole {
	return &ai_boilerplate_model.SysRole{}
}

// DeepCopy 深拷贝
func (s *SysRoleRepo) DeepCopy(data *ai_boilerplate_model.SysRole) *ai_boilerplate_model.SysRole {
	newData := new(ai_boilerplate_model.SysRole)
	_ = copier.CopyWithOption(newData, data, copier.Option{DeepCopy: true})
	return newData
}

// CreateOne 创建一条数据
func (s *SysRoleRepo) CreateOne(ctx context.Context, data *ai_boilerplate_model.SysRole) error {
	dao := ai_boilerplate_dao.Use(s.db).SysRole
	err := dao.WithContext(ctx).Create(data)
	if err != nil {
		return err
	}
	return nil
}

// CreateOneCache 创建一条数据, 并删除缓存
func (s *SysRoleRepo) CreateOneCache(ctx context.Context, data *ai_boilerplate_model.SysRole) error {
	dao := ai_boilerplate_dao.Use(s.db).SysRole
	err := dao.WithContext(ctx).Create(data)
	if err != nil {
		return err
	}
	err = s.DeleteIndexCache(ctx, data)
	if err != nil {
		return err
	}
	return nil
}

// CreateOneByTx 创建一条数据(事务)
func (s *SysRoleRepo) CreateOneByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, data *ai_boilerplate_model.SysRole) error {
	dao := tx.SysRole
	err := dao.WithContext(ctx).Create(data)
	if err != nil {
		return err
	}
	return nil
}

// CreateOneCacheByTx 创建一条数据(事务), 并删除缓存
func (s *SysRoleRepo) CreateOneCacheByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, data *ai_boilerplate_model.SysRole) error {
	dao := tx.SysRole
	err := dao.WithContext(ctx).Create(data)
	if err != nil {
		return err
	}
	err = s.DeleteIndexCache(ctx, data)
	if err != nil {
		return err
	}
	return nil
}

// CreateBatch 批量创建数据
func (s *SysRoleRepo) CreateBatch(ctx context.Context, data []*ai_boilerplate_model.SysRole, batchSize int) error {
	dao := ai_boilerplate_dao.Use(s.db).SysRole
	err := dao.WithContext(ctx).CreateInBatches(data, batchSize)
	if err != nil {
		return err
	}
	return nil
}

// CreateBatchCache 批量创建数据, 并删除缓存
func (s *SysRoleRepo) CreateBatchCache(ctx context.Context, data []*ai_boilerplate_model.SysRole, batchSize int) error {
	dao := ai_boilerplate_dao.Use(s.db).SysRole
	err := dao.WithContext(ctx).CreateInBatches(data, batchSize)
	if err != nil {
		return err
	}
	err = s.DeleteIndexCache(ctx, data...)
	if err != nil {
		return err
	}
	return nil
}

// CreateBatchByTx 批量创建数据(事务)
func (s *SysRoleRepo) CreateBatchByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, data []*ai_boilerplate_model.SysRole, batchSize int) error {
	dao := tx.SysRole
	err := dao.WithContext(ctx).CreateInBatches(data, batchSize)
	if err != nil {
		return err
	}
	return nil
}

// CreateBatchCacheByTx 批量创建数据(事务), 并删除缓存
func (s *SysRoleRepo) CreateBatchCacheByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, data []*ai_boilerplate_model.SysRole, batchSize int) error {
	dao := tx.SysRole
	err := dao.WithContext(ctx).CreateInBatches(data, batchSize)
	if err != nil {
		return err
	}
	err = s.DeleteIndexCache(ctx, data...)
	if err != nil {
		return err
	}
	return nil
}

// UpsertOne Upsert一条数据
// Update all columns, except primary keys, to new value on conflict
func (s *SysRoleRepo) UpsertOne(ctx context.Context, data *ai_boilerplate_model.SysRole) error {
	dao := ai_boilerplate_dao.Use(s.db).SysRole
	err := dao.WithContext(ctx).Save(data)
	if err != nil {
		return err
	}
	return nil
}

// UpsertOneCache Upsert一条数据, 并删除缓存
// Update all columns, except primary keys, to new value on conflict
func (s *SysRoleRepo) UpsertOneCache(ctx context.Context, data *ai_boilerplate_model.SysRole) error {
	dao := ai_boilerplate_dao.Use(s.db).SysRole
	oldData, err := dao.WithContext(ctx).Where(dao.ID.Eq(data.ID)).Unscoped().First()
	if err != nil && !errors.Is(err, gorm.ErrRecordNotFound) {
		return err
	}
	err = dao.WithContext(ctx).Save(data)
	if err != nil {
		return err
	}
	err = s.DeleteIndexCache(ctx, oldData, data)
	if err != nil {
		return err
	}
	return nil
}

// UpsertOneByTx Upsert一条数据(事务)
// Update all columns, except primary keys, to new value on conflict
func (s *SysRoleRepo) UpsertOneByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, data *ai_boilerplate_model.SysRole) error {
	dao := tx.SysRole
	err := dao.WithContext(ctx).Save(data)
	if err != nil {
		return err
	}
	return nil
}

// UpsertOneCacheByTx Upsert一条数据(事务), 并删除缓存
// Update all columns, except primary keys, to new value on conflict
func (s *SysRoleRepo) UpsertOneCacheByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, data *ai_boilerplate_model.SysRole) error {
	dao := tx.SysRole
	oldData, err := dao.WithContext(ctx).Where(dao.ID.Eq(data.ID)).Unscoped().First()
	if err != nil && !errors.Is(err, gorm.ErrRecordNotFound) {
		return err
	}
	err = dao.WithContext(ctx).Save(data)
	if err != nil {
		return err
	}
	err = s.DeleteIndexCache(ctx, oldData, data)
	if err != nil {
		return err
	}
	return nil
}

// UpsertOneByFields 根据fields字段Upsert一条数据
func (s *SysRoleRepo) UpsertOneByFields(ctx context.Context, data *ai_boilerplate_model.SysRole, fields []string) error {
	if len(fields) == 0 {
		return errors.New("UpsertOneByFields fields is empty")
	}
	columns := make([]clause.Column, 0)
	for _, item := range fields {
		columns = append(columns, clause.Column{Name: item})
	}
	dao := ai_boilerplate_dao.Use(s.db).SysRole
	err := dao.WithContext(ctx).Clauses(clause.OnConflict{
		Columns:   columns,
		UpdateAll: true,
	}).Create(data)
	if err != nil {
		return err
	}
	return nil
}

// UpsertOneCacheByFields 根据fields字段Upsert一条数据, 并删除缓存
func (s *SysRoleRepo) UpsertOneCacheByFields(ctx context.Context, data *ai_boilerplate_model.SysRole, fields []string) error {
	if len(fields) == 0 {
		return errors.New("UpsertOneByFields fields is empty")
	}
	fieldNameToValue := make(map[string]interface{})
	typ := reflect.TypeOf(data).Elem()
	val := reflect.ValueOf(data).Elem()
	for i := 0; i < typ.NumField(); i++ {
		field := typ.Field(i)
		gormTag := field.Tag.Get("gorm")
		if gormTag != "" {
			gormTags := strings.Split(gormTag, ";")
			for _, item := range gormTags {
				if strings.Contains(item, "column") {
					columnName := strings.TrimPrefix(item, "column:")
					fieldValue := val.Field(i).Interface()
					fieldNameToValue[columnName] = fieldValue
					break
				}
			}
		}
	}
	whereExpressions := make([]clause.Expression, 0)
	columns := make([]clause.Column, 0)
	for _, item := range fields {
		whereExpressions = append(whereExpressions, clause.And(clause.Eq{Column: item, Value: fieldNameToValue[item]}))
		columns = append(columns, clause.Column{Name: item})
	}
	oldData := &ai_boilerplate_model.SysRole{}
	err := s.db.Model(&ai_boilerplate_model.SysRole{}).Clauses(whereExpressions...).Unscoped().First(oldData).Error
	if err != nil && !errors.Is(err, gorm.ErrRecordNotFound) {
		return err
	}
	dao := ai_boilerplate_dao.Use(s.db).SysRole
	err = dao.WithContext(ctx).Clauses(clause.OnConflict{
		Columns:   columns,
		UpdateAll: true,
	}).Create(data)
	if err != nil {
		return err
	}
	err = s.DeleteIndexCache(ctx, oldData, data)
	if err != nil {
		return err
	}
	return nil
}

// UpsertOneByFieldsTx 根据fields字段Upsert一条数据(事务)
func (s *SysRoleRepo) UpsertOneByFieldsTx(ctx context.Context, tx *ai_boilerplate_dao.Query, data *ai_boilerplate_model.SysRole, fields []string) error {
	if len(fields) == 0 {
		return errors.New("UpsertOneByFieldsTx fields is empty")
	}
	columns := make([]clause.Column, 0)
	for _, item := range fields {
		columns = append(columns, clause.Column{Name: item})
	}
	dao := tx.SysRole
	err := dao.WithContext(ctx).Clauses(clause.OnConflict{
		Columns:   columns,
		UpdateAll: true,
	}).Create(data)
	if err != nil {
		return err
	}
	return nil
}

// UpsertOneCacheByFieldsTx 根据fields字段Upsert一条数据(事务), 并删除缓存
func (s *SysRoleRepo) UpsertOneCacheByFieldsTx(ctx context.Context, tx *ai_boilerplate_dao.Query, data *ai_boilerplate_model.SysRole, fields []string) error {
	if len(fields) == 0 {
		return errors.New("UpsertOneByFieldsTx fields is empty")
	}
	fieldNameToValue := make(map[string]interface{})
	typ := reflect.TypeOf(data).Elem()
	val := reflect.ValueOf(data).Elem()
	for i := 0; i < typ.NumField(); i++ {
		field := typ.Field(i)
		gormTag := field.Tag.Get("gorm")
		if gormTag != "" {
			gormTags := strings.Split(gormTag, ";")
			for _, item := range gormTags {
				if strings.Contains(item, "column") {
					columnName := strings.TrimPrefix(item, "column:")
					fieldValue := val.Field(i).Interface()
					fieldNameToValue[columnName] = fieldValue
					break
				}
			}
		}
	}
	whereExpressions := make([]clause.Expression, 0)
	columns := make([]clause.Column, 0)
	for _, item := range fields {
		whereExpressions = append(whereExpressions, clause.And(clause.Eq{Column: item, Value: fieldNameToValue[item]}))
		columns = append(columns, clause.Column{Name: item})
	}
	oldData := &ai_boilerplate_model.SysRole{}
	err := s.db.Model(&ai_boilerplate_model.SysRole{}).Clauses(whereExpressions...).Unscoped().First(oldData).Error
	if err != nil && !errors.Is(err, gorm.ErrRecordNotFound) {
		return err
	}
	dao := tx.SysRole
	err = dao.WithContext(ctx).Clauses(clause.OnConflict{
		Columns:   columns,
		UpdateAll: true,
	}).Create(data)
	if err != nil {
		return err
	}
	err = s.DeleteIndexCache(ctx, oldData, data)
	if err != nil {
		return err
	}
	return nil
}

// UpdateOne 更新一条数据
// data 中主键字段必须有值，零值不会被更新
func (s *SysRoleRepo) UpdateOne(ctx context.Context, newData *ai_boilerplate_model.SysRole) error {
	dao := ai_boilerplate_dao.Use(s.db).SysRole
	_, err := dao.WithContext(ctx).Updates(newData)
	if err != nil {
		return err
	}
	return nil
}

// UpdateOneUnscoped 更新一条数据（包括软删除）
// data 中主键字段必须有值，零值不会被更新
func (s *SysRoleRepo) UpdateOneUnscoped(ctx context.Context, newData *ai_boilerplate_model.SysRole) error {
	dao := ai_boilerplate_dao.Use(s.db).SysRole
	_, err := dao.WithContext(ctx).Unscoped().Updates(newData)
	if err != nil {
		return err
	}
	return nil
}

// UpdateOneCache 更新一条数据，并删除缓存
// data 中主键字段必须有值，零值不会被更新
// oldData 旧数据，删除缓存时使用
func (s *SysRoleRepo) UpdateOneCache(ctx context.Context, newData *ai_boilerplate_model.SysRole, oldData *ai_boilerplate_model.SysRole) error {
	dao := ai_boilerplate_dao.Use(s.db).SysRole
	_, err := dao.WithContext(ctx).Updates(newData)
	if err != nil {
		return err
	}
	err = s.DeleteIndexCache(ctx, oldData, newData)
	if err != nil {
		return err
	}
	return nil
}

// UpdateOneUnscopedCache 更新一条数据，并删除缓存（包括软删除）
// data 中主键字段必须有值，零值不会被更新
// oldData 旧数据，删除缓存时使用
func (s *SysRoleRepo) UpdateOneUnscopedCache(ctx context.Context, newData *ai_boilerplate_model.SysRole, oldData *ai_boilerplate_model.SysRole) error {
	dao := ai_boilerplate_dao.Use(s.db).SysRole
	_, err := dao.WithContext(ctx).Unscoped().Updates(newData)
	if err != nil {
		return err
	}
	err = s.DeleteIndexCache(ctx, oldData, newData)
	if err != nil {
		return err
	}
	return nil
}

// UpdateOneByTx 更新一条数据(事务)
// data 中主键字段必须有值，零值不会被更新
func (s *SysRoleRepo) UpdateOneByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, newData *ai_boilerplate_model.SysRole) error {
	dao := tx.SysRole
	_, err := dao.WithContext(ctx).Updates(newData)
	if err != nil {
		return err
	}
	return nil
}

// UpdateOneUnscopedByTx 更新一条数据(事务)（包括软删除）
// data 中主键字段必须有值，零值不会被更新
func (s *SysRoleRepo) UpdateOneUnscopedByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, newData *ai_boilerplate_model.SysRole) error {
	dao := tx.SysRole
	_, err := dao.WithContext(ctx).Unscoped().Updates(newData)
	if err != nil {
		return err
	}
	return nil
}

// UpdateOneCacheByTx 更新一条数据(事务)，并删除缓存
// data 中主键字段必须有值，零值不会被更新
// oldData 旧数据，删除缓存时使用
func (s *SysRoleRepo) UpdateOneCacheByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, newData *ai_boilerplate_model.SysRole, oldData *ai_boilerplate_model.SysRole) error {
	dao := tx.SysRole
	_, err := dao.WithContext(ctx).Updates(newData)
	if err != nil {
		return err
	}
	err = s.DeleteIndexCache(ctx, oldData, newData)
	if err != nil {
		return err
	}
	return nil
}

// UpdateOneUnscopedCacheByTx 更新一条数据(事务)，并删除缓存（包括软删除）
// data 中主键字段必须有值，零值不会被更新
// oldData 旧数据，删除缓存时使用
func (s *SysRoleRepo) UpdateOneUnscopedCacheByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, newData *ai_boilerplate_model.SysRole, oldData *ai_boilerplate_model.SysRole) error {
	dao := tx.SysRole
	_, err := dao.WithContext(ctx).Unscoped().Updates(newData)
	if err != nil {
		return err
	}
	err = s.DeleteIndexCache(ctx, oldData, newData)
	if err != nil {
		return err
	}
	return nil
}

// UpdateOneWithZero 更新一条数据,包含零值
// data 中主键字段必须有值,并且会更新所有字段,包括零值
func (s *SysRoleRepo) UpdateOneWithZero(ctx context.Context, newData *ai_boilerplate_model.SysRole) error {
	dao := ai_boilerplate_dao.Use(s.db).SysRole
	_, err := dao.WithContext(ctx).Select(dao.ALL.WithTable("")).Updates(newData)
	if err != nil {
		return err
	}
	return nil
}

// UpdateOneUnscopedWithZero 更新一条数据,包含零值（包括软删除）
// data 中主键字段必须有值,并且会更新所有字段,包括零值
func (s *SysRoleRepo) UpdateOneUnscopedWithZero(ctx context.Context, newData *ai_boilerplate_model.SysRole) error {
	dao := ai_boilerplate_dao.Use(s.db).SysRole
	_, err := dao.WithContext(ctx).Unscoped().Select(dao.ALL.WithTable("")).Updates(newData)
	if err != nil {
		return err
	}
	return nil
}

// UpdateOneCacheWithZero 更新一条数据,包含零值，并删除缓存
// data 中主键字段必须有值,并且会更新所有字段,包括零值
// oldData 旧数据，删除缓存时使用
func (s *SysRoleRepo) UpdateOneCacheWithZero(ctx context.Context, newData *ai_boilerplate_model.SysRole, oldData *ai_boilerplate_model.SysRole) error {
	dao := ai_boilerplate_dao.Use(s.db).SysRole
	_, err := dao.WithContext(ctx).Select(dao.ALL.WithTable("")).Updates(newData)
	if err != nil {
		return err
	}
	err = s.DeleteIndexCache(ctx, oldData, newData)
	if err != nil {
		return err
	}
	return nil
}

// UpdateOneUnscopedCacheWithZero 更新一条数据,包含零值，并删除缓存（包括软删除）
// data 中主键字段必须有值,并且会更新所有字段,包括零值
// oldData 旧数据，删除缓存时使用
func (s *SysRoleRepo) UpdateOneUnscopedCacheWithZero(ctx context.Context, newData *ai_boilerplate_model.SysRole, oldData *ai_boilerplate_model.SysRole) error {
	dao := ai_boilerplate_dao.Use(s.db).SysRole
	_, err := dao.WithContext(ctx).Unscoped().Select(dao.ALL.WithTable("")).Updates(newData)
	if err != nil {
		return err
	}
	err = s.DeleteIndexCache(ctx, oldData, newData)
	if err != nil {
		return err
	}
	return nil
}

// UpdateOneWithZeroByTx 更新一条数据(事务),包含零值，
// data 中主键字段必须有值,并且会更新所有字段,包括零值
func (s *SysRoleRepo) UpdateOneWithZeroByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, newData *ai_boilerplate_model.SysRole) error {
	dao := tx.SysRole
	_, err := dao.WithContext(ctx).Select(dao.ALL.WithTable("")).Updates(newData)
	if err != nil {
		return err
	}
	return nil
}

// UpdateOneUnscopedWithZeroByTx 更新一条数据(事务),包含零值（包括软删除）
// data 中主键字段必须有值,并且会更新所有字段,包括零值
func (s *SysRoleRepo) UpdateOneUnscopedWithZeroByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, newData *ai_boilerplate_model.SysRole) error {
	dao := tx.SysRole
	_, err := dao.WithContext(ctx).Unscoped().Select(dao.ALL.WithTable("")).Updates(newData)
	if err != nil {
		return err
	}
	return nil
}

// UpdateOneCacheWithZeroByTx 更新一条数据(事务),包含零值，并删除缓存
// data 中主键字段必须有值,并且会更新所有字段,包括零值
// oldData 旧数据，删除缓存时使用
func (s *SysRoleRepo) UpdateOneCacheWithZeroByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, newData *ai_boilerplate_model.SysRole, oldData *ai_boilerplate_model.SysRole) error {
	dao := tx.SysRole
	_, err := dao.WithContext(ctx).Select(dao.ALL.WithTable("")).Updates(newData)
	if err != nil {
		return err
	}
	err = s.DeleteIndexCache(ctx, oldData, newData)
	if err != nil {
		return err
	}
	return nil
}

// UpdateOneUnscopedCacheWithZeroByTx 更新一条数据(事务),包含零值，并删除缓存（包括软删除）
// data 中主键字段必须有值,并且会更新所有字段,包括零值
// oldData 旧数据，删除缓存时使用
func (s *SysRoleRepo) UpdateOneUnscopedCacheWithZeroByTx(ctx context.Context, tx *ai_boilerplate_dao.Query, newData *ai_boilerplate_model.SysRole, oldData *ai_boilerplate_model.SysRole) error {
	dao := tx.SysRole
	_, err := dao.WithContext(ctx).Unscoped().Select(dao.ALL.WithTable("")).Updates(newData)
	if err != nil {
		return err
	}
	err = s.DeleteIndexCache(ctx, oldData, newData)
	if err != nil {
		return err
	}
	return nil
}

// UpdateBatchByID 根据字段ID批量更新,零值会被更新
func (s *SysRoleRepo) UpdateBatchByID(ctx context.Context, ID string, data map[string]interface{}) error {
	dao := ai_boilerplate_dao.Use(s.db).SysRole
	_, err := dao.WithContext(ctx).Where(dao.ID.Eq(ID)).Updates(data)
	if err != nil {
		return err
	}
	return nil
}

// UpdateBatchUnscopedByID 根据字段ID批量更新,零值会被更新（包括软删除）
func (s *SysRoleRepo) UpdateBatchUnscopedByID(ctx context.Context, ID string, data map[string]interface{}) error {
	dao := ai_boilerplate_dao.Use(s.db).SysRole
	_, err := dao.WithContext(ctx).Unscoped().Where(dao.ID.Eq(ID)).Updates(data)
	if err != nil {
		return err
	}
	return nil
}

// UpdateBatchByIDTx 根据字段ID批量更新(事务),零值会被更新
func (s *SysRoleRepo) UpdateBatchByIDTx(ctx context.Context, tx *ai_boilerplate_dao.Query, ID string, data map[string]interface{}) error {
	dao := tx.SysRole
	_, err := dao.WithContext(ctx).Where(dao.ID.Eq(ID)).Updates(data)
	if err != nil {
		return err
	}
	return nil
}

// UpdateBatchUnscopedByIDTx 根据字段ID批量更新(事务),零值会被更新（包括软删除）
func (s *SysRoleRepo) UpdateBatchUnscopedByIDTx(ctx context.Context, tx *ai_boilerplate_dao.Query, ID string, data map[string]interface{}) error {
	dao := tx.SysRole
	_, err := dao.WithContext(ctx).Unscoped().Where(dao.ID.Eq(ID)).Updates(data)
	if err != nil {
		return err
	}
	return nil
}

// UpdateBatchByIDS 根据字段IDS批量更新,零值会被更新
func (s *SysRoleRepo) UpdateBatchByIDS(ctx context.Context, IDS []string, data map[string]interface{}) error {
	dao := ai_boilerplate_dao.Use(s.db).SysRole
	_, err := dao.WithContext(ctx).Where(dao.ID.In(IDS...)).Updates(data)
	if err != nil {
		return err
	}
	return nil
}

// UpdateBatchUnscopedByIDS 根据字段IDS批量更新,零值会被更新（包括软删除）
func (s *SysRoleRepo) UpdateBatchUnscopedByIDS(ctx context.Context, IDS []string, data map[string]interface{}) error {
	dao := ai_boilerplate_dao.Use(s.db).SysRole
	_, err := dao.WithContext(ctx).Unscoped().Where(dao.ID.In(IDS...)).Updates(data)
	if err != nil {
		return err
	}
	return nil
}

// UpdateBatchByIDSTx 根据字段IDS批量更新(事务),零值会被更新
func (s *SysRoleRepo) UpdateBatchByIDSTx(ctx context.Context, tx *ai_boilerplate_dao.Query, IDS []string, data map[string]interface{}) error {
	dao := tx.SysRole
	_, err := dao.WithContext(ctx).Where(dao.ID.In(IDS...)).Updates(data)
	if err != nil {
		return err
	}
	return nil
}

// UpdateBatchUnscopedByIDSTx 根据字段IDS批量更新(事务),零值会被更新（包括软删除）
func (s *SysRoleRepo) UpdateBatchUnscopedByIDSTx(ctx context.Context, tx *ai_boilerplate_dao.Query, IDS []string, data map[string]interface{}) error {
	dao := tx.SysRole
	_, err := dao.WithContext(ctx).Unscoped().Where(dao.ID.In(IDS...)).Updates(data)
	if err != nil {
		return err
	}
	return nil
}

// UpdateBatchByTenantID 根据字段TenantID批量更新,零值会被更新
func (s *SysRoleRepo) UpdateBatchByTenantID(ctx context.Context, tenantID string, data map[string]interface{}) error {
	dao := ai_boilerplate_dao.Use(s.db).SysRole
	_, err := dao.WithContext(ctx).Where(dao.TenantID.Eq(tenantID)).Updates(data)
	if err != nil {
		return err
	}
	return nil
}

// UpdateBatchUnscopedByTenantID 根据字段TenantID批量更新,零值会被更新（包括软删除）
func (s *SysRoleRepo) UpdateBatchUnscopedByTenantID(ctx context.Context, tenantID string, data map[string]interface{}) error {
	dao := ai_boilerplate_dao.Use(s.db).SysRole
	_, err := dao.WithContext(ctx).Unscoped().Where(dao.TenantID.Eq(tenantID)).Updates(data)
	if err != nil {
		return err
	}
	return nil
}

// UpdateBatchByTenantIDTx 根据字段TenantID批量更新(事务),零值会被更新
func (s *SysRoleRepo) UpdateBatchByTenantIDTx(ctx context.Context, tx *ai_boilerplate_dao.Query, tenantID string, data map[string]interface{}) error {
	dao := tx.SysRole
	_, err := dao.WithContext(ctx).Where(dao.TenantID.Eq(tenantID)).Updates(data)
	if err != nil {
		return err
	}
	return nil
}

// UpdateBatchUnscopedByTenantIDTx 根据字段TenantID批量更新(事务),零值会被更新（包括软删除）
func (s *SysRoleRepo) UpdateBatchUnscopedByTenantIDTx(ctx context.Context, tx *ai_boilerplate_dao.Query, tenantID string, data map[string]interface{}) error {
	dao := tx.SysRole
	_, err := dao.WithContext(ctx).Unscoped().Where(dao.TenantID.Eq(tenantID)).Updates(data)
	if err != nil {
		return err
	}
	return nil
}

// UpdateBatchByTenantIDS 根据字段TenantIDS批量更新,零值会被更新
func (s *SysRoleRepo) UpdateBatchByTenantIDS(ctx context.Context, tenantIDS []string, data map[string]interface{}) error {
	dao := ai_boilerplate_dao.Use(s.db).SysRole
	_, err := dao.WithContext(ctx).Where(dao.TenantID.In(tenantIDS...)).Updates(data)
	if err != nil {
		return err
	}
	return nil
}

// UpdateBatchUnscopedByTenantIDS 根据字段TenantIDS批量更新,零值会被更新（包括软删除）
func (s *SysRoleRepo) UpdateBatchUnscopedByTenantIDS(ctx context.Context, tenantIDS []string, data map[string]interface{}) error {
	dao := ai_boilerplate_dao.Use(s.db).SysRole
	_, err := dao.WithContext(ctx).Unscoped().Where(dao.TenantID.In(tenantIDS...)).Updates(data)
	if err != nil {
		return err
	}
	return nil
}

// UpdateBatchByTenantIDSTx 根据字段TenantIDS批量更新(事务),零值会被更新
func (s *SysRoleRepo) UpdateBatchByTenantIDSTx(ctx context.Context, tx *ai_boilerplate_dao.Query, tenantIDS []string, data map[string]interface{}) error {
	dao := tx.SysRole
	_, err := dao.WithContext(ctx).Where(dao.TenantID.In(tenantIDS...)).Updates(data)
	if err != nil {
		return err
	}
	return nil
}

// UpdateBatchUnscopedByTenantIDSTx 根据字段TenantIDS批量更新(事务),零值会被更新（包括软删除）
func (s *SysRoleRepo) UpdateBatchUnscopedByTenantIDSTx(ctx context.Context, tx *ai_boilerplate_dao.Query, tenantIDS []string, data map[string]interface{}) error {
	dao := tx.SysRole
	_, err := dao.WithContext(ctx).Unscoped().Where(dao.TenantID.In(tenantIDS...)).Updates(data)
	if err != nil {
		return err
	}
	return nil
}

// FindOneByID 根据ID查询一条数据
func (s *SysRoleRepo) FindOneByID(ctx context.Context, ID string) (*ai_boilerplate_model.SysRole, error) {
	dao := ai_boilerplate_dao.Use(s.db).SysRole
	result, err := dao.WithContext(ctx).Where(dao.ID.Eq(ID)).First()
	if err != nil && !errors.Is(err, gorm.ErrRecordNotFound) {
		return nil, err
	}
	return result, nil
}

// FindOneUnscopedByID 根据ID查询一条数据（包括软删除）
func (s *SysRoleRepo) FindOneUnscopedByID(ctx context.Context, ID string) (*ai_boilerplate_model.SysRole, error) {
	dao := ai_boilerplate_dao.Use(s.db).SysRole
	result, err := dao.WithContext(ctx).Unscoped().Where(dao.ID.Eq(ID)).First()
	if err != nil && !errors.Is(err, gorm.ErrRecordNotFound) {
		return nil, err
	}
	return result, nil
}

// FindOneCacheByID 根据ID查询一条数据，并设置缓存
func (s *SysRoleRepo) FindOneCacheByID(ctx context.Context, ID string) (*ai_boilerplate_model.SysRole, error) {
	resp := new(ai_boilerplate_model.SysRole)
	cacheKey := s.cache.Key(CacheSysRoleByIDPrefix, ID)
	cacheValue, err := s.cache.Fetch(ctx, cacheKey, func() (string, error) {
		dao := ai_boilerplate_dao.Use(s.db).SysRole
		result, err := dao.WithContext(ctx).Where(dao.ID.Eq(ID)).First()
		if err != nil && !errors.Is(err, gorm.ErrRecordNotFound) {
			return "", err
		}
		marshal, err := s.encoding.Marshal(result)
		if err != nil {
			return "", err
		}
		return string(marshal), nil
	}, s.cache.TTL())
	if err != nil {
		return nil, err
	}
	if cacheValue != "" {
		err = s.encoding.Unmarshal([]byte(cacheValue), resp)
		if err != nil {
			return nil, err
		}
	}
	return resp, nil
}

// FindOneUnscopedCacheByID 根据ID查询一条数据（包括软删除），并设置缓存
func (s *SysRoleRepo) FindOneUnscopedCacheByID(ctx context.Context, ID string) (*ai_boilerplate_model.SysRole, error) {
	resp := new(ai_boilerplate_model.SysRole)
	cacheKey := s.cache.Key(CacheSysRoleUnscopedByIDPrefix, ID)
	cacheValue, err := s.cache.Fetch(ctx, cacheKey, func() (string, error) {
		dao := ai_boilerplate_dao.Use(s.db).SysRole
		result, err := dao.WithContext(ctx).Unscoped().Where(dao.ID.Eq(ID)).First()
		if err != nil && !errors.Is(err, gorm.ErrRecordNotFound) {
			return "", err
		}
		marshal, err := s.encoding.Marshal(result)
		if err != nil {
			return "", err
		}
		return string(marshal), nil
	}, s.cache.TTL())
	if err != nil {
		return nil, err
	}
	if cacheValue != "" {
		err = s.encoding.Unmarshal([]byte(cacheValue), resp)
		if err != nil {
			return nil, err
		}
	}
	return resp, nil
}

// FindMultiByIDS 根据IDS查询多条数据
func (s *SysRoleRepo) FindMultiByIDS(ctx context.Context, IDS []string) ([]*ai_boilerplate_model.SysRole, error) {
	dao := ai_boilerplate_dao.Use(s.db).SysRole
	result, err := dao.WithContext(ctx).Where(dao.ID.In(IDS...)).Find()
	if err != nil {
		return nil, err
	}
	return result, nil
}

// FindMultiUnscopedByIDS 根据IDS查询多条数据（包括软删除）
func (s *SysRoleRepo) FindMultiUnscopedByIDS(ctx context.Context, IDS []string) ([]*ai_boilerplate_model.SysRole, error) {
	dao := ai_boilerplate_dao.Use(s.db).SysRole
	result, err := dao.WithContext(ctx).Unscoped().Where(dao.ID.In(IDS...)).Find()
	if err != nil {
		return nil, err
	}
	return result, nil
}

// FindMultiCacheByIDS 根据IDS查询多条数据，并设置缓存
func (s *SysRoleRepo) FindMultiCacheByIDS(ctx context.Context, IDS []string) ([]*ai_boilerplate_model.SysRole, error) {
	resp := make([]*ai_boilerplate_model.SysRole, 0)
	cacheKeys := make([]string, 0)
	keyToParam := make(map[string]string)
	for _, item := range IDS {
		cacheKey := s.cache.Key(CacheSysRoleByIDPrefix, item)
		cacheKeys = append(cacheKeys, cacheKey)
		keyToParam[cacheKey] = item
	}
	cacheValue, err := s.cache.FetchBatch(ctx, cacheKeys, func(miss []string) (map[string]string, error) {
		dbValue := make(map[string]string)
		params := make([]string, 0)
		for _, item := range miss {
			dbValue[item] = ""
			params = append(params, keyToParam[item])
		}
		dao := ai_boilerplate_dao.Use(s.db).SysRole
		result, err := dao.WithContext(ctx).Where(dao.ID.In(params...)).Find()
		if err != nil {
			return nil, err
		}
		for _, item := range result {
			marshal, err := s.encoding.Marshal(item)
			if err != nil {
				return nil, err
			}
			dbValue[s.cache.Key(CacheSysRoleByIDPrefix, item.ID)] = string(marshal)
		}
		return dbValue, nil
	}, s.cache.TTL())
	if err != nil {
		return nil, err
	}
	for _, cacheKey := range cacheKeys {
		if cacheValue[cacheKey] != "" {
			tmp := new(ai_boilerplate_model.SysRole)
			err := s.encoding.Unmarshal([]byte(cacheValue[cacheKey]), tmp)
			if err != nil {
				return nil, err
			}
			resp = append(resp, tmp)
		}
	}
	return resp, nil
}

// FindMultiUnscopedCacheByIDS 根据IDS查询多条数据（包括软删除），并设置缓存
func (s *SysRoleRepo) FindMultiUnscopedCacheByIDS(ctx context.Context, IDS []string) ([]*ai_boilerplate_model.SysRole, error) {
	resp := make([]*ai_boilerplate_model.SysRole, 0)
	cacheKeys := make([]string, 0)
	keyToParam := make(map[string]string)
	for _, item := range IDS {
		cacheKey := s.cache.Key(CacheSysRoleUnscopedByIDPrefix, item)
		cacheKeys = append(cacheKeys, cacheKey)
		keyToParam[cacheKey] = item
	}
	cacheValue, err := s.cache.FetchBatch(ctx, cacheKeys, func(miss []string) (map[string]string, error) {
		dbValue := make(map[string]string)
		params := make([]string, 0)
		for _, item := range miss {
			dbValue[item] = ""
			params = append(params, keyToParam[item])
		}
		dao := ai_boilerplate_dao.Use(s.db).SysRole
		result, err := dao.WithContext(ctx).Unscoped().Where(dao.ID.In(params...)).Find()
		if err != nil {
			return nil, err
		}
		for _, item := range result {
			marshal, err := s.encoding.Marshal(item)
			if err != nil {
				return nil, err
			}
			dbValue[s.cache.Key(CacheSysRoleUnscopedByIDPrefix, item.ID)] = string(marshal)
		}
		return dbValue, nil
	}, s.cache.TTL())
	if err != nil {
		return nil, err
	}
	for _, cacheKey := range cacheKeys {
		if cacheValue[cacheKey] != "" {
			tmp := new(ai_boilerplate_model.SysRole)
			err := s.encoding.Unmarshal([]byte(cacheValue[cacheKey]), tmp)
			if err != nil {
				return nil, err
			}
			resp = append(resp, tmp)
		}
	}
	return resp, nil
}

// FindMultiByTenantID 根据tenantID查询多条数据
func (s *SysRoleRepo) FindMultiByTenantID(ctx context.Context, tenantID string) ([]*ai_boilerplate_model.SysRole, error) {
	dao := ai_boilerplate_dao.Use(s.db).SysRole
	result, err := dao.WithContext(ctx).Where(dao.TenantID.Eq(tenantID)).Find()
	if err != nil {
		return nil, err
	}
	return result, nil
}

// FindMultiUnscopedByTenantID 根据tenantID查询多条数据（包括软删除）
func (s *SysRoleRepo) FindMultiUnscopedByTenantID(ctx context.Context, tenantID string) ([]*ai_boilerplate_model.SysRole, error) {
	dao := ai_boilerplate_dao.Use(s.db).SysRole
	result, err := dao.WithContext(ctx).Unscoped().Where(dao.TenantID.Eq(tenantID)).Find()
	if err != nil {
		return nil, err
	}
	return result, nil
}

// FindMultiCacheByTenantID 根据tenantID查询多条数据，并设置缓存
func (s *SysRoleRepo) FindMultiCacheByTenantID(ctx context.Context, tenantID string) ([]*ai_boilerplate_model.SysRole, error) {
	resp := make([]*ai_boilerplate_model.SysRole, 0)
	cacheKey := s.cache.Key(CacheSysRoleByTenantIDPrefix, tenantID)
	cacheValue, err := s.cache.Fetch(ctx, cacheKey, func() (string, error) {
		dao := ai_boilerplate_dao.Use(s.db).SysRole
		result, err := dao.WithContext(ctx).Where(dao.TenantID.Eq(tenantID)).Find()
		if err != nil && !errors.Is(err, gorm.ErrRecordNotFound) {
			return "", err
		}
		marshal, err := s.encoding.Marshal(result)
		if err != nil {
			return "", err
		}
		return string(marshal), nil
	}, s.cache.TTL())
	if err != nil {
		return nil, err
	}
	if cacheValue != "" {
		err = s.encoding.Unmarshal([]byte(cacheValue), &resp)
		if err != nil {
			return nil, err
		}
	}
	return resp, nil
}

// FindMultiUnscopedCacheByTenantID 根据tenantID查询多条数据（包括软删除），并设置缓存
func (s *SysRoleRepo) FindMultiUnscopedCacheByTenantID(ctx context.Context, tenantID string) ([]*ai_boilerplate_model.SysRole, error) {
	resp := make([]*ai_boilerplate_model.SysRole, 0)
	cacheKey := s.cache.Key(CacheSysRoleUnscopedByTenantIDPrefix, tenantID)
	cacheValue, err := s.cache.Fetch(ctx, cacheKey, func() (string, error) {
		dao := ai_boilerplate_dao.Use(s.db).SysRole
		result, err := dao.WithContext(ctx).Unscoped().Where(dao.TenantID.Eq(tenantID)).Find()
		if err != nil && !errors.Is(err, gorm.ErrRecordNotFound) {
			return "", err
		}
		marshal, err := s.encoding.Marshal(result)
		if err != nil {
			return "", err
		}
		return string(marshal), nil
	}, s.cache.TTL())
	if err != nil {
		return nil, err
	}
	if cacheValue != "" {
		err = s.encoding.Unmarshal([]byte(cacheValue), &resp)
		if err != nil {
			return nil, err
		}
	}
	return resp, nil
}

// FindMultiByTenantIDS 根据tenantIDS查询多条数据
func (s *SysRoleRepo) FindMultiByTenantIDS(ctx context.Context, tenantIDS []string) ([]*ai_boilerplate_model.SysRole, error) {
	dao := ai_boilerplate_dao.Use(s.db).SysRole
	result, err := dao.WithContext(ctx).Where(dao.TenantID.In(tenantIDS...)).Find()
	if err != nil {
		return nil, err
	}
	return result, nil
}

// FindMultiUnscopedByTenantIDS 根据tenantIDS查询多条数据（包括软删除）
func (s *SysRoleRepo) FindMultiUnscopedByTenantIDS(ctx context.Context, tenantIDS []string) ([]*ai_boilerplate_model.SysRole, error) {
	dao := ai_boilerplate_dao.Use(s.db).SysRole
	result, err := dao.WithContext(ctx).Unscoped().Where(dao.TenantID.In(tenantIDS...)).Find()
	if err != nil {
		return nil, err
	}
	return result, nil
}

// FindMultiCacheByTenantIDS 根据tenantIDS查询多条数据，并设置缓存
func (s *SysRoleRepo) FindMultiCacheByTenantIDS(ctx context.Context, tenantIDS []string) ([]*ai_boilerplate_model.SysRole, error) {
	resp := make([]*ai_boilerplate_model.SysRole, 0)
	cacheKeys := make([]string, 0)
	keyToParam := make(map[string]string)
	for _, item := range tenantIDS {
		cacheKey := s.cache.Key(CacheSysRoleByTenantIDPrefix, item)
		cacheKeys = append(cacheKeys, cacheKey)
		keyToParam[cacheKey] = item
	}
	cacheValue, err := s.cache.FetchBatch(ctx, cacheKeys, func(miss []string) (map[string]string, error) {
		dbValue := make(map[string]string)
		params := make([]string, 0)
		for _, item := range miss {
			dbValue[item] = ""
			params = append(params, keyToParam[item])
		}
		dao := ai_boilerplate_dao.Use(s.db).SysRole
		result, err := dao.WithContext(ctx).Where(dao.TenantID.In(params...)).Find()
		if err != nil {
			return nil, err
		}
		keyToValues := make(map[string][]*ai_boilerplate_model.SysRole)
		for _, item := range result {
			key := s.cache.Key(CacheSysRoleByTenantIDPrefix, item.TenantID)
			if keyToValues[key] == nil {
				keyToValues[key] = make([]*ai_boilerplate_model.SysRole, 0)
			}
			keyToValues[key] = append(keyToValues[key], item)
		}
		for item := range dbValue {
			if keyToValues[item] != nil {
				marshal, err := s.encoding.Marshal(keyToValues[item])
				if err != nil {
					return nil, err
				}
				dbValue[item] = string(marshal)
			}
		}
		return dbValue, nil
	}, s.cache.TTL())
	if err != nil {
		return nil, err
	}
	for _, cacheKey := range cacheKeys {
		if cacheValue[cacheKey] != "" {
			tmp := make([]*ai_boilerplate_model.SysRole, 0)
			err := s.encoding.Unmarshal([]byte(cacheValue[cacheKey]), &tmp)
			if err != nil {
				return nil, err
			}
			resp = append(resp, tmp...)
		}
	}
	return resp, nil
}

// FindMultiUnscopedCacheByTenantIDS 根据tenantIDS查询多条数据（包括软删除），并设置缓存
func (s *SysRoleRepo) FindMultiUnscopedCacheByTenantIDS(ctx context.Context, tenantIDS []string) ([]*ai_boilerplate_model.SysRole, error) {
	resp := make([]*ai_boilerplate_model.SysRole, 0)
	cacheKeys := make([]string, 0)
	keyToParam := make(map[string]string)
	for _, item := range tenantIDS {
		cacheKey := s.cache.Key(CacheSysRoleUnscopedByTenantIDPrefix, item)
		cacheKeys = append(cacheKeys, cacheKey)
		keyToParam[cacheKey] = item
	}
	cacheValue, err := s.cache.FetchBatch(ctx, cacheKeys, func(miss []string) (map[string]string, error) {
		dbValue := make(map[string]string)
		params := make([]string, 0)
		for _, item := range miss {
			dbValue[item] = ""
			params = append(params, keyToParam[item])
		}
		dao := ai_boilerplate_dao.Use(s.db).SysRole
		result, err := dao.WithContext(ctx).Unscoped().Where(dao.TenantID.In(params...)).Find()
		if err != nil {
			return nil, err
		}
		keyToValues := make(map[string][]*ai_boilerplate_model.SysRole)
		for _, item := range result {
			key := s.cache.Key(CacheSysRoleUnscopedByTenantIDPrefix, item.TenantID)
			if keyToValues[key] == nil {
				keyToValues[key] = make([]*ai_boilerplate_model.SysRole, 0)
			}
			keyToValues[key] = append(keyToValues[key], item)
		}
		for item := range dbValue {
			if keyToValues[item] != nil {
				marshal, err := s.encoding.Marshal(keyToValues[item])
				if err != nil {
					return nil, err
				}
				dbValue[item] = string(marshal)
			}
		}
		return dbValue, nil
	}, s.cache.TTL())
	if err != nil {
		return nil, err
	}
	for _, cacheKey := range cacheKeys {
		if cacheValue[cacheKey] != "" {
			tmp := make([]*ai_boilerplate_model.SysRole, 0)
			err := s.encoding.Unmarshal([]byte(cacheValue[cacheKey]), &tmp)
			if err != nil {
				return nil, err
			}
			resp = append(resp, tmp...)
		}
	}
	return resp, nil
}

// FindMultiByCondition 自定义查询数据(通用)
// 非万能查询方法,请评估后谨慎使用
func (s *SysRoleRepo) FindMultiByCondition(ctx context.Context, conditionReq *condition.Req) ([]*ai_boilerplate_model.SysRole, *condition.Reply, error) {
	result := make([]*ai_boilerplate_model.SysRole, 0)
	conditionReply := &condition.Reply{}
	var total int64
	whereExpressions, orderExpressions, err := conditionReq.ConvertToGormExpression(ai_boilerplate_model.SysRole{})
	if err != nil {
		return result, conditionReply, err
	}
	if conditionReq.Page != 0 && conditionReq.PageSize != 0 {
		err = s.db.WithContext(ctx).Model(&ai_boilerplate_model.SysRole{}).Clauses(whereExpressions...).Count(&total).Error
		if err != nil {
			return result, conditionReply, err
		}
		if total == 0 {
			return result, conditionReply, nil
		}
		conditionReply, err = conditionReq.ConvertToPage(int32(total))
		if err != nil {
			return result, conditionReply, err
		}
		query := s.db.WithContext(ctx).Model(&ai_boilerplate_model.SysRole{}).Clauses(whereExpressions...).Clauses(orderExpressions...)
		if conditionReply.Page != 0 && conditionReply.PageSize != 0 {
			query = query.Offset(int((conditionReply.Page - 1) * conditionReply.PageSize))
			query = query.Limit(int(conditionReply.PageSize))
		}
		err = query.Find(&result).Error
		if err != nil {
			return result, conditionReply, err
		}
	} else {
		err = s.db.WithContext(ctx).Model(&ai_boilerplate_model.SysRole{}).Clauses(whereExpressions...).Clauses(orderExpressions...).Find(&result).Error
		if err != nil {
			return result, conditionReply, err
		}
		conditionReply.Total = int32(len(result))
	}
	return result, conditionReply, err
}

// FindMultiUnscopedByCondition 自定义查询数据(通用)（包括软删除）
// 非万能查询方法,请评估后谨慎使用
func (s *SysRoleRepo) FindMultiUnscopedByCondition(ctx context.Context, conditionReq *condition.Req) ([]*ai_boilerplate_model.SysRole, *condition.Reply, error) {
	result := make([]*ai_boilerplate_model.SysRole, 0)
	conditionReply := &condition.Reply{}
	var total int64
	whereExpressions, orderExpressions, err := conditionReq.ConvertToGormExpression(ai_boilerplate_model.SysRole{})
	if err != nil {
		return result, conditionReply, err
	}
	if conditionReq.Page != 0 && conditionReq.PageSize != 0 {
		err = s.db.WithContext(ctx).Model(&ai_boilerplate_model.SysRole{}).Unscoped().Clauses(whereExpressions...).Count(&total).Error
		if err != nil {
			return result, conditionReply, err
		}
		if total == 0 {
			return result, conditionReply, nil
		}
		conditionReply, err = conditionReq.ConvertToPage(int32(total))
		if err != nil {
			return result, conditionReply, err
		}
		query := s.db.WithContext(ctx).Model(&ai_boilerplate_model.SysRole{}).Unscoped().Clauses(whereExpressions...).Clauses(orderExpressions...)
		if conditionReply.Page != 0 && conditionReply.PageSize != 0 {
			query = query.Offset(int((conditionReply.Page - 1) * conditionReply.PageSize))
			query = query.Limit(int(conditionReply.PageSize))
		}
		err = query.Find(&result).Error
		if err != nil {
			return result, conditionReply, err
		}
	} else {
		err = s.db.WithContext(ctx).Model(&ai_boilerplate_model.SysRole{}).Unscoped().Clauses(whereExpressions...).Clauses(orderExpressions...).Find(&result).Error
		if err != nil {
			return result, conditionReply, err
		}
		conditionReply.Total = int32(len(result))
	}
	return result, conditionReply, err
}

// FindMultiCacheByCondition 自定义查询数据(通用),并设置缓存
// 非万能查询方法,缓存命中率低,请评估后谨慎使用
func (s *SysRoleRepo) FindMultiCacheByCondition(ctx context.Context, conditionReq *condition.Req) ([]*ai_boilerplate_model.SysRole, *condition.Reply, error) {
	type Tmp struct {
		Result         []*ai_boilerplate_model.SysRole
		ConditionReply *condition.Reply
	}
	tmp := Tmp{
		Result:         make([]*ai_boilerplate_model.SysRole, 0),
		ConditionReply: &condition.Reply{},
	}
	cacheKey := s.cache.Key(CacheSysRoleByConditionPrefix)
	cacheField := conditionReq.ConvertToCacheField()
	cacheValue, err := s.cache.FetchHash(ctx, cacheKey, cacheField, func() (string, error) {
		result, conditionReply, err := s.FindMultiByCondition(ctx, conditionReq)
		if err != nil {
			return "", err
		}
		tmp.Result = result
		tmp.ConditionReply = conditionReply
		marshal, err := s.encoding.Marshal(tmp)
		if err != nil {
			return "", err
		}
		return string(marshal), nil
	}, s.cache.TTL())
	if err != nil {
		return tmp.Result, tmp.ConditionReply, err
	}
	if cacheValue != "" {
		err = s.encoding.Unmarshal([]byte(cacheValue), &tmp)
		if err != nil {
			return tmp.Result, tmp.ConditionReply, err
		}
	}
	return tmp.Result, tmp.ConditionReply, nil
}

// FindMultiUnscopedCacheByCondition 自定义查询数据(通用)（包括软删除）,并设置缓存
// 非万能查询方法,缓存命中率低,请评估后谨慎使用
func (s *SysRoleRepo) FindMultiUnscopedCacheByCondition(ctx context.Context, conditionReq *condition.Req) ([]*ai_boilerplate_model.SysRole, *condition.Reply, error) {
	type Tmp struct {
		Result         []*ai_boilerplate_model.SysRole
		ConditionReply *condition.Reply
	}
	tmp := Tmp{
		Result:         make([]*ai_boilerplate_model.SysRole, 0),
		ConditionReply: &condition.Reply{},
	}
	cacheKey := s.cache.Key(CacheSysRoleUnscopedByConditionPrefix)
	cacheField := conditionReq.ConvertToCacheField()
	cacheValue, err := s.cache.FetchHash(ctx, cacheKey, cacheField, func() (string, error) {
		result, conditionReply, err := s.FindMultiUnscopedByCondition(ctx, conditionReq)
		if err != nil {
			return "", err
		}
		tmp.Result = result
		tmp.ConditionReply = conditionReply
		marshal, err := s.encoding.Marshal(tmp)
		if err != nil {
			return "", err
		}
		return string(marshal), nil
	}, s.cache.TTL())
	if err != nil {
		return tmp.Result, tmp.ConditionReply, err
	}
	if cacheValue != "" {
		err = s.encoding.Unmarshal([]byte(cacheValue), &tmp)
		if err != nil {
			return tmp.Result, tmp.ConditionReply, err
		}
	}
	return tmp.Result, tmp.ConditionReply, nil
}

// DeleteOneByID 根据ID删除一条数据
func (s *SysRoleRepo) DeleteOneByID(ctx context.Context, ID string) error {
	dao := ai_boilerplate_dao.Use(s.db).SysRole
	_, err := dao.WithContext(ctx).Where(dao.ID.Eq(ID)).Delete()
	if err != nil {
		return err
	}
	return nil
}

// DeleteOneUnscopedByID 根据ID删除一条数据
func (s *SysRoleRepo) DeleteOneUnscopedByID(ctx context.Context, ID string) error {
	dao := ai_boilerplate_dao.Use(s.db).SysRole
	_, err := dao.WithContext(ctx).Unscoped().Where(dao.ID.Eq(ID)).Delete()
	if err != nil {
		return err
	}
	return nil
}

// DeleteOneCacheByID 根据ID删除一条数据，并删除缓存
func (s *SysRoleRepo) DeleteOneCacheByID(ctx context.Context, ID string) error {
	dao := ai_boilerplate_dao.Use(s.db).SysRole
	result, err := dao.WithContext(ctx).Where(dao.ID.Eq(ID)).First()
	if err != nil && !errors.Is(err, gorm.ErrRecordNotFound) {
		return err
	}
	if result == nil {
		return nil
	}
	_, err = dao.WithContext(ctx).Where(dao.ID.Eq(ID)).Delete()
	if err != nil {
		return err
	}
	err = s.DeleteIndexCache(ctx, result)
	if err != nil {
		return err
	}
	return nil
}

// DeleteOneUnscopedCacheByID 根据ID删除一条数据，并删除缓存
func (s *SysRoleRepo) DeleteOneUnscopedCacheByID(ctx context.Context, ID string) error {
	dao := ai_boilerplate_dao.Use(s.db).SysRole
	result, err := dao.WithContext(ctx).Unscoped().Where(dao.ID.Eq(ID)).First()
	if err != nil && !errors.Is(err, gorm.ErrRecordNotFound) {
		return err
	}
	if result == nil {
		return nil
	}
	_, err = dao.WithContext(ctx).Unscoped().Where(dao.ID.Eq(ID)).Delete()
	if err != nil {
		return err
	}
	err = s.DeleteIndexCache(ctx, result)
	if err != nil {
		return err
	}
	return nil
}

// DeleteOneByIDTx 根据ID删除一条数据
func (s *SysRoleRepo) DeleteOneByIDTx(ctx context.Context, tx *ai_boilerplate_dao.Query, ID string) error {
	dao := tx.SysRole
	_, err := dao.WithContext(ctx).Where(dao.ID.Eq(ID)).Delete()
	if err != nil {
		return err
	}
	return nil
}

// DeleteOneUnscopedByIDTx 根据ID删除一条数据
func (s *SysRoleRepo) DeleteOneUnscopedByIDTx(ctx context.Context, tx *ai_boilerplate_dao.Query, ID string) error {
	dao := tx.SysRole
	_, err := dao.WithContext(ctx).Unscoped().Where(dao.ID.Eq(ID)).Delete()
	if err != nil {
		return err
	}
	return nil
}

// DeleteOneCacheByIDTx 根据ID删除一条数据，并删除缓存
func (s *SysRoleRepo) DeleteOneCacheByIDTx(ctx context.Context, tx *ai_boilerplate_dao.Query, ID string) error {
	dao := tx.SysRole
	result, err := dao.WithContext(ctx).Where(dao.ID.Eq(ID)).First()
	if err != nil && !errors.Is(err, gorm.ErrRecordNotFound) {
		return err
	}
	if result == nil {
		return nil
	}
	_, err = dao.WithContext(ctx).Where(dao.ID.Eq(ID)).Delete()
	if err != nil {
		return err
	}
	err = s.DeleteIndexCache(ctx, result)
	if err != nil {
		return err
	}
	return nil
}

// DeleteOneUnscopedCacheByIDTx 根据ID删除一条数据，并删除缓存
func (s *SysRoleRepo) DeleteOneUnscopedCacheByIDTx(ctx context.Context, tx *ai_boilerplate_dao.Query, ID string) error {
	dao := tx.SysRole
	result, err := dao.WithContext(ctx).Unscoped().Where(dao.ID.Eq(ID)).First()
	if err != nil && !errors.Is(err, gorm.ErrRecordNotFound) {
		return err
	}
	if result == nil {
		return nil
	}
	_, err = dao.WithContext(ctx).Unscoped().Where(dao.ID.Eq(ID)).Delete()
	if err != nil {
		return err
	}
	err = s.DeleteIndexCache(ctx, result)
	if err != nil {
		return err
	}
	return nil
}

// DeleteMultiByIDS 根据IDS删除多条数据
func (s *SysRoleRepo) DeleteMultiByIDS(ctx context.Context, IDS []string) error {
	dao := ai_boilerplate_dao.Use(s.db).SysRole
	_, err := dao.WithContext(ctx).Where(dao.ID.In(IDS...)).Delete()
	if err != nil {
		return err
	}
	return nil
}

// DeleteMultiUnscopedByIDS 根据IDS删除多条数据
func (s *SysRoleRepo) DeleteMultiUnscopedByIDS(ctx context.Context, IDS []string) error {
	dao := ai_boilerplate_dao.Use(s.db).SysRole
	_, err := dao.WithContext(ctx).Unscoped().Where(dao.ID.In(IDS...)).Delete()
	if err != nil {
		return err
	}
	return nil
}

// DeleteMultiCacheByIDS 根据IDS删除多条数据，并删除缓存
func (s *SysRoleRepo) DeleteMultiCacheByIDS(ctx context.Context, IDS []string) error {
	dao := ai_boilerplate_dao.Use(s.db).SysRole
	result, err := dao.WithContext(ctx).Where(dao.ID.In(IDS...)).Find()
	if err != nil {
		return err
	}
	if len(result) == 0 {
		return nil
	}
	_, err = dao.WithContext(ctx).Where(dao.ID.In(IDS...)).Delete()
	if err != nil {
		return err
	}
	err = s.DeleteIndexCache(ctx, result...)
	if err != nil {
		return err
	}
	return nil
}

// DeleteMultiUnscopedCacheByIDS 根据IDS删除多条数据，并删除缓存
func (s *SysRoleRepo) DeleteMultiUnscopedCacheByIDS(ctx context.Context, IDS []string) error {
	dao := ai_boilerplate_dao.Use(s.db).SysRole
	result, err := dao.WithContext(ctx).Unscoped().Where(dao.ID.In(IDS...)).Find()
	if err != nil {
		return err
	}
	if len(result) == 0 {
		return nil
	}
	_, err = dao.WithContext(ctx).Unscoped().Where(dao.ID.In(IDS...)).Delete()
	if err != nil {
		return err
	}
	err = s.DeleteIndexCache(ctx, result...)
	if err != nil {
		return err
	}
	return nil
}

// DeleteMultiByIDSTx 根据IDS删除多条数据
func (s *SysRoleRepo) DeleteMultiByIDSTx(ctx context.Context, tx *ai_boilerplate_dao.Query, IDS []string) error {
	dao := tx.SysRole
	_, err := dao.WithContext(ctx).Where(dao.ID.In(IDS...)).Delete()
	if err != nil {
		return err
	}
	return nil
}

// DeleteMultiUnscopedByIDSTx 根据IDS删除多条数据
func (s *SysRoleRepo) DeleteMultiUnscopedByIDSTx(ctx context.Context, tx *ai_boilerplate_dao.Query, IDS []string) error {
	dao := tx.SysRole
	_, err := dao.WithContext(ctx).Unscoped().Where(dao.ID.In(IDS...)).Delete()
	if err != nil {
		return err
	}
	return nil
}

// DeleteMultiCacheByIDSTx 根据IDS删除多条数据，并删除缓存
func (s *SysRoleRepo) DeleteMultiCacheByIDSTx(ctx context.Context, tx *ai_boilerplate_dao.Query, IDS []string) error {
	dao := tx.SysRole
	result, err := dao.WithContext(ctx).Where(dao.ID.In(IDS...)).Find()
	if err != nil {
		return err
	}
	if len(result) == 0 {
		return nil
	}
	_, err = dao.WithContext(ctx).Where(dao.ID.In(IDS...)).Delete()
	if err != nil {
		return err
	}
	err = s.DeleteIndexCache(ctx, result...)
	if err != nil {
		return err
	}
	return nil
}

// DeleteMultiUnscopedCacheByIDSTx 根据IDS删除多条数据，并删除缓存
func (s *SysRoleRepo) DeleteMultiUnscopedCacheByIDSTx(ctx context.Context, tx *ai_boilerplate_dao.Query, IDS []string) error {
	dao := tx.SysRole
	result, err := dao.WithContext(ctx).Unscoped().Where(dao.ID.In(IDS...)).Find()
	if err != nil {
		return err
	}
	if len(result) == 0 {
		return nil
	}
	_, err = dao.WithContext(ctx).Unscoped().Where(dao.ID.In(IDS...)).Delete()
	if err != nil {
		return err
	}
	err = s.DeleteIndexCache(ctx, result...)
	if err != nil {
		return err
	}
	return nil
}

// DeleteMultiByTenantID 根据TenantID删除多条数据
func (s *SysRoleRepo) DeleteMultiByTenantID(ctx context.Context, tenantID string) error {
	dao := ai_boilerplate_dao.Use(s.db).SysRole
	_, err := dao.WithContext(ctx).Where(dao.TenantID.Eq(tenantID)).Delete()
	if err != nil {
		return err
	}
	return nil
}

// DeleteMultiUnscopedByTenantID 根据TenantID删除多条数据
func (s *SysRoleRepo) DeleteMultiUnscopedByTenantID(ctx context.Context, tenantID string) error {
	dao := ai_boilerplate_dao.Use(s.db).SysRole
	_, err := dao.WithContext(ctx).Unscoped().Where(dao.TenantID.Eq(tenantID)).Delete()
	if err != nil {
		return err
	}
	return nil
}

// DeleteMultiCacheByTenantID 根据tenantID删除多条数据，并删除缓存
func (s *SysRoleRepo) DeleteMultiCacheByTenantID(ctx context.Context, tenantID string) error {
	dao := ai_boilerplate_dao.Use(s.db).SysRole
	result, err := dao.WithContext(ctx).Where(dao.TenantID.Eq(tenantID)).Find()
	if err != nil {
		return err
	}
	if len(result) == 0 {
		return nil
	}
	_, err = dao.WithContext(ctx).Where(dao.TenantID.Eq(tenantID)).Delete()
	if err != nil {
		return err
	}
	err = s.DeleteIndexCache(ctx, result...)
	if err != nil {
		return err
	}
	return nil
}

// DeleteMultiUnscopedCacheByTenantID 根据tenantID删除多条数据，并删除缓存
func (s *SysRoleRepo) DeleteMultiUnscopedCacheByTenantID(ctx context.Context, tenantID string) error {
	dao := ai_boilerplate_dao.Use(s.db).SysRole
	result, err := dao.WithContext(ctx).Unscoped().Where(dao.TenantID.Eq(tenantID)).Find()
	if err != nil {
		return err
	}
	if len(result) == 0 {
		return nil
	}
	_, err = dao.WithContext(ctx).Unscoped().Where(dao.TenantID.Eq(tenantID)).Delete()
	if err != nil {
		return err
	}
	err = s.DeleteIndexCache(ctx, result...)
	if err != nil {
		return err
	}
	return nil
}

// DeleteMultiByTenantIDTx 根据tenantID删除多条数据
func (s *SysRoleRepo) DeleteMultiByTenantIDTx(ctx context.Context, tx *ai_boilerplate_dao.Query, tenantID string) error {
	dao := tx.SysRole
	_, err := dao.WithContext(ctx).Where(dao.TenantID.Eq(tenantID)).Delete()
	if err != nil {
		return err
	}
	return nil
}

// DeleteMultiUnscopedByTenantIDTx 根据tenantID删除多条数据
func (s *SysRoleRepo) DeleteMultiUnscopedByTenantIDTx(ctx context.Context, tx *ai_boilerplate_dao.Query, tenantID string) error {
	dao := tx.SysRole
	_, err := dao.WithContext(ctx).Unscoped().Where(dao.TenantID.Eq(tenantID)).Delete()
	if err != nil {
		return err
	}
	return nil
}

// DeleteMultiCacheByTenantIDTx 根据tenantID删除多条数据，并删除缓存
func (s *SysRoleRepo) DeleteMultiCacheByTenantIDTx(ctx context.Context, tx *ai_boilerplate_dao.Query, tenantID string) error {
	dao := tx.SysRole
	result, err := dao.WithContext(ctx).Where(dao.TenantID.Eq(tenantID)).Find()
	if err != nil {
		return err
	}
	if len(result) == 0 {
		return nil
	}
	_, err = dao.WithContext(ctx).Where(dao.TenantID.Eq(tenantID)).Delete()
	if err != nil {
		return err
	}
	err = s.DeleteIndexCache(ctx, result...)
	if err != nil {
		return err
	}
	return nil
}

// DeleteMultiUnscopedCacheByTenantIDTx 根据tenantID删除多条数据，并删除缓存
func (s *SysRoleRepo) DeleteMultiUnscopedCacheByTenantIDTx(ctx context.Context, tx *ai_boilerplate_dao.Query, tenantID string) error {
	dao := tx.SysRole
	result, err := dao.WithContext(ctx).Unscoped().Where(dao.TenantID.Eq(tenantID)).Find()
	if err != nil {
		return err
	}
	if len(result) == 0 {
		return nil
	}
	_, err = dao.WithContext(ctx).Unscoped().Where(dao.TenantID.Eq(tenantID)).Delete()
	if err != nil {
		return err
	}
	err = s.DeleteIndexCache(ctx, result...)
	if err != nil {
		return err
	}
	return nil
}

// DeleteMultiByTenantIDS 根据tenantIDS删除多条数据
func (s *SysRoleRepo) DeleteMultiByTenantIDS(ctx context.Context, tenantIDS []string) error {
	dao := ai_boilerplate_dao.Use(s.db).SysRole
	_, err := dao.WithContext(ctx).Where(dao.TenantID.In(tenantIDS...)).Delete()
	if err != nil {
		return err
	}
	return nil
}

// DeleteMultiUnscopedByTenantIDS 根据tenantIDS删除多条数据
func (s *SysRoleRepo) DeleteMultiUnscopedByTenantIDS(ctx context.Context, tenantIDS []string) error {
	dao := ai_boilerplate_dao.Use(s.db).SysRole
	_, err := dao.WithContext(ctx).Unscoped().Where(dao.TenantID.In(tenantIDS...)).Delete()
	if err != nil {
		return err
	}
	return nil
}

// DeleteMultiCacheByTenantIDS 根据tenantIDS删除多条数据，并删除缓存
func (s *SysRoleRepo) DeleteMultiCacheByTenantIDS(ctx context.Context, tenantIDS []string) error {
	dao := ai_boilerplate_dao.Use(s.db).SysRole
	result, err := dao.WithContext(ctx).Where(dao.TenantID.In(tenantIDS...)).Find()
	if err != nil {
		return err
	}
	if len(result) == 0 {
		return nil
	}
	_, err = dao.WithContext(ctx).Where(dao.TenantID.In(tenantIDS...)).Delete()
	if err != nil {
		return err
	}
	err = s.DeleteIndexCache(ctx, result...)
	if err != nil {
		return err
	}
	return nil
}

// DeleteMultiUnscopedCacheByTenantIDS 根据tenantIDS删除多条数据，并删除缓存
func (s *SysRoleRepo) DeleteMultiUnscopedCacheByTenantIDS(ctx context.Context, tenantIDS []string) error {
	dao := ai_boilerplate_dao.Use(s.db).SysRole
	result, err := dao.WithContext(ctx).Unscoped().Where(dao.TenantID.In(tenantIDS...)).Find()
	if err != nil {
		return err
	}
	if len(result) == 0 {
		return nil
	}
	_, err = dao.WithContext(ctx).Unscoped().Where(dao.TenantID.In(tenantIDS...)).Delete()
	if err != nil {
		return err
	}
	err = s.DeleteIndexCache(ctx, result...)
	if err != nil {
		return err
	}
	return nil
}

// DeleteMultiByTenantIDSTx 根据tenantIDS删除多条数据
func (s *SysRoleRepo) DeleteMultiByTenantIDSTx(ctx context.Context, tx *ai_boilerplate_dao.Query, tenantIDS []string) error {
	dao := tx.SysRole
	_, err := dao.WithContext(ctx).Where(dao.TenantID.In(tenantIDS...)).Delete()
	if err != nil {
		return err
	}
	return nil
}

// DeleteMultiUnscopedByTenantIDSTx 根据tenantIDS删除多条数据
func (s *SysRoleRepo) DeleteMultiUnscopedByTenantIDSTx(ctx context.Context, tx *ai_boilerplate_dao.Query, tenantIDS []string) error {
	dao := tx.SysRole
	_, err := dao.WithContext(ctx).Unscoped().Where(dao.TenantID.In(tenantIDS...)).Delete()
	if err != nil {
		return err
	}
	return nil
}

// DeleteMultiCacheByTenantIDSTx 根据tenantIDS删除多条数据，并删除缓存
func (s *SysRoleRepo) DeleteMultiCacheByTenantIDSTx(ctx context.Context, tx *ai_boilerplate_dao.Query, tenantIDS []string) error {
	dao := tx.SysRole
	result, err := dao.WithContext(ctx).Where(dao.TenantID.In(tenantIDS...)).Find()
	if err != nil {
		return err
	}
	if len(result) == 0 {
		return nil
	}
	_, err = dao.WithContext(ctx).Where(dao.TenantID.In(tenantIDS...)).Delete()
	if err != nil {
		return err
	}
	err = s.DeleteIndexCache(ctx, result...)
	if err != nil {
		return err
	}
	return nil
}

// DeleteMultiUnscopedCacheByTenantIDSTx 根据tenantIDS删除多条数据，并删除缓存
func (s *SysRoleRepo) DeleteMultiUnscopedCacheByTenantIDSTx(ctx context.Context, tx *ai_boilerplate_dao.Query, tenantIDS []string) error {
	dao := tx.SysRole
	result, err := dao.WithContext(ctx).Unscoped().Where(dao.TenantID.In(tenantIDS...)).Find()
	if err != nil {
		return err
	}
	if len(result) == 0 {
		return nil
	}
	_, err = dao.WithContext(ctx).Unscoped().Where(dao.TenantID.In(tenantIDS...)).Delete()
	if err != nil {
		return err
	}
	err = s.DeleteIndexCache(ctx, result...)
	if err != nil {
		return err
	}
	return nil
}

// DeleteUniqueIndexCache 删除索引存在的缓存
func (s *SysRoleRepo) DeleteIndexCache(ctx context.Context, data ...*ai_boilerplate_model.SysRole) error {
	KeyMap := make(map[string]struct{})
	keys := make([]string, 0)
	keys = append(keys, s.cache.Key(CacheSysRoleByConditionPrefix))
	keys = append(keys, s.cache.Key(CacheSysRoleUnscopedByConditionPrefix))
	for _, item := range data {
		if item != nil {
			KeyMap[s.cache.Key(CacheSysRoleByIDPrefix, item.ID)] = struct{}{}
			KeyMap[s.cache.Key(CacheSysRoleUnscopedByIDPrefix, item.ID)] = struct{}{}
			KeyMap[s.cache.Key(CacheSysRoleByTenantIDPrefix, item.TenantID)] = struct{}{}
			KeyMap[s.cache.Key(CacheSysRoleUnscopedByTenantIDPrefix, item.TenantID)] = struct{}{}
		}
	}
	for item := range KeyMap {
		keys = append(keys, item)
	}
	err := s.cache.DelBatch(ctx, keys)
	if err != nil {
		return err
	}
	return nil
}
