// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.5.3
// - protoc             v3.21.9
// source: admin/v1/ai_index_prompt.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationAiIndexPromptCreateAiIndexPrompt = "/admin.v1.AiIndexPrompt/CreateAiIndexPrompt"
const OperationAiIndexPromptDeleteAiIndexPrompt = "/admin.v1.AiIndexPrompt/DeleteAiIndexPrompt"
const OperationAiIndexPromptGetAiIndexPromptInfo = "/admin.v1.AiIndexPrompt/GetAiIndexPromptInfo"
const OperationAiIndexPromptGetAiIndexPromptList = "/admin.v1.AiIndexPrompt/GetAiIndexPromptList"
const OperationAiIndexPromptUpdateAiIndexPrompt = "/admin.v1.AiIndexPrompt/UpdateAiIndexPrompt"

type AiIndexPromptHTTPServer interface {
	CreateAiIndexPrompt(context.Context, *CreateAiIndexPromptReq) (*CreateAiIndexPromptReply, error)
	DeleteAiIndexPrompt(context.Context, *DeleteAiIndexPromptReq) (*DeleteAiIndexPromptReply, error)
	GetAiIndexPromptInfo(context.Context, *GetAiIndexPromptInfoReq) (*GetAiIndexPromptInfoReply, error)
	GetAiIndexPromptList(context.Context, *GetAiIndexPromptListReq) (*GetAiIndexPromptListReply, error)
	UpdateAiIndexPrompt(context.Context, *UpdateAiIndexPromptReq) (*UpdateAiIndexPromptReply, error)
}

func RegisterAiIndexPromptHTTPServer(s *http.Server, srv AiIndexPromptHTTPServer) {
	r := s.Route("/")
	r.POST("/admin/v1/ai_prompt/create", _AiIndexPrompt_CreateAiIndexPrompt0_HTTP_Handler(srv))
	r.POST("/admin/v1/ai_prompt/update", _AiIndexPrompt_UpdateAiIndexPrompt0_HTTP_Handler(srv))
	r.POST("/admin/v1/ai_prompt/delete", _AiIndexPrompt_DeleteAiIndexPrompt0_HTTP_Handler(srv))
	r.GET("/admin/v1/ai_prompt/info", _AiIndexPrompt_GetAiIndexPromptInfo0_HTTP_Handler(srv))
	r.GET("/admin/v1/ai_prompt/list", _AiIndexPrompt_GetAiIndexPromptList0_HTTP_Handler(srv))
}

func _AiIndexPrompt_CreateAiIndexPrompt0_HTTP_Handler(srv AiIndexPromptHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateAiIndexPromptReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAiIndexPromptCreateAiIndexPrompt)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateAiIndexPrompt(ctx, req.(*CreateAiIndexPromptReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateAiIndexPromptReply)
		return ctx.Result(200, reply)
	}
}

func _AiIndexPrompt_UpdateAiIndexPrompt0_HTTP_Handler(srv AiIndexPromptHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateAiIndexPromptReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAiIndexPromptUpdateAiIndexPrompt)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateAiIndexPrompt(ctx, req.(*UpdateAiIndexPromptReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateAiIndexPromptReply)
		return ctx.Result(200, reply)
	}
}

func _AiIndexPrompt_DeleteAiIndexPrompt0_HTTP_Handler(srv AiIndexPromptHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteAiIndexPromptReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAiIndexPromptDeleteAiIndexPrompt)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteAiIndexPrompt(ctx, req.(*DeleteAiIndexPromptReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteAiIndexPromptReply)
		return ctx.Result(200, reply)
	}
}

func _AiIndexPrompt_GetAiIndexPromptInfo0_HTTP_Handler(srv AiIndexPromptHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetAiIndexPromptInfoReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAiIndexPromptGetAiIndexPromptInfo)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetAiIndexPromptInfo(ctx, req.(*GetAiIndexPromptInfoReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetAiIndexPromptInfoReply)
		return ctx.Result(200, reply)
	}
}

func _AiIndexPrompt_GetAiIndexPromptList0_HTTP_Handler(srv AiIndexPromptHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetAiIndexPromptListReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAiIndexPromptGetAiIndexPromptList)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetAiIndexPromptList(ctx, req.(*GetAiIndexPromptListReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetAiIndexPromptListReply)
		return ctx.Result(200, reply)
	}
}

type AiIndexPromptHTTPClient interface {
	CreateAiIndexPrompt(ctx context.Context, req *CreateAiIndexPromptReq, opts ...http.CallOption) (rsp *CreateAiIndexPromptReply, err error)
	DeleteAiIndexPrompt(ctx context.Context, req *DeleteAiIndexPromptReq, opts ...http.CallOption) (rsp *DeleteAiIndexPromptReply, err error)
	GetAiIndexPromptInfo(ctx context.Context, req *GetAiIndexPromptInfoReq, opts ...http.CallOption) (rsp *GetAiIndexPromptInfoReply, err error)
	GetAiIndexPromptList(ctx context.Context, req *GetAiIndexPromptListReq, opts ...http.CallOption) (rsp *GetAiIndexPromptListReply, err error)
	UpdateAiIndexPrompt(ctx context.Context, req *UpdateAiIndexPromptReq, opts ...http.CallOption) (rsp *UpdateAiIndexPromptReply, err error)
}

type AiIndexPromptHTTPClientImpl struct {
	cc *http.Client
}

func NewAiIndexPromptHTTPClient(client *http.Client) AiIndexPromptHTTPClient {
	return &AiIndexPromptHTTPClientImpl{client}
}

func (c *AiIndexPromptHTTPClientImpl) CreateAiIndexPrompt(ctx context.Context, in *CreateAiIndexPromptReq, opts ...http.CallOption) (*CreateAiIndexPromptReply, error) {
	var out CreateAiIndexPromptReply
	pattern := "/admin/v1/ai_prompt/create"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAiIndexPromptCreateAiIndexPrompt))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *AiIndexPromptHTTPClientImpl) DeleteAiIndexPrompt(ctx context.Context, in *DeleteAiIndexPromptReq, opts ...http.CallOption) (*DeleteAiIndexPromptReply, error) {
	var out DeleteAiIndexPromptReply
	pattern := "/admin/v1/ai_prompt/delete"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAiIndexPromptDeleteAiIndexPrompt))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *AiIndexPromptHTTPClientImpl) GetAiIndexPromptInfo(ctx context.Context, in *GetAiIndexPromptInfoReq, opts ...http.CallOption) (*GetAiIndexPromptInfoReply, error) {
	var out GetAiIndexPromptInfoReply
	pattern := "/admin/v1/ai_prompt/info"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAiIndexPromptGetAiIndexPromptInfo))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *AiIndexPromptHTTPClientImpl) GetAiIndexPromptList(ctx context.Context, in *GetAiIndexPromptListReq, opts ...http.CallOption) (*GetAiIndexPromptListReply, error) {
	var out GetAiIndexPromptListReply
	pattern := "/admin/v1/ai_prompt/list"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAiIndexPromptGetAiIndexPromptList))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *AiIndexPromptHTTPClientImpl) UpdateAiIndexPrompt(ctx context.Context, in *UpdateAiIndexPromptReq, opts ...http.CallOption) (*UpdateAiIndexPromptReply, error) {
	var out UpdateAiIndexPromptReply
	pattern := "/admin/v1/ai_prompt/update"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAiIndexPromptUpdateAiIndexPrompt))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
