// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: admin/v1/ai_provider_platform.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on AiProviderPlatformInfo with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *AiProviderPlatformInfo) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AiProviderPlatformInfo with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AiProviderPlatformInfoMultiError, or nil if none found.
func (m *AiProviderPlatformInfo) ValidateAll() error {
	return m.validate(true)
}

func (m *AiProviderPlatformInfo) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Platform

	// no validation rules for Name

	// no validation rules for APIURL

	// no validation rules for APIKey

	// no validation rules for DocURL

	// no validation rules for Sort

	// no validation rules for Status

	// no validation rules for CreatedAt

	// no validation rules for UpdatedAt

	if len(errors) > 0 {
		return AiProviderPlatformInfoMultiError(errors)
	}

	return nil
}

// AiProviderPlatformInfoMultiError is an error wrapping multiple validation
// errors returned by AiProviderPlatformInfo.ValidateAll() if the designated
// constraints aren't met.
type AiProviderPlatformInfoMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AiProviderPlatformInfoMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AiProviderPlatformInfoMultiError) AllErrors() []error { return m }

// AiProviderPlatformInfoValidationError is the validation error returned by
// AiProviderPlatformInfo.Validate if the designated constraints aren't met.
type AiProviderPlatformInfoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AiProviderPlatformInfoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AiProviderPlatformInfoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AiProviderPlatformInfoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AiProviderPlatformInfoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AiProviderPlatformInfoValidationError) ErrorName() string {
	return "AiProviderPlatformInfoValidationError"
}

// Error satisfies the builtin error interface
func (e AiProviderPlatformInfoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAiProviderPlatformInfo.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AiProviderPlatformInfoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AiProviderPlatformInfoValidationError{}

// Validate checks the field values on CreateAiProviderPlatformReq with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateAiProviderPlatformReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateAiProviderPlatformReq with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateAiProviderPlatformReqMultiError, or nil if none found.
func (m *CreateAiProviderPlatformReq) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateAiProviderPlatformReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Platform

	// no validation rules for Name

	// no validation rules for APIURL

	// no validation rules for APIKey

	// no validation rules for DocURL

	// no validation rules for Sort

	// no validation rules for Status

	if len(errors) > 0 {
		return CreateAiProviderPlatformReqMultiError(errors)
	}

	return nil
}

// CreateAiProviderPlatformReqMultiError is an error wrapping multiple
// validation errors returned by CreateAiProviderPlatformReq.ValidateAll() if
// the designated constraints aren't met.
type CreateAiProviderPlatformReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateAiProviderPlatformReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateAiProviderPlatformReqMultiError) AllErrors() []error { return m }

// CreateAiProviderPlatformReqValidationError is the validation error returned
// by CreateAiProviderPlatformReq.Validate if the designated constraints
// aren't met.
type CreateAiProviderPlatformReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateAiProviderPlatformReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateAiProviderPlatformReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateAiProviderPlatformReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateAiProviderPlatformReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateAiProviderPlatformReqValidationError) ErrorName() string {
	return "CreateAiProviderPlatformReqValidationError"
}

// Error satisfies the builtin error interface
func (e CreateAiProviderPlatformReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateAiProviderPlatformReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateAiProviderPlatformReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateAiProviderPlatformReqValidationError{}

// Validate checks the field values on CreateAiProviderPlatformReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateAiProviderPlatformReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateAiProviderPlatformReply with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// CreateAiProviderPlatformReplyMultiError, or nil if none found.
func (m *CreateAiProviderPlatformReply) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateAiProviderPlatformReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return CreateAiProviderPlatformReplyMultiError(errors)
	}

	return nil
}

// CreateAiProviderPlatformReplyMultiError is an error wrapping multiple
// validation errors returned by CreateAiProviderPlatformReply.ValidateAll()
// if the designated constraints aren't met.
type CreateAiProviderPlatformReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateAiProviderPlatformReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateAiProviderPlatformReplyMultiError) AllErrors() []error { return m }

// CreateAiProviderPlatformReplyValidationError is the validation error
// returned by CreateAiProviderPlatformReply.Validate if the designated
// constraints aren't met.
type CreateAiProviderPlatformReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateAiProviderPlatformReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateAiProviderPlatformReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateAiProviderPlatformReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateAiProviderPlatformReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateAiProviderPlatformReplyValidationError) ErrorName() string {
	return "CreateAiProviderPlatformReplyValidationError"
}

// Error satisfies the builtin error interface
func (e CreateAiProviderPlatformReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateAiProviderPlatformReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateAiProviderPlatformReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateAiProviderPlatformReplyValidationError{}

// Validate checks the field values on UpdateAiProviderPlatformReq with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateAiProviderPlatformReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateAiProviderPlatformReq with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateAiProviderPlatformReqMultiError, or nil if none found.
func (m *UpdateAiProviderPlatformReq) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateAiProviderPlatformReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Platform

	// no validation rules for Name

	// no validation rules for APIURL

	// no validation rules for APIKey

	// no validation rules for DocURL

	// no validation rules for Sort

	// no validation rules for Status

	if len(errors) > 0 {
		return UpdateAiProviderPlatformReqMultiError(errors)
	}

	return nil
}

// UpdateAiProviderPlatformReqMultiError is an error wrapping multiple
// validation errors returned by UpdateAiProviderPlatformReq.ValidateAll() if
// the designated constraints aren't met.
type UpdateAiProviderPlatformReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateAiProviderPlatformReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateAiProviderPlatformReqMultiError) AllErrors() []error { return m }

// UpdateAiProviderPlatformReqValidationError is the validation error returned
// by UpdateAiProviderPlatformReq.Validate if the designated constraints
// aren't met.
type UpdateAiProviderPlatformReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateAiProviderPlatformReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateAiProviderPlatformReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateAiProviderPlatformReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateAiProviderPlatformReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateAiProviderPlatformReqValidationError) ErrorName() string {
	return "UpdateAiProviderPlatformReqValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateAiProviderPlatformReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateAiProviderPlatformReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateAiProviderPlatformReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateAiProviderPlatformReqValidationError{}

// Validate checks the field values on UpdateAiProviderPlatformReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateAiProviderPlatformReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateAiProviderPlatformReply with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// UpdateAiProviderPlatformReplyMultiError, or nil if none found.
func (m *UpdateAiProviderPlatformReply) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateAiProviderPlatformReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return UpdateAiProviderPlatformReplyMultiError(errors)
	}

	return nil
}

// UpdateAiProviderPlatformReplyMultiError is an error wrapping multiple
// validation errors returned by UpdateAiProviderPlatformReply.ValidateAll()
// if the designated constraints aren't met.
type UpdateAiProviderPlatformReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateAiProviderPlatformReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateAiProviderPlatformReplyMultiError) AllErrors() []error { return m }

// UpdateAiProviderPlatformReplyValidationError is the validation error
// returned by UpdateAiProviderPlatformReply.Validate if the designated
// constraints aren't met.
type UpdateAiProviderPlatformReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateAiProviderPlatformReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateAiProviderPlatformReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateAiProviderPlatformReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateAiProviderPlatformReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateAiProviderPlatformReplyValidationError) ErrorName() string {
	return "UpdateAiProviderPlatformReplyValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateAiProviderPlatformReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateAiProviderPlatformReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateAiProviderPlatformReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateAiProviderPlatformReplyValidationError{}

// Validate checks the field values on UpdateAiProviderPlatformStatusReq with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *UpdateAiProviderPlatformStatusReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateAiProviderPlatformStatusReq
// with the rules defined in the proto definition for this message. If any
// rules are violated, the result is a list of violation errors wrapped in
// UpdateAiProviderPlatformStatusReqMultiError, or nil if none found.
func (m *UpdateAiProviderPlatformStatusReq) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateAiProviderPlatformStatusReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Status

	if len(errors) > 0 {
		return UpdateAiProviderPlatformStatusReqMultiError(errors)
	}

	return nil
}

// UpdateAiProviderPlatformStatusReqMultiError is an error wrapping multiple
// validation errors returned by
// UpdateAiProviderPlatformStatusReq.ValidateAll() if the designated
// constraints aren't met.
type UpdateAiProviderPlatformStatusReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateAiProviderPlatformStatusReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateAiProviderPlatformStatusReqMultiError) AllErrors() []error { return m }

// UpdateAiProviderPlatformStatusReqValidationError is the validation error
// returned by UpdateAiProviderPlatformStatusReq.Validate if the designated
// constraints aren't met.
type UpdateAiProviderPlatformStatusReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateAiProviderPlatformStatusReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateAiProviderPlatformStatusReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateAiProviderPlatformStatusReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateAiProviderPlatformStatusReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateAiProviderPlatformStatusReqValidationError) ErrorName() string {
	return "UpdateAiProviderPlatformStatusReqValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateAiProviderPlatformStatusReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateAiProviderPlatformStatusReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateAiProviderPlatformStatusReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateAiProviderPlatformStatusReqValidationError{}

// Validate checks the field values on UpdateAiProviderPlatformStatusReply with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *UpdateAiProviderPlatformStatusReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateAiProviderPlatformStatusReply
// with the rules defined in the proto definition for this message. If any
// rules are violated, the result is a list of violation errors wrapped in
// UpdateAiProviderPlatformStatusReplyMultiError, or nil if none found.
func (m *UpdateAiProviderPlatformStatusReply) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateAiProviderPlatformStatusReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return UpdateAiProviderPlatformStatusReplyMultiError(errors)
	}

	return nil
}

// UpdateAiProviderPlatformStatusReplyMultiError is an error wrapping multiple
// validation errors returned by
// UpdateAiProviderPlatformStatusReply.ValidateAll() if the designated
// constraints aren't met.
type UpdateAiProviderPlatformStatusReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateAiProviderPlatformStatusReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateAiProviderPlatformStatusReplyMultiError) AllErrors() []error { return m }

// UpdateAiProviderPlatformStatusReplyValidationError is the validation error
// returned by UpdateAiProviderPlatformStatusReply.Validate if the designated
// constraints aren't met.
type UpdateAiProviderPlatformStatusReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateAiProviderPlatformStatusReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateAiProviderPlatformStatusReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateAiProviderPlatformStatusReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateAiProviderPlatformStatusReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateAiProviderPlatformStatusReplyValidationError) ErrorName() string {
	return "UpdateAiProviderPlatformStatusReplyValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateAiProviderPlatformStatusReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateAiProviderPlatformStatusReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateAiProviderPlatformStatusReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateAiProviderPlatformStatusReplyValidationError{}

// Validate checks the field values on DeleteAiProviderPlatformReq with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteAiProviderPlatformReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteAiProviderPlatformReq with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteAiProviderPlatformReqMultiError, or nil if none found.
func (m *DeleteAiProviderPlatformReq) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteAiProviderPlatformReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return DeleteAiProviderPlatformReqMultiError(errors)
	}

	return nil
}

// DeleteAiProviderPlatformReqMultiError is an error wrapping multiple
// validation errors returned by DeleteAiProviderPlatformReq.ValidateAll() if
// the designated constraints aren't met.
type DeleteAiProviderPlatformReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteAiProviderPlatformReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteAiProviderPlatformReqMultiError) AllErrors() []error { return m }

// DeleteAiProviderPlatformReqValidationError is the validation error returned
// by DeleteAiProviderPlatformReq.Validate if the designated constraints
// aren't met.
type DeleteAiProviderPlatformReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteAiProviderPlatformReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteAiProviderPlatformReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteAiProviderPlatformReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteAiProviderPlatformReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteAiProviderPlatformReqValidationError) ErrorName() string {
	return "DeleteAiProviderPlatformReqValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteAiProviderPlatformReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteAiProviderPlatformReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteAiProviderPlatformReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteAiProviderPlatformReqValidationError{}

// Validate checks the field values on DeleteAiProviderPlatformReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteAiProviderPlatformReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteAiProviderPlatformReply with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// DeleteAiProviderPlatformReplyMultiError, or nil if none found.
func (m *DeleteAiProviderPlatformReply) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteAiProviderPlatformReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return DeleteAiProviderPlatformReplyMultiError(errors)
	}

	return nil
}

// DeleteAiProviderPlatformReplyMultiError is an error wrapping multiple
// validation errors returned by DeleteAiProviderPlatformReply.ValidateAll()
// if the designated constraints aren't met.
type DeleteAiProviderPlatformReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteAiProviderPlatformReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteAiProviderPlatformReplyMultiError) AllErrors() []error { return m }

// DeleteAiProviderPlatformReplyValidationError is the validation error
// returned by DeleteAiProviderPlatformReply.Validate if the designated
// constraints aren't met.
type DeleteAiProviderPlatformReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteAiProviderPlatformReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteAiProviderPlatformReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteAiProviderPlatformReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteAiProviderPlatformReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteAiProviderPlatformReplyValidationError) ErrorName() string {
	return "DeleteAiProviderPlatformReplyValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteAiProviderPlatformReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteAiProviderPlatformReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteAiProviderPlatformReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteAiProviderPlatformReplyValidationError{}

// Validate checks the field values on GetAiProviderPlatformInfoReq with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetAiProviderPlatformInfoReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetAiProviderPlatformInfoReq with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetAiProviderPlatformInfoReqMultiError, or nil if none found.
func (m *GetAiProviderPlatformInfoReq) ValidateAll() error {
	return m.validate(true)
}

func (m *GetAiProviderPlatformInfoReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return GetAiProviderPlatformInfoReqMultiError(errors)
	}

	return nil
}

// GetAiProviderPlatformInfoReqMultiError is an error wrapping multiple
// validation errors returned by GetAiProviderPlatformInfoReq.ValidateAll() if
// the designated constraints aren't met.
type GetAiProviderPlatformInfoReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetAiProviderPlatformInfoReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetAiProviderPlatformInfoReqMultiError) AllErrors() []error { return m }

// GetAiProviderPlatformInfoReqValidationError is the validation error returned
// by GetAiProviderPlatformInfoReq.Validate if the designated constraints
// aren't met.
type GetAiProviderPlatformInfoReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetAiProviderPlatformInfoReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetAiProviderPlatformInfoReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetAiProviderPlatformInfoReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetAiProviderPlatformInfoReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetAiProviderPlatformInfoReqValidationError) ErrorName() string {
	return "GetAiProviderPlatformInfoReqValidationError"
}

// Error satisfies the builtin error interface
func (e GetAiProviderPlatformInfoReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetAiProviderPlatformInfoReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetAiProviderPlatformInfoReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetAiProviderPlatformInfoReqValidationError{}

// Validate checks the field values on GetAiProviderPlatformInfoReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetAiProviderPlatformInfoReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetAiProviderPlatformInfoReply with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// GetAiProviderPlatformInfoReplyMultiError, or nil if none found.
func (m *GetAiProviderPlatformInfoReply) ValidateAll() error {
	return m.validate(true)
}

func (m *GetAiProviderPlatformInfoReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetInfo()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetAiProviderPlatformInfoReplyValidationError{
					field:  "Info",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetAiProviderPlatformInfoReplyValidationError{
					field:  "Info",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetInfo()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetAiProviderPlatformInfoReplyValidationError{
				field:  "Info",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetAiProviderPlatformInfoReplyMultiError(errors)
	}

	return nil
}

// GetAiProviderPlatformInfoReplyMultiError is an error wrapping multiple
// validation errors returned by GetAiProviderPlatformInfoReply.ValidateAll()
// if the designated constraints aren't met.
type GetAiProviderPlatformInfoReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetAiProviderPlatformInfoReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetAiProviderPlatformInfoReplyMultiError) AllErrors() []error { return m }

// GetAiProviderPlatformInfoReplyValidationError is the validation error
// returned by GetAiProviderPlatformInfoReply.Validate if the designated
// constraints aren't met.
type GetAiProviderPlatformInfoReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetAiProviderPlatformInfoReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetAiProviderPlatformInfoReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetAiProviderPlatformInfoReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetAiProviderPlatformInfoReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetAiProviderPlatformInfoReplyValidationError) ErrorName() string {
	return "GetAiProviderPlatformInfoReplyValidationError"
}

// Error satisfies the builtin error interface
func (e GetAiProviderPlatformInfoReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetAiProviderPlatformInfoReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetAiProviderPlatformInfoReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetAiProviderPlatformInfoReplyValidationError{}

// Validate checks the field values on GetAiProviderPlatformListReq with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetAiProviderPlatformListReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetAiProviderPlatformListReq with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetAiProviderPlatformListReqMultiError, or nil if none found.
func (m *GetAiProviderPlatformListReq) ValidateAll() error {
	return m.validate(true)
}

func (m *GetAiProviderPlatformListReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Page

	// no validation rules for PageSize

	// no validation rules for Platform

	// no validation rules for Status

	if len(errors) > 0 {
		return GetAiProviderPlatformListReqMultiError(errors)
	}

	return nil
}

// GetAiProviderPlatformListReqMultiError is an error wrapping multiple
// validation errors returned by GetAiProviderPlatformListReq.ValidateAll() if
// the designated constraints aren't met.
type GetAiProviderPlatformListReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetAiProviderPlatformListReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetAiProviderPlatformListReqMultiError) AllErrors() []error { return m }

// GetAiProviderPlatformListReqValidationError is the validation error returned
// by GetAiProviderPlatformListReq.Validate if the designated constraints
// aren't met.
type GetAiProviderPlatformListReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetAiProviderPlatformListReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetAiProviderPlatformListReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetAiProviderPlatformListReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetAiProviderPlatformListReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetAiProviderPlatformListReqValidationError) ErrorName() string {
	return "GetAiProviderPlatformListReqValidationError"
}

// Error satisfies the builtin error interface
func (e GetAiProviderPlatformListReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetAiProviderPlatformListReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetAiProviderPlatformListReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetAiProviderPlatformListReqValidationError{}

// Validate checks the field values on GetAiProviderPlatformListReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetAiProviderPlatformListReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetAiProviderPlatformListReply with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// GetAiProviderPlatformListReplyMultiError, or nil if none found.
func (m *GetAiProviderPlatformListReply) ValidateAll() error {
	return m.validate(true)
}

func (m *GetAiProviderPlatformListReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Total

	for idx, item := range m.GetList() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetAiProviderPlatformListReplyValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetAiProviderPlatformListReplyValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetAiProviderPlatformListReplyValidationError{
					field:  fmt.Sprintf("List[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return GetAiProviderPlatformListReplyMultiError(errors)
	}

	return nil
}

// GetAiProviderPlatformListReplyMultiError is an error wrapping multiple
// validation errors returned by GetAiProviderPlatformListReply.ValidateAll()
// if the designated constraints aren't met.
type GetAiProviderPlatformListReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetAiProviderPlatformListReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetAiProviderPlatformListReplyMultiError) AllErrors() []error { return m }

// GetAiProviderPlatformListReplyValidationError is the validation error
// returned by GetAiProviderPlatformListReply.Validate if the designated
// constraints aren't met.
type GetAiProviderPlatformListReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetAiProviderPlatformListReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetAiProviderPlatformListReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetAiProviderPlatformListReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetAiProviderPlatformListReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetAiProviderPlatformListReplyValidationError) ErrorName() string {
	return "GetAiProviderPlatformListReplyValidationError"
}

// Error satisfies the builtin error interface
func (e GetAiProviderPlatformListReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetAiProviderPlatformListReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetAiProviderPlatformListReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetAiProviderPlatformListReplyValidationError{}

// Validate checks the field values on AiProviderPlatformSelectorItem with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *AiProviderPlatformSelectorItem) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AiProviderPlatformSelectorItem with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// AiProviderPlatformSelectorItemMultiError, or nil if none found.
func (m *AiProviderPlatformSelectorItem) ValidateAll() error {
	return m.validate(true)
}

func (m *AiProviderPlatformSelectorItem) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Label

	// no validation rules for Value

	if len(errors) > 0 {
		return AiProviderPlatformSelectorItemMultiError(errors)
	}

	return nil
}

// AiProviderPlatformSelectorItemMultiError is an error wrapping multiple
// validation errors returned by AiProviderPlatformSelectorItem.ValidateAll()
// if the designated constraints aren't met.
type AiProviderPlatformSelectorItemMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AiProviderPlatformSelectorItemMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AiProviderPlatformSelectorItemMultiError) AllErrors() []error { return m }

// AiProviderPlatformSelectorItemValidationError is the validation error
// returned by AiProviderPlatformSelectorItem.Validate if the designated
// constraints aren't met.
type AiProviderPlatformSelectorItemValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AiProviderPlatformSelectorItemValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AiProviderPlatformSelectorItemValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AiProviderPlatformSelectorItemValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AiProviderPlatformSelectorItemValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AiProviderPlatformSelectorItemValidationError) ErrorName() string {
	return "AiProviderPlatformSelectorItemValidationError"
}

// Error satisfies the builtin error interface
func (e AiProviderPlatformSelectorItemValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAiProviderPlatformSelectorItem.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AiProviderPlatformSelectorItemValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AiProviderPlatformSelectorItemValidationError{}

// Validate checks the field values on GetAiProviderPlatformSelectorReq with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *GetAiProviderPlatformSelectorReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetAiProviderPlatformSelectorReq with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// GetAiProviderPlatformSelectorReqMultiError, or nil if none found.
func (m *GetAiProviderPlatformSelectorReq) ValidateAll() error {
	return m.validate(true)
}

func (m *GetAiProviderPlatformSelectorReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return GetAiProviderPlatformSelectorReqMultiError(errors)
	}

	return nil
}

// GetAiProviderPlatformSelectorReqMultiError is an error wrapping multiple
// validation errors returned by
// GetAiProviderPlatformSelectorReq.ValidateAll() if the designated
// constraints aren't met.
type GetAiProviderPlatformSelectorReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetAiProviderPlatformSelectorReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetAiProviderPlatformSelectorReqMultiError) AllErrors() []error { return m }

// GetAiProviderPlatformSelectorReqValidationError is the validation error
// returned by GetAiProviderPlatformSelectorReq.Validate if the designated
// constraints aren't met.
type GetAiProviderPlatformSelectorReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetAiProviderPlatformSelectorReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetAiProviderPlatformSelectorReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetAiProviderPlatformSelectorReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetAiProviderPlatformSelectorReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetAiProviderPlatformSelectorReqValidationError) ErrorName() string {
	return "GetAiProviderPlatformSelectorReqValidationError"
}

// Error satisfies the builtin error interface
func (e GetAiProviderPlatformSelectorReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetAiProviderPlatformSelectorReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetAiProviderPlatformSelectorReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetAiProviderPlatformSelectorReqValidationError{}

// Validate checks the field values on GetAiProviderPlatformSelectorReply with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *GetAiProviderPlatformSelectorReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetAiProviderPlatformSelectorReply
// with the rules defined in the proto definition for this message. If any
// rules are violated, the result is a list of violation errors wrapped in
// GetAiProviderPlatformSelectorReplyMultiError, or nil if none found.
func (m *GetAiProviderPlatformSelectorReply) ValidateAll() error {
	return m.validate(true)
}

func (m *GetAiProviderPlatformSelectorReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetList() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetAiProviderPlatformSelectorReplyValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetAiProviderPlatformSelectorReplyValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetAiProviderPlatformSelectorReplyValidationError{
					field:  fmt.Sprintf("List[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return GetAiProviderPlatformSelectorReplyMultiError(errors)
	}

	return nil
}

// GetAiProviderPlatformSelectorReplyMultiError is an error wrapping multiple
// validation errors returned by
// GetAiProviderPlatformSelectorReply.ValidateAll() if the designated
// constraints aren't met.
type GetAiProviderPlatformSelectorReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetAiProviderPlatformSelectorReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetAiProviderPlatformSelectorReplyMultiError) AllErrors() []error { return m }

// GetAiProviderPlatformSelectorReplyValidationError is the validation error
// returned by GetAiProviderPlatformSelectorReply.Validate if the designated
// constraints aren't met.
type GetAiProviderPlatformSelectorReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetAiProviderPlatformSelectorReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetAiProviderPlatformSelectorReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetAiProviderPlatformSelectorReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetAiProviderPlatformSelectorReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetAiProviderPlatformSelectorReplyValidationError) ErrorName() string {
	return "GetAiProviderPlatformSelectorReplyValidationError"
}

// Error satisfies the builtin error interface
func (e GetAiProviderPlatformSelectorReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetAiProviderPlatformSelectorReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetAiProviderPlatformSelectorReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetAiProviderPlatformSelectorReplyValidationError{}
