// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.9
// source: admin/v1/device.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DeviceClient is the client API for Device service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DeviceClient interface {
	// 设备表-注册设备
	RegisterDevice(ctx context.Context, in *RegisterDeviceReq, opts ...grpc.CallOption) (*RegisterDeviceReply, error)
	// 设备表-更新状态
	UpdateDeviceStatus(ctx context.Context, in *UpdateDeviceStatusReq, opts ...grpc.CallOption) (*UpdateDeviceStatusReply, error)
	// 设备表-删除一条数据
	DeleteDevice(ctx context.Context, in *DeleteDeviceReq, opts ...grpc.CallOption) (*DeleteDeviceReply, error)
	// 设备表-单条数据查询
	GetDeviceInfo(ctx context.Context, in *GetDeviceInfoReq, opts ...grpc.CallOption) (*GetDeviceInfoReply, error)
	// 设备表-列表数据查询
	GetDeviceList(ctx context.Context, in *GetDeviceListReq, opts ...grpc.CallOption) (*GetDeviceListReply, error)
	// 设备表-在线设备数量统计
	GetOnlineDeviceCount(ctx context.Context, in *GetOnlineDeviceCountReq, opts ...grpc.CallOption) (*GetOnlineDeviceCountReply, error)
}

type deviceClient struct {
	cc grpc.ClientConnInterface
}

func NewDeviceClient(cc grpc.ClientConnInterface) DeviceClient {
	return &deviceClient{cc}
}

func (c *deviceClient) RegisterDevice(ctx context.Context, in *RegisterDeviceReq, opts ...grpc.CallOption) (*RegisterDeviceReply, error) {
	out := new(RegisterDeviceReply)
	err := c.cc.Invoke(ctx, "/admin.v1.Device/RegisterDevice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceClient) UpdateDeviceStatus(ctx context.Context, in *UpdateDeviceStatusReq, opts ...grpc.CallOption) (*UpdateDeviceStatusReply, error) {
	out := new(UpdateDeviceStatusReply)
	err := c.cc.Invoke(ctx, "/admin.v1.Device/UpdateDeviceStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceClient) DeleteDevice(ctx context.Context, in *DeleteDeviceReq, opts ...grpc.CallOption) (*DeleteDeviceReply, error) {
	out := new(DeleteDeviceReply)
	err := c.cc.Invoke(ctx, "/admin.v1.Device/DeleteDevice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceClient) GetDeviceInfo(ctx context.Context, in *GetDeviceInfoReq, opts ...grpc.CallOption) (*GetDeviceInfoReply, error) {
	out := new(GetDeviceInfoReply)
	err := c.cc.Invoke(ctx, "/admin.v1.Device/GetDeviceInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceClient) GetDeviceList(ctx context.Context, in *GetDeviceListReq, opts ...grpc.CallOption) (*GetDeviceListReply, error) {
	out := new(GetDeviceListReply)
	err := c.cc.Invoke(ctx, "/admin.v1.Device/GetDeviceList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceClient) GetOnlineDeviceCount(ctx context.Context, in *GetOnlineDeviceCountReq, opts ...grpc.CallOption) (*GetOnlineDeviceCountReply, error) {
	out := new(GetOnlineDeviceCountReply)
	err := c.cc.Invoke(ctx, "/admin.v1.Device/GetOnlineDeviceCount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeviceServer is the server API for Device service.
// All implementations must embed UnimplementedDeviceServer
// for forward compatibility
type DeviceServer interface {
	// 设备表-注册设备
	RegisterDevice(context.Context, *RegisterDeviceReq) (*RegisterDeviceReply, error)
	// 设备表-更新状态
	UpdateDeviceStatus(context.Context, *UpdateDeviceStatusReq) (*UpdateDeviceStatusReply, error)
	// 设备表-删除一条数据
	DeleteDevice(context.Context, *DeleteDeviceReq) (*DeleteDeviceReply, error)
	// 设备表-单条数据查询
	GetDeviceInfo(context.Context, *GetDeviceInfoReq) (*GetDeviceInfoReply, error)
	// 设备表-列表数据查询
	GetDeviceList(context.Context, *GetDeviceListReq) (*GetDeviceListReply, error)
	// 设备表-在线设备数量统计
	GetOnlineDeviceCount(context.Context, *GetOnlineDeviceCountReq) (*GetOnlineDeviceCountReply, error)
	mustEmbedUnimplementedDeviceServer()
}

// UnimplementedDeviceServer must be embedded to have forward compatible implementations.
type UnimplementedDeviceServer struct {
}

func (UnimplementedDeviceServer) RegisterDevice(context.Context, *RegisterDeviceReq) (*RegisterDeviceReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterDevice not implemented")
}
func (UnimplementedDeviceServer) UpdateDeviceStatus(context.Context, *UpdateDeviceStatusReq) (*UpdateDeviceStatusReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDeviceStatus not implemented")
}
func (UnimplementedDeviceServer) DeleteDevice(context.Context, *DeleteDeviceReq) (*DeleteDeviceReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDevice not implemented")
}
func (UnimplementedDeviceServer) GetDeviceInfo(context.Context, *GetDeviceInfoReq) (*GetDeviceInfoReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDeviceInfo not implemented")
}
func (UnimplementedDeviceServer) GetDeviceList(context.Context, *GetDeviceListReq) (*GetDeviceListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDeviceList not implemented")
}
func (UnimplementedDeviceServer) GetOnlineDeviceCount(context.Context, *GetOnlineDeviceCountReq) (*GetOnlineDeviceCountReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOnlineDeviceCount not implemented")
}
func (UnimplementedDeviceServer) mustEmbedUnimplementedDeviceServer() {}

// UnsafeDeviceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeviceServer will
// result in compilation errors.
type UnsafeDeviceServer interface {
	mustEmbedUnimplementedDeviceServer()
}

func RegisterDeviceServer(s grpc.ServiceRegistrar, srv DeviceServer) {
	s.RegisterService(&Device_ServiceDesc, srv)
}

func _Device_RegisterDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterDeviceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceServer).RegisterDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin.v1.Device/RegisterDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceServer).RegisterDevice(ctx, req.(*RegisterDeviceReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Device_UpdateDeviceStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDeviceStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceServer).UpdateDeviceStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin.v1.Device/UpdateDeviceStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceServer).UpdateDeviceStatus(ctx, req.(*UpdateDeviceStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Device_DeleteDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDeviceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceServer).DeleteDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin.v1.Device/DeleteDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceServer).DeleteDevice(ctx, req.(*DeleteDeviceReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Device_GetDeviceInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeviceInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceServer).GetDeviceInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin.v1.Device/GetDeviceInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceServer).GetDeviceInfo(ctx, req.(*GetDeviceInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Device_GetDeviceList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeviceListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceServer).GetDeviceList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin.v1.Device/GetDeviceList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceServer).GetDeviceList(ctx, req.(*GetDeviceListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Device_GetOnlineDeviceCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOnlineDeviceCountReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceServer).GetOnlineDeviceCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin.v1.Device/GetOnlineDeviceCount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceServer).GetOnlineDeviceCount(ctx, req.(*GetOnlineDeviceCountReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Device_ServiceDesc is the grpc.ServiceDesc for Device service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Device_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "admin.v1.Device",
	HandlerType: (*DeviceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterDevice",
			Handler:    _Device_RegisterDevice_Handler,
		},
		{
			MethodName: "UpdateDeviceStatus",
			Handler:    _Device_UpdateDeviceStatus_Handler,
		},
		{
			MethodName: "DeleteDevice",
			Handler:    _Device_DeleteDevice_Handler,
		},
		{
			MethodName: "GetDeviceInfo",
			Handler:    _Device_GetDeviceInfo_Handler,
		},
		{
			MethodName: "GetDeviceList",
			Handler:    _Device_GetDeviceList_Handler,
		},
		{
			MethodName: "GetOnlineDeviceCount",
			Handler:    _Device_GetOnlineDeviceCount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "admin/v1/device.proto",
}
