// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.9
// source: admin/v1/mall_order.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MallOrderClient is the client API for MallOrder service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MallOrderClient interface {
	// 订单信息表-单条数据查询
	GetMallOrderInfo(ctx context.Context, in *GetMallOrderInfoReq, opts ...grpc.CallOption) (*GetMallOrderInfoReply, error)
	// 订单信息表-列表数据查询
	GetMallOrderList(ctx context.Context, in *GetMallOrderListReq, opts ...grpc.CallOption) (*GetMallOrderListReply, error)
}

type mallOrderClient struct {
	cc grpc.ClientConnInterface
}

func NewMallOrderClient(cc grpc.ClientConnInterface) MallOrderClient {
	return &mallOrderClient{cc}
}

func (c *mallOrderClient) GetMallOrderInfo(ctx context.Context, in *GetMallOrderInfoReq, opts ...grpc.CallOption) (*GetMallOrderInfoReply, error) {
	out := new(GetMallOrderInfoReply)
	err := c.cc.Invoke(ctx, "/admin.v1.MallOrder/GetMallOrderInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mallOrderClient) GetMallOrderList(ctx context.Context, in *GetMallOrderListReq, opts ...grpc.CallOption) (*GetMallOrderListReply, error) {
	out := new(GetMallOrderListReply)
	err := c.cc.Invoke(ctx, "/admin.v1.MallOrder/GetMallOrderList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MallOrderServer is the server API for MallOrder service.
// All implementations must embed UnimplementedMallOrderServer
// for forward compatibility
type MallOrderServer interface {
	// 订单信息表-单条数据查询
	GetMallOrderInfo(context.Context, *GetMallOrderInfoReq) (*GetMallOrderInfoReply, error)
	// 订单信息表-列表数据查询
	GetMallOrderList(context.Context, *GetMallOrderListReq) (*GetMallOrderListReply, error)
	mustEmbedUnimplementedMallOrderServer()
}

// UnimplementedMallOrderServer must be embedded to have forward compatible implementations.
type UnimplementedMallOrderServer struct {
}

func (UnimplementedMallOrderServer) GetMallOrderInfo(context.Context, *GetMallOrderInfoReq) (*GetMallOrderInfoReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMallOrderInfo not implemented")
}
func (UnimplementedMallOrderServer) GetMallOrderList(context.Context, *GetMallOrderListReq) (*GetMallOrderListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMallOrderList not implemented")
}
func (UnimplementedMallOrderServer) mustEmbedUnimplementedMallOrderServer() {}

// UnsafeMallOrderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MallOrderServer will
// result in compilation errors.
type UnsafeMallOrderServer interface {
	mustEmbedUnimplementedMallOrderServer()
}

func RegisterMallOrderServer(s grpc.ServiceRegistrar, srv MallOrderServer) {
	s.RegisterService(&MallOrder_ServiceDesc, srv)
}

func _MallOrder_GetMallOrderInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMallOrderInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MallOrderServer).GetMallOrderInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin.v1.MallOrder/GetMallOrderInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MallOrderServer).GetMallOrderInfo(ctx, req.(*GetMallOrderInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MallOrder_GetMallOrderList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMallOrderListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MallOrderServer).GetMallOrderList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/admin.v1.MallOrder/GetMallOrderList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MallOrderServer).GetMallOrderList(ctx, req.(*GetMallOrderListReq))
	}
	return interceptor(ctx, in, info, handler)
}

// MallOrder_ServiceDesc is the grpc.ServiceDesc for MallOrder service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MallOrder_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "admin.v1.MallOrder",
	HandlerType: (*MallOrderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMallOrderInfo",
			Handler:    _MallOrder_GetMallOrderInfo_Handler,
		},
		{
			MethodName: "GetMallOrderList",
			Handler:    _MallOrder_GetMallOrderList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "admin/v1/mall_order.proto",
}
