// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: admin/v1/sys_auth.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on SysMenuItem with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *SysMenuItem) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SysMenuItem with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in SysMenuItemMultiError, or
// nil if none found.
func (m *SysMenuItem) ValidateAll() error {
	return m.validate(true)
}

func (m *SysMenuItem) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Pid

	// no validation rules for Name

	// no validation rules for Type

	// no validation rules for Path

	// no validation rules for Permission

	// no validation rules for Icon

	// no validation rules for Component

	// no validation rules for ComponentName

	// no validation rules for Sort

	// no validation rules for Status

	for idx, item := range m.GetChildren() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, SysMenuItemValidationError{
						field:  fmt.Sprintf("Children[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, SysMenuItemValidationError{
						field:  fmt.Sprintf("Children[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return SysMenuItemValidationError{
					field:  fmt.Sprintf("Children[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return SysMenuItemMultiError(errors)
	}

	return nil
}

// SysMenuItemMultiError is an error wrapping multiple validation errors
// returned by SysMenuItem.ValidateAll() if the designated constraints aren't met.
type SysMenuItemMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SysMenuItemMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SysMenuItemMultiError) AllErrors() []error { return m }

// SysMenuItemValidationError is the validation error returned by
// SysMenuItem.Validate if the designated constraints aren't met.
type SysMenuItemValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SysMenuItemValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SysMenuItemValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SysMenuItemValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SysMenuItemValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SysMenuItemValidationError) ErrorName() string { return "SysMenuItemValidationError" }

// Error satisfies the builtin error interface
func (e SysMenuItemValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSysMenuItem.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SysMenuItemValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SysMenuItemValidationError{}

// Validate checks the field values on SysAuthLoginReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *SysAuthLoginReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SysAuthLoginReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SysAuthLoginReqMultiError, or nil if none found.
func (m *SysAuthLoginReq) ValidateAll() error {
	return m.validate(true)
}

func (m *SysAuthLoginReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Username

	// no validation rules for Password

	if len(errors) > 0 {
		return SysAuthLoginReqMultiError(errors)
	}

	return nil
}

// SysAuthLoginReqMultiError is an error wrapping multiple validation errors
// returned by SysAuthLoginReq.ValidateAll() if the designated constraints
// aren't met.
type SysAuthLoginReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SysAuthLoginReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SysAuthLoginReqMultiError) AllErrors() []error { return m }

// SysAuthLoginReqValidationError is the validation error returned by
// SysAuthLoginReq.Validate if the designated constraints aren't met.
type SysAuthLoginReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SysAuthLoginReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SysAuthLoginReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SysAuthLoginReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SysAuthLoginReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SysAuthLoginReqValidationError) ErrorName() string { return "SysAuthLoginReqValidationError" }

// Error satisfies the builtin error interface
func (e SysAuthLoginReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSysAuthLoginReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SysAuthLoginReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SysAuthLoginReqValidationError{}

// Validate checks the field values on SysAuthLoginReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *SysAuthLoginReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SysAuthLoginReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SysAuthLoginReplyMultiError, or nil if none found.
func (m *SysAuthLoginReply) ValidateAll() error {
	return m.validate(true)
}

func (m *SysAuthLoginReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Token

	// no validation rules for ExpiredAt

	// no validation rules for RefreshAt

	if len(errors) > 0 {
		return SysAuthLoginReplyMultiError(errors)
	}

	return nil
}

// SysAuthLoginReplyMultiError is an error wrapping multiple validation errors
// returned by SysAuthLoginReply.ValidateAll() if the designated constraints
// aren't met.
type SysAuthLoginReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SysAuthLoginReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SysAuthLoginReplyMultiError) AllErrors() []error { return m }

// SysAuthLoginReplyValidationError is the validation error returned by
// SysAuthLoginReply.Validate if the designated constraints aren't met.
type SysAuthLoginReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SysAuthLoginReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SysAuthLoginReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SysAuthLoginReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SysAuthLoginReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SysAuthLoginReplyValidationError) ErrorName() string {
	return "SysAuthLoginReplyValidationError"
}

// Error satisfies the builtin error interface
func (e SysAuthLoginReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSysAuthLoginReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SysAuthLoginReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SysAuthLoginReplyValidationError{}

// Validate checks the field values on SysAuthLogoutReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *SysAuthLogoutReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SysAuthLogoutReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SysAuthLogoutReqMultiError, or nil if none found.
func (m *SysAuthLogoutReq) ValidateAll() error {
	return m.validate(true)
}

func (m *SysAuthLogoutReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return SysAuthLogoutReqMultiError(errors)
	}

	return nil
}

// SysAuthLogoutReqMultiError is an error wrapping multiple validation errors
// returned by SysAuthLogoutReq.ValidateAll() if the designated constraints
// aren't met.
type SysAuthLogoutReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SysAuthLogoutReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SysAuthLogoutReqMultiError) AllErrors() []error { return m }

// SysAuthLogoutReqValidationError is the validation error returned by
// SysAuthLogoutReq.Validate if the designated constraints aren't met.
type SysAuthLogoutReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SysAuthLogoutReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SysAuthLogoutReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SysAuthLogoutReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SysAuthLogoutReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SysAuthLogoutReqValidationError) ErrorName() string { return "SysAuthLogoutReqValidationError" }

// Error satisfies the builtin error interface
func (e SysAuthLogoutReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSysAuthLogoutReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SysAuthLogoutReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SysAuthLogoutReqValidationError{}

// Validate checks the field values on SysAuthLogoutReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SysAuthLogoutReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SysAuthLogoutReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SysAuthLogoutReplyMultiError, or nil if none found.
func (m *SysAuthLogoutReply) ValidateAll() error {
	return m.validate(true)
}

func (m *SysAuthLogoutReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return SysAuthLogoutReplyMultiError(errors)
	}

	return nil
}

// SysAuthLogoutReplyMultiError is an error wrapping multiple validation errors
// returned by SysAuthLogoutReply.ValidateAll() if the designated constraints
// aren't met.
type SysAuthLogoutReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SysAuthLogoutReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SysAuthLogoutReplyMultiError) AllErrors() []error { return m }

// SysAuthLogoutReplyValidationError is the validation error returned by
// SysAuthLogoutReply.Validate if the designated constraints aren't met.
type SysAuthLogoutReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SysAuthLogoutReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SysAuthLogoutReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SysAuthLogoutReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SysAuthLogoutReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SysAuthLogoutReplyValidationError) ErrorName() string {
	return "SysAuthLogoutReplyValidationError"
}

// Error satisfies the builtin error interface
func (e SysAuthLogoutReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSysAuthLogoutReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SysAuthLogoutReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SysAuthLogoutReplyValidationError{}

// Validate checks the field values on SysAuthCheckTokenReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SysAuthCheckTokenReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SysAuthCheckTokenReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SysAuthCheckTokenReqMultiError, or nil if none found.
func (m *SysAuthCheckTokenReq) ValidateAll() error {
	return m.validate(true)
}

func (m *SysAuthCheckTokenReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Token

	if len(errors) > 0 {
		return SysAuthCheckTokenReqMultiError(errors)
	}

	return nil
}

// SysAuthCheckTokenReqMultiError is an error wrapping multiple validation
// errors returned by SysAuthCheckTokenReq.ValidateAll() if the designated
// constraints aren't met.
type SysAuthCheckTokenReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SysAuthCheckTokenReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SysAuthCheckTokenReqMultiError) AllErrors() []error { return m }

// SysAuthCheckTokenReqValidationError is the validation error returned by
// SysAuthCheckTokenReq.Validate if the designated constraints aren't met.
type SysAuthCheckTokenReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SysAuthCheckTokenReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SysAuthCheckTokenReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SysAuthCheckTokenReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SysAuthCheckTokenReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SysAuthCheckTokenReqValidationError) ErrorName() string {
	return "SysAuthCheckTokenReqValidationError"
}

// Error satisfies the builtin error interface
func (e SysAuthCheckTokenReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSysAuthCheckTokenReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SysAuthCheckTokenReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SysAuthCheckTokenReqValidationError{}

// Validate checks the field values on SysAuthCheckTokenReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SysAuthCheckTokenReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SysAuthCheckTokenReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SysAuthCheckTokenReplyMultiError, or nil if none found.
func (m *SysAuthCheckTokenReply) ValidateAll() error {
	return m.validate(true)
}

func (m *SysAuthCheckTokenReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for AdminId

	// no validation rules for Nickname

	// no validation rules for TenantId

	if len(errors) > 0 {
		return SysAuthCheckTokenReplyMultiError(errors)
	}

	return nil
}

// SysAuthCheckTokenReplyMultiError is an error wrapping multiple validation
// errors returned by SysAuthCheckTokenReply.ValidateAll() if the designated
// constraints aren't met.
type SysAuthCheckTokenReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SysAuthCheckTokenReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SysAuthCheckTokenReplyMultiError) AllErrors() []error { return m }

// SysAuthCheckTokenReplyValidationError is the validation error returned by
// SysAuthCheckTokenReply.Validate if the designated constraints aren't met.
type SysAuthCheckTokenReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SysAuthCheckTokenReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SysAuthCheckTokenReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SysAuthCheckTokenReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SysAuthCheckTokenReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SysAuthCheckTokenReplyValidationError) ErrorName() string {
	return "SysAuthCheckTokenReplyValidationError"
}

// Error satisfies the builtin error interface
func (e SysAuthCheckTokenReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSysAuthCheckTokenReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SysAuthCheckTokenReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SysAuthCheckTokenReplyValidationError{}

// Validate checks the field values on SysAuthAdminInfoReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SysAuthAdminInfoReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SysAuthAdminInfoReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SysAuthAdminInfoReqMultiError, or nil if none found.
func (m *SysAuthAdminInfoReq) ValidateAll() error {
	return m.validate(true)
}

func (m *SysAuthAdminInfoReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return SysAuthAdminInfoReqMultiError(errors)
	}

	return nil
}

// SysAuthAdminInfoReqMultiError is an error wrapping multiple validation
// errors returned by SysAuthAdminInfoReq.ValidateAll() if the designated
// constraints aren't met.
type SysAuthAdminInfoReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SysAuthAdminInfoReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SysAuthAdminInfoReqMultiError) AllErrors() []error { return m }

// SysAuthAdminInfoReqValidationError is the validation error returned by
// SysAuthAdminInfoReq.Validate if the designated constraints aren't met.
type SysAuthAdminInfoReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SysAuthAdminInfoReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SysAuthAdminInfoReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SysAuthAdminInfoReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SysAuthAdminInfoReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SysAuthAdminInfoReqValidationError) ErrorName() string {
	return "SysAuthAdminInfoReqValidationError"
}

// Error satisfies the builtin error interface
func (e SysAuthAdminInfoReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSysAuthAdminInfoReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SysAuthAdminInfoReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SysAuthAdminInfoReqValidationError{}

// Validate checks the field values on SysAuthAdminInfoReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SysAuthAdminInfoReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SysAuthAdminInfoReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SysAuthAdminInfoReplyMultiError, or nil if none found.
func (m *SysAuthAdminInfoReply) ValidateAll() error {
	return m.validate(true)
}

func (m *SysAuthAdminInfoReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetInfo()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, SysAuthAdminInfoReplyValidationError{
					field:  "Info",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, SysAuthAdminInfoReplyValidationError{
					field:  "Info",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetInfo()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SysAuthAdminInfoReplyValidationError{
				field:  "Info",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return SysAuthAdminInfoReplyMultiError(errors)
	}

	return nil
}

// SysAuthAdminInfoReplyMultiError is an error wrapping multiple validation
// errors returned by SysAuthAdminInfoReply.ValidateAll() if the designated
// constraints aren't met.
type SysAuthAdminInfoReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SysAuthAdminInfoReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SysAuthAdminInfoReplyMultiError) AllErrors() []error { return m }

// SysAuthAdminInfoReplyValidationError is the validation error returned by
// SysAuthAdminInfoReply.Validate if the designated constraints aren't met.
type SysAuthAdminInfoReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SysAuthAdminInfoReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SysAuthAdminInfoReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SysAuthAdminInfoReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SysAuthAdminInfoReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SysAuthAdminInfoReplyValidationError) ErrorName() string {
	return "SysAuthAdminInfoReplyValidationError"
}

// Error satisfies the builtin error interface
func (e SysAuthAdminInfoReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSysAuthAdminInfoReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SysAuthAdminInfoReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SysAuthAdminInfoReplyValidationError{}

// Validate checks the field values on SysAuthUpdateAdminInfoReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SysAuthUpdateAdminInfoReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SysAuthUpdateAdminInfoReq with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SysAuthUpdateAdminInfoReqMultiError, or nil if none found.
func (m *SysAuthUpdateAdminInfoReq) ValidateAll() error {
	return m.validate(true)
}

func (m *SysAuthUpdateAdminInfoReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Nickname

	// no validation rules for Avatar

	// no validation rules for Sex

	if len(errors) > 0 {
		return SysAuthUpdateAdminInfoReqMultiError(errors)
	}

	return nil
}

// SysAuthUpdateAdminInfoReqMultiError is an error wrapping multiple validation
// errors returned by SysAuthUpdateAdminInfoReq.ValidateAll() if the
// designated constraints aren't met.
type SysAuthUpdateAdminInfoReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SysAuthUpdateAdminInfoReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SysAuthUpdateAdminInfoReqMultiError) AllErrors() []error { return m }

// SysAuthUpdateAdminInfoReqValidationError is the validation error returned by
// SysAuthUpdateAdminInfoReq.Validate if the designated constraints aren't met.
type SysAuthUpdateAdminInfoReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SysAuthUpdateAdminInfoReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SysAuthUpdateAdminInfoReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SysAuthUpdateAdminInfoReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SysAuthUpdateAdminInfoReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SysAuthUpdateAdminInfoReqValidationError) ErrorName() string {
	return "SysAuthUpdateAdminInfoReqValidationError"
}

// Error satisfies the builtin error interface
func (e SysAuthUpdateAdminInfoReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSysAuthUpdateAdminInfoReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SysAuthUpdateAdminInfoReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SysAuthUpdateAdminInfoReqValidationError{}

// Validate checks the field values on SysAuthUpdateAdminInfoReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SysAuthUpdateAdminInfoReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SysAuthUpdateAdminInfoReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SysAuthUpdateAdminInfoReplyMultiError, or nil if none found.
func (m *SysAuthUpdateAdminInfoReply) ValidateAll() error {
	return m.validate(true)
}

func (m *SysAuthUpdateAdminInfoReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return SysAuthUpdateAdminInfoReplyMultiError(errors)
	}

	return nil
}

// SysAuthUpdateAdminInfoReplyMultiError is an error wrapping multiple
// validation errors returned by SysAuthUpdateAdminInfoReply.ValidateAll() if
// the designated constraints aren't met.
type SysAuthUpdateAdminInfoReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SysAuthUpdateAdminInfoReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SysAuthUpdateAdminInfoReplyMultiError) AllErrors() []error { return m }

// SysAuthUpdateAdminInfoReplyValidationError is the validation error returned
// by SysAuthUpdateAdminInfoReply.Validate if the designated constraints
// aren't met.
type SysAuthUpdateAdminInfoReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SysAuthUpdateAdminInfoReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SysAuthUpdateAdminInfoReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SysAuthUpdateAdminInfoReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SysAuthUpdateAdminInfoReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SysAuthUpdateAdminInfoReplyValidationError) ErrorName() string {
	return "SysAuthUpdateAdminInfoReplyValidationError"
}

// Error satisfies the builtin error interface
func (e SysAuthUpdateAdminInfoReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSysAuthUpdateAdminInfoReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SysAuthUpdateAdminInfoReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SysAuthUpdateAdminInfoReplyValidationError{}

// Validate checks the field values on SysAuthUpdateAdminPasswordReq with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SysAuthUpdateAdminPasswordReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SysAuthUpdateAdminPasswordReq with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// SysAuthUpdateAdminPasswordReqMultiError, or nil if none found.
func (m *SysAuthUpdateAdminPasswordReq) ValidateAll() error {
	return m.validate(true)
}

func (m *SysAuthUpdateAdminPasswordReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for OldPassword

	// no validation rules for NewPassword

	if len(errors) > 0 {
		return SysAuthUpdateAdminPasswordReqMultiError(errors)
	}

	return nil
}

// SysAuthUpdateAdminPasswordReqMultiError is an error wrapping multiple
// validation errors returned by SysAuthUpdateAdminPasswordReq.ValidateAll()
// if the designated constraints aren't met.
type SysAuthUpdateAdminPasswordReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SysAuthUpdateAdminPasswordReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SysAuthUpdateAdminPasswordReqMultiError) AllErrors() []error { return m }

// SysAuthUpdateAdminPasswordReqValidationError is the validation error
// returned by SysAuthUpdateAdminPasswordReq.Validate if the designated
// constraints aren't met.
type SysAuthUpdateAdminPasswordReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SysAuthUpdateAdminPasswordReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SysAuthUpdateAdminPasswordReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SysAuthUpdateAdminPasswordReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SysAuthUpdateAdminPasswordReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SysAuthUpdateAdminPasswordReqValidationError) ErrorName() string {
	return "SysAuthUpdateAdminPasswordReqValidationError"
}

// Error satisfies the builtin error interface
func (e SysAuthUpdateAdminPasswordReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSysAuthUpdateAdminPasswordReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SysAuthUpdateAdminPasswordReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SysAuthUpdateAdminPasswordReqValidationError{}

// Validate checks the field values on SysAuthUpdateAdminPasswordReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SysAuthUpdateAdminPasswordReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SysAuthUpdateAdminPasswordReply with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// SysAuthUpdateAdminPasswordReplyMultiError, or nil if none found.
func (m *SysAuthUpdateAdminPasswordReply) ValidateAll() error {
	return m.validate(true)
}

func (m *SysAuthUpdateAdminPasswordReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return SysAuthUpdateAdminPasswordReplyMultiError(errors)
	}

	return nil
}

// SysAuthUpdateAdminPasswordReplyMultiError is an error wrapping multiple
// validation errors returned by SysAuthUpdateAdminPasswordReply.ValidateAll()
// if the designated constraints aren't met.
type SysAuthUpdateAdminPasswordReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SysAuthUpdateAdminPasswordReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SysAuthUpdateAdminPasswordReplyMultiError) AllErrors() []error { return m }

// SysAuthUpdateAdminPasswordReplyValidationError is the validation error
// returned by SysAuthUpdateAdminPasswordReply.Validate if the designated
// constraints aren't met.
type SysAuthUpdateAdminPasswordReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SysAuthUpdateAdminPasswordReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SysAuthUpdateAdminPasswordReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SysAuthUpdateAdminPasswordReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SysAuthUpdateAdminPasswordReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SysAuthUpdateAdminPasswordReplyValidationError) ErrorName() string {
	return "SysAuthUpdateAdminPasswordReplyValidationError"
}

// Error satisfies the builtin error interface
func (e SysAuthUpdateAdminPasswordReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSysAuthUpdateAdminPasswordReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SysAuthUpdateAdminPasswordReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SysAuthUpdateAdminPasswordReplyValidationError{}

// Validate checks the field values on SysAuthMenuReq with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *SysAuthMenuReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SysAuthMenuReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in SysAuthMenuReqMultiError,
// or nil if none found.
func (m *SysAuthMenuReq) ValidateAll() error {
	return m.validate(true)
}

func (m *SysAuthMenuReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return SysAuthMenuReqMultiError(errors)
	}

	return nil
}

// SysAuthMenuReqMultiError is an error wrapping multiple validation errors
// returned by SysAuthMenuReq.ValidateAll() if the designated constraints
// aren't met.
type SysAuthMenuReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SysAuthMenuReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SysAuthMenuReqMultiError) AllErrors() []error { return m }

// SysAuthMenuReqValidationError is the validation error returned by
// SysAuthMenuReq.Validate if the designated constraints aren't met.
type SysAuthMenuReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SysAuthMenuReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SysAuthMenuReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SysAuthMenuReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SysAuthMenuReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SysAuthMenuReqValidationError) ErrorName() string { return "SysAuthMenuReqValidationError" }

// Error satisfies the builtin error interface
func (e SysAuthMenuReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSysAuthMenuReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SysAuthMenuReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SysAuthMenuReqValidationError{}

// Validate checks the field values on SysAuthMenuReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *SysAuthMenuReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SysAuthMenuReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SysAuthMenuReplyMultiError, or nil if none found.
func (m *SysAuthMenuReply) ValidateAll() error {
	return m.validate(true)
}

func (m *SysAuthMenuReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetMenu() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, SysAuthMenuReplyValidationError{
						field:  fmt.Sprintf("Menu[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, SysAuthMenuReplyValidationError{
						field:  fmt.Sprintf("Menu[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return SysAuthMenuReplyValidationError{
					field:  fmt.Sprintf("Menu[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return SysAuthMenuReplyMultiError(errors)
	}

	return nil
}

// SysAuthMenuReplyMultiError is an error wrapping multiple validation errors
// returned by SysAuthMenuReply.ValidateAll() if the designated constraints
// aren't met.
type SysAuthMenuReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SysAuthMenuReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SysAuthMenuReplyMultiError) AllErrors() []error { return m }

// SysAuthMenuReplyValidationError is the validation error returned by
// SysAuthMenuReply.Validate if the designated constraints aren't met.
type SysAuthMenuReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SysAuthMenuReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SysAuthMenuReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SysAuthMenuReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SysAuthMenuReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SysAuthMenuReplyValidationError) ErrorName() string { return "SysAuthMenuReplyValidationError" }

// Error satisfies the builtin error interface
func (e SysAuthMenuReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSysAuthMenuReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SysAuthMenuReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SysAuthMenuReplyValidationError{}

// Validate checks the field values on SysAuthPermissionReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SysAuthPermissionReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SysAuthPermissionReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SysAuthPermissionReqMultiError, or nil if none found.
func (m *SysAuthPermissionReq) ValidateAll() error {
	return m.validate(true)
}

func (m *SysAuthPermissionReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return SysAuthPermissionReqMultiError(errors)
	}

	return nil
}

// SysAuthPermissionReqMultiError is an error wrapping multiple validation
// errors returned by SysAuthPermissionReq.ValidateAll() if the designated
// constraints aren't met.
type SysAuthPermissionReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SysAuthPermissionReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SysAuthPermissionReqMultiError) AllErrors() []error { return m }

// SysAuthPermissionReqValidationError is the validation error returned by
// SysAuthPermissionReq.Validate if the designated constraints aren't met.
type SysAuthPermissionReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SysAuthPermissionReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SysAuthPermissionReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SysAuthPermissionReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SysAuthPermissionReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SysAuthPermissionReqValidationError) ErrorName() string {
	return "SysAuthPermissionReqValidationError"
}

// Error satisfies the builtin error interface
func (e SysAuthPermissionReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSysAuthPermissionReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SysAuthPermissionReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SysAuthPermissionReqValidationError{}

// Validate checks the field values on SysAuthPermissionReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SysAuthPermissionReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SysAuthPermissionReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SysAuthPermissionReplyMultiError, or nil if none found.
func (m *SysAuthPermissionReply) ValidateAll() error {
	return m.validate(true)
}

func (m *SysAuthPermissionReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return SysAuthPermissionReplyMultiError(errors)
	}

	return nil
}

// SysAuthPermissionReplyMultiError is an error wrapping multiple validation
// errors returned by SysAuthPermissionReply.ValidateAll() if the designated
// constraints aren't met.
type SysAuthPermissionReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SysAuthPermissionReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SysAuthPermissionReplyMultiError) AllErrors() []error { return m }

// SysAuthPermissionReplyValidationError is the validation error returned by
// SysAuthPermissionReply.Validate if the designated constraints aren't met.
type SysAuthPermissionReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SysAuthPermissionReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SysAuthPermissionReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SysAuthPermissionReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SysAuthPermissionReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SysAuthPermissionReplyValidationError) ErrorName() string {
	return "SysAuthPermissionReplyValidationError"
}

// Error satisfies the builtin error interface
func (e SysAuthPermissionReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSysAuthPermissionReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SysAuthPermissionReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SysAuthPermissionReplyValidationError{}
