// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.5.3
// - protoc             v3.21.9
// source: admin/v1/wx_gzh_auto_reply.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationWxGzhAutoReplyCreateWxGzhAutoReply = "/admin.v1.WxGzhAutoReply/CreateWxGzhAutoReply"
const OperationWxGzhAutoReplyDeleteWxGzhAutoReply = "/admin.v1.WxGzhAutoReply/DeleteWxGzhAutoReply"
const OperationWxGzhAutoReplyGetWxGzhAutoReplyInfo = "/admin.v1.WxGzhAutoReply/GetWxGzhAutoReplyInfo"
const OperationWxGzhAutoReplyGetWxGzhAutoReplyList = "/admin.v1.WxGzhAutoReply/GetWxGzhAutoReplyList"
const OperationWxGzhAutoReplyUpdateWxGzhAutoReply = "/admin.v1.WxGzhAutoReply/UpdateWxGzhAutoReply"
const OperationWxGzhAutoReplyUpdateWxGzhAutoReplyStatus = "/admin.v1.WxGzhAutoReply/UpdateWxGzhAutoReplyStatus"

type WxGzhAutoReplyHTTPServer interface {
	CreateWxGzhAutoReply(context.Context, *CreateWxGzhAutoReplyReq) (*CreateWxGzhAutoReplyReply, error)
	DeleteWxGzhAutoReply(context.Context, *DeleteWxGzhAutoReplyReq) (*DeleteWxGzhAutoReplyReply, error)
	GetWxGzhAutoReplyInfo(context.Context, *GetWxGzhAutoReplyInfoReq) (*GetWxGzhAutoReplyInfoReply, error)
	GetWxGzhAutoReplyList(context.Context, *GetWxGzhAutoReplyListReq) (*GetWxGzhAutoReplyListReply, error)
	UpdateWxGzhAutoReply(context.Context, *UpdateWxGzhAutoReplyReq) (*UpdateWxGzhAutoReplyReply, error)
	UpdateWxGzhAutoReplyStatus(context.Context, *UpdateWxGzhAutoReplyStatusReq) (*UpdateWxGzhAutoReplyStatusReply, error)
}

func RegisterWxGzhAutoReplyHTTPServer(s *http.Server, srv WxGzhAutoReplyHTTPServer) {
	r := s.Route("/")
	r.POST("/admin/v1/wx_gzh_auto_reply/create", _WxGzhAutoReply_CreateWxGzhAutoReply0_HTTP_Handler(srv))
	r.POST("/admin/v1/wx_gzh_auto_reply/update", _WxGzhAutoReply_UpdateWxGzhAutoReply0_HTTP_Handler(srv))
	r.POST("/admin/v1/wx_gzh_auto_reply/update/status", _WxGzhAutoReply_UpdateWxGzhAutoReplyStatus0_HTTP_Handler(srv))
	r.POST("/admin/v1/wx_gzh_auto_reply/delete", _WxGzhAutoReply_DeleteWxGzhAutoReply0_HTTP_Handler(srv))
	r.GET("/admin/v1/wx_gzh_auto_reply/info", _WxGzhAutoReply_GetWxGzhAutoReplyInfo0_HTTP_Handler(srv))
	r.GET("/admin/v1/wx_gzh_auto_reply/list", _WxGzhAutoReply_GetWxGzhAutoReplyList0_HTTP_Handler(srv))
}

func _WxGzhAutoReply_CreateWxGzhAutoReply0_HTTP_Handler(srv WxGzhAutoReplyHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateWxGzhAutoReplyReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationWxGzhAutoReplyCreateWxGzhAutoReply)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateWxGzhAutoReply(ctx, req.(*CreateWxGzhAutoReplyReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateWxGzhAutoReplyReply)
		return ctx.Result(200, reply)
	}
}

func _WxGzhAutoReply_UpdateWxGzhAutoReply0_HTTP_Handler(srv WxGzhAutoReplyHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateWxGzhAutoReplyReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationWxGzhAutoReplyUpdateWxGzhAutoReply)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateWxGzhAutoReply(ctx, req.(*UpdateWxGzhAutoReplyReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateWxGzhAutoReplyReply)
		return ctx.Result(200, reply)
	}
}

func _WxGzhAutoReply_UpdateWxGzhAutoReplyStatus0_HTTP_Handler(srv WxGzhAutoReplyHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateWxGzhAutoReplyStatusReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationWxGzhAutoReplyUpdateWxGzhAutoReplyStatus)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateWxGzhAutoReplyStatus(ctx, req.(*UpdateWxGzhAutoReplyStatusReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateWxGzhAutoReplyStatusReply)
		return ctx.Result(200, reply)
	}
}

func _WxGzhAutoReply_DeleteWxGzhAutoReply0_HTTP_Handler(srv WxGzhAutoReplyHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteWxGzhAutoReplyReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationWxGzhAutoReplyDeleteWxGzhAutoReply)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteWxGzhAutoReply(ctx, req.(*DeleteWxGzhAutoReplyReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteWxGzhAutoReplyReply)
		return ctx.Result(200, reply)
	}
}

func _WxGzhAutoReply_GetWxGzhAutoReplyInfo0_HTTP_Handler(srv WxGzhAutoReplyHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetWxGzhAutoReplyInfoReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationWxGzhAutoReplyGetWxGzhAutoReplyInfo)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetWxGzhAutoReplyInfo(ctx, req.(*GetWxGzhAutoReplyInfoReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetWxGzhAutoReplyInfoReply)
		return ctx.Result(200, reply)
	}
}

func _WxGzhAutoReply_GetWxGzhAutoReplyList0_HTTP_Handler(srv WxGzhAutoReplyHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetWxGzhAutoReplyListReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationWxGzhAutoReplyGetWxGzhAutoReplyList)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetWxGzhAutoReplyList(ctx, req.(*GetWxGzhAutoReplyListReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetWxGzhAutoReplyListReply)
		return ctx.Result(200, reply)
	}
}

type WxGzhAutoReplyHTTPClient interface {
	CreateWxGzhAutoReply(ctx context.Context, req *CreateWxGzhAutoReplyReq, opts ...http.CallOption) (rsp *CreateWxGzhAutoReplyReply, err error)
	DeleteWxGzhAutoReply(ctx context.Context, req *DeleteWxGzhAutoReplyReq, opts ...http.CallOption) (rsp *DeleteWxGzhAutoReplyReply, err error)
	GetWxGzhAutoReplyInfo(ctx context.Context, req *GetWxGzhAutoReplyInfoReq, opts ...http.CallOption) (rsp *GetWxGzhAutoReplyInfoReply, err error)
	GetWxGzhAutoReplyList(ctx context.Context, req *GetWxGzhAutoReplyListReq, opts ...http.CallOption) (rsp *GetWxGzhAutoReplyListReply, err error)
	UpdateWxGzhAutoReply(ctx context.Context, req *UpdateWxGzhAutoReplyReq, opts ...http.CallOption) (rsp *UpdateWxGzhAutoReplyReply, err error)
	UpdateWxGzhAutoReplyStatus(ctx context.Context, req *UpdateWxGzhAutoReplyStatusReq, opts ...http.CallOption) (rsp *UpdateWxGzhAutoReplyStatusReply, err error)
}

type WxGzhAutoReplyHTTPClientImpl struct {
	cc *http.Client
}

func NewWxGzhAutoReplyHTTPClient(client *http.Client) WxGzhAutoReplyHTTPClient {
	return &WxGzhAutoReplyHTTPClientImpl{client}
}

func (c *WxGzhAutoReplyHTTPClientImpl) CreateWxGzhAutoReply(ctx context.Context, in *CreateWxGzhAutoReplyReq, opts ...http.CallOption) (*CreateWxGzhAutoReplyReply, error) {
	var out CreateWxGzhAutoReplyReply
	pattern := "/admin/v1/wx_gzh_auto_reply/create"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationWxGzhAutoReplyCreateWxGzhAutoReply))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *WxGzhAutoReplyHTTPClientImpl) DeleteWxGzhAutoReply(ctx context.Context, in *DeleteWxGzhAutoReplyReq, opts ...http.CallOption) (*DeleteWxGzhAutoReplyReply, error) {
	var out DeleteWxGzhAutoReplyReply
	pattern := "/admin/v1/wx_gzh_auto_reply/delete"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationWxGzhAutoReplyDeleteWxGzhAutoReply))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *WxGzhAutoReplyHTTPClientImpl) GetWxGzhAutoReplyInfo(ctx context.Context, in *GetWxGzhAutoReplyInfoReq, opts ...http.CallOption) (*GetWxGzhAutoReplyInfoReply, error) {
	var out GetWxGzhAutoReplyInfoReply
	pattern := "/admin/v1/wx_gzh_auto_reply/info"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationWxGzhAutoReplyGetWxGzhAutoReplyInfo))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *WxGzhAutoReplyHTTPClientImpl) GetWxGzhAutoReplyList(ctx context.Context, in *GetWxGzhAutoReplyListReq, opts ...http.CallOption) (*GetWxGzhAutoReplyListReply, error) {
	var out GetWxGzhAutoReplyListReply
	pattern := "/admin/v1/wx_gzh_auto_reply/list"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationWxGzhAutoReplyGetWxGzhAutoReplyList))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *WxGzhAutoReplyHTTPClientImpl) UpdateWxGzhAutoReply(ctx context.Context, in *UpdateWxGzhAutoReplyReq, opts ...http.CallOption) (*UpdateWxGzhAutoReplyReply, error) {
	var out UpdateWxGzhAutoReplyReply
	pattern := "/admin/v1/wx_gzh_auto_reply/update"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationWxGzhAutoReplyUpdateWxGzhAutoReply))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *WxGzhAutoReplyHTTPClientImpl) UpdateWxGzhAutoReplyStatus(ctx context.Context, in *UpdateWxGzhAutoReplyStatusReq, opts ...http.CallOption) (*UpdateWxGzhAutoReplyStatusReply, error) {
	var out UpdateWxGzhAutoReplyStatusReply
	pattern := "/admin/v1/wx_gzh_auto_reply/update/status"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationWxGzhAutoReplyUpdateWxGzhAutoReplyStatus))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
