// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: admin/v1/wx_gzh_menu.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on SelfmenuInfo with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *SelfmenuInfo) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SelfmenuInfo with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in SelfmenuInfoMultiError, or
// nil if none found.
func (m *SelfmenuInfo) ValidateAll() error {
	return m.validate(true)
}

func (m *SelfmenuInfo) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetButton() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, SelfmenuInfoValidationError{
						field:  fmt.Sprintf("Button[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, SelfmenuInfoValidationError{
						field:  fmt.Sprintf("Button[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return SelfmenuInfoValidationError{
					field:  fmt.Sprintf("Button[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return SelfmenuInfoMultiError(errors)
	}

	return nil
}

// SelfmenuInfoMultiError is an error wrapping multiple validation errors
// returned by SelfmenuInfo.ValidateAll() if the designated constraints aren't met.
type SelfmenuInfoMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SelfmenuInfoMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SelfmenuInfoMultiError) AllErrors() []error { return m }

// SelfmenuInfoValidationError is the validation error returned by
// SelfmenuInfo.Validate if the designated constraints aren't met.
type SelfmenuInfoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SelfmenuInfoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SelfmenuInfoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SelfmenuInfoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SelfmenuInfoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SelfmenuInfoValidationError) ErrorName() string { return "SelfmenuInfoValidationError" }

// Error satisfies the builtin error interface
func (e SelfmenuInfoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSelfmenuInfo.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SelfmenuInfoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SelfmenuInfoValidationError{}

// Validate checks the field values on WxGzhMenuInfo with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *WxGzhMenuInfo) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on WxGzhMenuInfo with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in WxGzhMenuInfoMultiError, or
// nil if none found.
func (m *WxGzhMenuInfo) ValidateAll() error {
	return m.validate(true)
}

func (m *WxGzhMenuInfo) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for AppId

	// no validation rules for IsMenuOpen

	if all {
		switch v := interface{}(m.GetSelfmenuInfo()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, WxGzhMenuInfoValidationError{
					field:  "SelfmenuInfo",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, WxGzhMenuInfoValidationError{
					field:  "SelfmenuInfo",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetSelfmenuInfo()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return WxGzhMenuInfoValidationError{
				field:  "SelfmenuInfo",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for CreatedAt

	// no validation rules for UpdatedAt

	if len(errors) > 0 {
		return WxGzhMenuInfoMultiError(errors)
	}

	return nil
}

// WxGzhMenuInfoMultiError is an error wrapping multiple validation errors
// returned by WxGzhMenuInfo.ValidateAll() if the designated constraints
// aren't met.
type WxGzhMenuInfoMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m WxGzhMenuInfoMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m WxGzhMenuInfoMultiError) AllErrors() []error { return m }

// WxGzhMenuInfoValidationError is the validation error returned by
// WxGzhMenuInfo.Validate if the designated constraints aren't met.
type WxGzhMenuInfoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e WxGzhMenuInfoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e WxGzhMenuInfoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e WxGzhMenuInfoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e WxGzhMenuInfoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e WxGzhMenuInfoValidationError) ErrorName() string { return "WxGzhMenuInfoValidationError" }

// Error satisfies the builtin error interface
func (e WxGzhMenuInfoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sWxGzhMenuInfo.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = WxGzhMenuInfoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = WxGzhMenuInfoValidationError{}

// Validate checks the field values on StoreWxGzhMenuReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *StoreWxGzhMenuReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on StoreWxGzhMenuReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// StoreWxGzhMenuReqMultiError, or nil if none found.
func (m *StoreWxGzhMenuReq) ValidateAll() error {
	return m.validate(true)
}

func (m *StoreWxGzhMenuReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for AppId

	if all {
		switch v := interface{}(m.GetSelfmenuInfo()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, StoreWxGzhMenuReqValidationError{
					field:  "SelfmenuInfo",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, StoreWxGzhMenuReqValidationError{
					field:  "SelfmenuInfo",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetSelfmenuInfo()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return StoreWxGzhMenuReqValidationError{
				field:  "SelfmenuInfo",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return StoreWxGzhMenuReqMultiError(errors)
	}

	return nil
}

// StoreWxGzhMenuReqMultiError is an error wrapping multiple validation errors
// returned by StoreWxGzhMenuReq.ValidateAll() if the designated constraints
// aren't met.
type StoreWxGzhMenuReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m StoreWxGzhMenuReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m StoreWxGzhMenuReqMultiError) AllErrors() []error { return m }

// StoreWxGzhMenuReqValidationError is the validation error returned by
// StoreWxGzhMenuReq.Validate if the designated constraints aren't met.
type StoreWxGzhMenuReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e StoreWxGzhMenuReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e StoreWxGzhMenuReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e StoreWxGzhMenuReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e StoreWxGzhMenuReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e StoreWxGzhMenuReqValidationError) ErrorName() string {
	return "StoreWxGzhMenuReqValidationError"
}

// Error satisfies the builtin error interface
func (e StoreWxGzhMenuReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sStoreWxGzhMenuReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = StoreWxGzhMenuReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = StoreWxGzhMenuReqValidationError{}

// Validate checks the field values on StoreWxGzhMenuReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *StoreWxGzhMenuReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on StoreWxGzhMenuReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// StoreWxGzhMenuReplyMultiError, or nil if none found.
func (m *StoreWxGzhMenuReply) ValidateAll() error {
	return m.validate(true)
}

func (m *StoreWxGzhMenuReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return StoreWxGzhMenuReplyMultiError(errors)
	}

	return nil
}

// StoreWxGzhMenuReplyMultiError is an error wrapping multiple validation
// errors returned by StoreWxGzhMenuReply.ValidateAll() if the designated
// constraints aren't met.
type StoreWxGzhMenuReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m StoreWxGzhMenuReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m StoreWxGzhMenuReplyMultiError) AllErrors() []error { return m }

// StoreWxGzhMenuReplyValidationError is the validation error returned by
// StoreWxGzhMenuReply.Validate if the designated constraints aren't met.
type StoreWxGzhMenuReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e StoreWxGzhMenuReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e StoreWxGzhMenuReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e StoreWxGzhMenuReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e StoreWxGzhMenuReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e StoreWxGzhMenuReplyValidationError) ErrorName() string {
	return "StoreWxGzhMenuReplyValidationError"
}

// Error satisfies the builtin error interface
func (e StoreWxGzhMenuReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sStoreWxGzhMenuReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = StoreWxGzhMenuReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = StoreWxGzhMenuReplyValidationError{}

// Validate checks the field values on DeleteWxGzhMenuReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteWxGzhMenuReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteWxGzhMenuReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteWxGzhMenuReqMultiError, or nil if none found.
func (m *DeleteWxGzhMenuReq) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteWxGzhMenuReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for AppId

	if len(errors) > 0 {
		return DeleteWxGzhMenuReqMultiError(errors)
	}

	return nil
}

// DeleteWxGzhMenuReqMultiError is an error wrapping multiple validation errors
// returned by DeleteWxGzhMenuReq.ValidateAll() if the designated constraints
// aren't met.
type DeleteWxGzhMenuReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteWxGzhMenuReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteWxGzhMenuReqMultiError) AllErrors() []error { return m }

// DeleteWxGzhMenuReqValidationError is the validation error returned by
// DeleteWxGzhMenuReq.Validate if the designated constraints aren't met.
type DeleteWxGzhMenuReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteWxGzhMenuReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteWxGzhMenuReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteWxGzhMenuReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteWxGzhMenuReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteWxGzhMenuReqValidationError) ErrorName() string {
	return "DeleteWxGzhMenuReqValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteWxGzhMenuReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteWxGzhMenuReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteWxGzhMenuReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteWxGzhMenuReqValidationError{}

// Validate checks the field values on DeleteWxGzhMenuReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteWxGzhMenuReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteWxGzhMenuReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteWxGzhMenuReplyMultiError, or nil if none found.
func (m *DeleteWxGzhMenuReply) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteWxGzhMenuReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return DeleteWxGzhMenuReplyMultiError(errors)
	}

	return nil
}

// DeleteWxGzhMenuReplyMultiError is an error wrapping multiple validation
// errors returned by DeleteWxGzhMenuReply.ValidateAll() if the designated
// constraints aren't met.
type DeleteWxGzhMenuReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteWxGzhMenuReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteWxGzhMenuReplyMultiError) AllErrors() []error { return m }

// DeleteWxGzhMenuReplyValidationError is the validation error returned by
// DeleteWxGzhMenuReply.Validate if the designated constraints aren't met.
type DeleteWxGzhMenuReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteWxGzhMenuReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteWxGzhMenuReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteWxGzhMenuReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteWxGzhMenuReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteWxGzhMenuReplyValidationError) ErrorName() string {
	return "DeleteWxGzhMenuReplyValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteWxGzhMenuReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteWxGzhMenuReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteWxGzhMenuReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteWxGzhMenuReplyValidationError{}

// Validate checks the field values on GetWxGzhMenuInfoReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetWxGzhMenuInfoReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetWxGzhMenuInfoReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetWxGzhMenuInfoReqMultiError, or nil if none found.
func (m *GetWxGzhMenuInfoReq) ValidateAll() error {
	return m.validate(true)
}

func (m *GetWxGzhMenuInfoReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for AppId

	if len(errors) > 0 {
		return GetWxGzhMenuInfoReqMultiError(errors)
	}

	return nil
}

// GetWxGzhMenuInfoReqMultiError is an error wrapping multiple validation
// errors returned by GetWxGzhMenuInfoReq.ValidateAll() if the designated
// constraints aren't met.
type GetWxGzhMenuInfoReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetWxGzhMenuInfoReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetWxGzhMenuInfoReqMultiError) AllErrors() []error { return m }

// GetWxGzhMenuInfoReqValidationError is the validation error returned by
// GetWxGzhMenuInfoReq.Validate if the designated constraints aren't met.
type GetWxGzhMenuInfoReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetWxGzhMenuInfoReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetWxGzhMenuInfoReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetWxGzhMenuInfoReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetWxGzhMenuInfoReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetWxGzhMenuInfoReqValidationError) ErrorName() string {
	return "GetWxGzhMenuInfoReqValidationError"
}

// Error satisfies the builtin error interface
func (e GetWxGzhMenuInfoReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetWxGzhMenuInfoReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetWxGzhMenuInfoReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetWxGzhMenuInfoReqValidationError{}

// Validate checks the field values on GetWxGzhMenuInfoReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetWxGzhMenuInfoReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetWxGzhMenuInfoReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetWxGzhMenuInfoReplyMultiError, or nil if none found.
func (m *GetWxGzhMenuInfoReply) ValidateAll() error {
	return m.validate(true)
}

func (m *GetWxGzhMenuInfoReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetInfo()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetWxGzhMenuInfoReplyValidationError{
					field:  "Info",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetWxGzhMenuInfoReplyValidationError{
					field:  "Info",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetInfo()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetWxGzhMenuInfoReplyValidationError{
				field:  "Info",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetWxGzhMenuInfoReplyMultiError(errors)
	}

	return nil
}

// GetWxGzhMenuInfoReplyMultiError is an error wrapping multiple validation
// errors returned by GetWxGzhMenuInfoReply.ValidateAll() if the designated
// constraints aren't met.
type GetWxGzhMenuInfoReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetWxGzhMenuInfoReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetWxGzhMenuInfoReplyMultiError) AllErrors() []error { return m }

// GetWxGzhMenuInfoReplyValidationError is the validation error returned by
// GetWxGzhMenuInfoReply.Validate if the designated constraints aren't met.
type GetWxGzhMenuInfoReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetWxGzhMenuInfoReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetWxGzhMenuInfoReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetWxGzhMenuInfoReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetWxGzhMenuInfoReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetWxGzhMenuInfoReplyValidationError) ErrorName() string {
	return "GetWxGzhMenuInfoReplyValidationError"
}

// Error satisfies the builtin error interface
func (e GetWxGzhMenuInfoReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetWxGzhMenuInfoReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetWxGzhMenuInfoReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetWxGzhMenuInfoReplyValidationError{}

// Validate checks the field values on GetWxGzhMenuListReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetWxGzhMenuListReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetWxGzhMenuListReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetWxGzhMenuListReqMultiError, or nil if none found.
func (m *GetWxGzhMenuListReq) ValidateAll() error {
	return m.validate(true)
}

func (m *GetWxGzhMenuListReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Page

	// no validation rules for PageSize

	if len(errors) > 0 {
		return GetWxGzhMenuListReqMultiError(errors)
	}

	return nil
}

// GetWxGzhMenuListReqMultiError is an error wrapping multiple validation
// errors returned by GetWxGzhMenuListReq.ValidateAll() if the designated
// constraints aren't met.
type GetWxGzhMenuListReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetWxGzhMenuListReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetWxGzhMenuListReqMultiError) AllErrors() []error { return m }

// GetWxGzhMenuListReqValidationError is the validation error returned by
// GetWxGzhMenuListReq.Validate if the designated constraints aren't met.
type GetWxGzhMenuListReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetWxGzhMenuListReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetWxGzhMenuListReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetWxGzhMenuListReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetWxGzhMenuListReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetWxGzhMenuListReqValidationError) ErrorName() string {
	return "GetWxGzhMenuListReqValidationError"
}

// Error satisfies the builtin error interface
func (e GetWxGzhMenuListReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetWxGzhMenuListReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetWxGzhMenuListReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetWxGzhMenuListReqValidationError{}

// Validate checks the field values on GetWxGzhMenuListReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetWxGzhMenuListReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetWxGzhMenuListReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetWxGzhMenuListReplyMultiError, or nil if none found.
func (m *GetWxGzhMenuListReply) ValidateAll() error {
	return m.validate(true)
}

func (m *GetWxGzhMenuListReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Total

	for idx, item := range m.GetList() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetWxGzhMenuListReplyValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetWxGzhMenuListReplyValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetWxGzhMenuListReplyValidationError{
					field:  fmt.Sprintf("List[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return GetWxGzhMenuListReplyMultiError(errors)
	}

	return nil
}

// GetWxGzhMenuListReplyMultiError is an error wrapping multiple validation
// errors returned by GetWxGzhMenuListReply.ValidateAll() if the designated
// constraints aren't met.
type GetWxGzhMenuListReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetWxGzhMenuListReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetWxGzhMenuListReplyMultiError) AllErrors() []error { return m }

// GetWxGzhMenuListReplyValidationError is the validation error returned by
// GetWxGzhMenuListReply.Validate if the designated constraints aren't met.
type GetWxGzhMenuListReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetWxGzhMenuListReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetWxGzhMenuListReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetWxGzhMenuListReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetWxGzhMenuListReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetWxGzhMenuListReplyValidationError) ErrorName() string {
	return "GetWxGzhMenuListReplyValidationError"
}

// Error satisfies the builtin error interface
func (e GetWxGzhMenuListReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetWxGzhMenuListReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetWxGzhMenuListReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetWxGzhMenuListReplyValidationError{}

// Validate checks the field values on SelfmenuInfo_NewsInfo with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SelfmenuInfo_NewsInfo) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SelfmenuInfo_NewsInfo with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SelfmenuInfo_NewsInfoMultiError, or nil if none found.
func (m *SelfmenuInfo_NewsInfo) ValidateAll() error {
	return m.validate(true)
}

func (m *SelfmenuInfo_NewsInfo) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetList() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, SelfmenuInfo_NewsInfoValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, SelfmenuInfo_NewsInfoValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return SelfmenuInfo_NewsInfoValidationError{
					field:  fmt.Sprintf("List[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return SelfmenuInfo_NewsInfoMultiError(errors)
	}

	return nil
}

// SelfmenuInfo_NewsInfoMultiError is an error wrapping multiple validation
// errors returned by SelfmenuInfo_NewsInfo.ValidateAll() if the designated
// constraints aren't met.
type SelfmenuInfo_NewsInfoMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SelfmenuInfo_NewsInfoMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SelfmenuInfo_NewsInfoMultiError) AllErrors() []error { return m }

// SelfmenuInfo_NewsInfoValidationError is the validation error returned by
// SelfmenuInfo_NewsInfo.Validate if the designated constraints aren't met.
type SelfmenuInfo_NewsInfoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SelfmenuInfo_NewsInfoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SelfmenuInfo_NewsInfoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SelfmenuInfo_NewsInfoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SelfmenuInfo_NewsInfoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SelfmenuInfo_NewsInfoValidationError) ErrorName() string {
	return "SelfmenuInfo_NewsInfoValidationError"
}

// Error satisfies the builtin error interface
func (e SelfmenuInfo_NewsInfoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSelfmenuInfo_NewsInfo.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SelfmenuInfo_NewsInfoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SelfmenuInfo_NewsInfoValidationError{}

// Validate checks the field values on SelfmenuInfo_NewsItem with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SelfmenuInfo_NewsItem) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SelfmenuInfo_NewsItem with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SelfmenuInfo_NewsItemMultiError, or nil if none found.
func (m *SelfmenuInfo_NewsItem) ValidateAll() error {
	return m.validate(true)
}

func (m *SelfmenuInfo_NewsItem) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Title

	// no validation rules for Author

	// no validation rules for Digest

	// no validation rules for ShowCover

	// no validation rules for CoverUrl

	// no validation rules for ContentUrl

	// no validation rules for SourceUrl

	if len(errors) > 0 {
		return SelfmenuInfo_NewsItemMultiError(errors)
	}

	return nil
}

// SelfmenuInfo_NewsItemMultiError is an error wrapping multiple validation
// errors returned by SelfmenuInfo_NewsItem.ValidateAll() if the designated
// constraints aren't met.
type SelfmenuInfo_NewsItemMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SelfmenuInfo_NewsItemMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SelfmenuInfo_NewsItemMultiError) AllErrors() []error { return m }

// SelfmenuInfo_NewsItemValidationError is the validation error returned by
// SelfmenuInfo_NewsItem.Validate if the designated constraints aren't met.
type SelfmenuInfo_NewsItemValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SelfmenuInfo_NewsItemValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SelfmenuInfo_NewsItemValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SelfmenuInfo_NewsItemValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SelfmenuInfo_NewsItemValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SelfmenuInfo_NewsItemValidationError) ErrorName() string {
	return "SelfmenuInfo_NewsItemValidationError"
}

// Error satisfies the builtin error interface
func (e SelfmenuInfo_NewsItemValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSelfmenuInfo_NewsItem.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SelfmenuInfo_NewsItemValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SelfmenuInfo_NewsItemValidationError{}

// Validate checks the field values on SelfmenuInfo_ButtonItem with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SelfmenuInfo_ButtonItem) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SelfmenuInfo_ButtonItem with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SelfmenuInfo_ButtonItemMultiError, or nil if none found.
func (m *SelfmenuInfo_ButtonItem) ValidateAll() error {
	return m.validate(true)
}

func (m *SelfmenuInfo_ButtonItem) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Type

	// no validation rules for Name

	// no validation rules for Url

	// no validation rules for Appid

	// no validation rules for Pagepath

	// no validation rules for Key

	// no validation rules for Value

	if all {
		switch v := interface{}(m.GetNewsInfo()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, SelfmenuInfo_ButtonItemValidationError{
					field:  "NewsInfo",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, SelfmenuInfo_ButtonItemValidationError{
					field:  "NewsInfo",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetNewsInfo()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SelfmenuInfo_ButtonItemValidationError{
				field:  "NewsInfo",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return SelfmenuInfo_ButtonItemMultiError(errors)
	}

	return nil
}

// SelfmenuInfo_ButtonItemMultiError is an error wrapping multiple validation
// errors returned by SelfmenuInfo_ButtonItem.ValidateAll() if the designated
// constraints aren't met.
type SelfmenuInfo_ButtonItemMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SelfmenuInfo_ButtonItemMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SelfmenuInfo_ButtonItemMultiError) AllErrors() []error { return m }

// SelfmenuInfo_ButtonItemValidationError is the validation error returned by
// SelfmenuInfo_ButtonItem.Validate if the designated constraints aren't met.
type SelfmenuInfo_ButtonItemValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SelfmenuInfo_ButtonItemValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SelfmenuInfo_ButtonItemValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SelfmenuInfo_ButtonItemValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SelfmenuInfo_ButtonItemValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SelfmenuInfo_ButtonItemValidationError) ErrorName() string {
	return "SelfmenuInfo_ButtonItemValidationError"
}

// Error satisfies the builtin error interface
func (e SelfmenuInfo_ButtonItemValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSelfmenuInfo_ButtonItem.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SelfmenuInfo_ButtonItemValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SelfmenuInfo_ButtonItemValidationError{}

// Validate checks the field values on SelfmenuInfo_SubButton with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SelfmenuInfo_SubButton) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SelfmenuInfo_SubButton with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SelfmenuInfo_SubButtonMultiError, or nil if none found.
func (m *SelfmenuInfo_SubButton) ValidateAll() error {
	return m.validate(true)
}

func (m *SelfmenuInfo_SubButton) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetList() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, SelfmenuInfo_SubButtonValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, SelfmenuInfo_SubButtonValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return SelfmenuInfo_SubButtonValidationError{
					field:  fmt.Sprintf("List[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return SelfmenuInfo_SubButtonMultiError(errors)
	}

	return nil
}

// SelfmenuInfo_SubButtonMultiError is an error wrapping multiple validation
// errors returned by SelfmenuInfo_SubButton.ValidateAll() if the designated
// constraints aren't met.
type SelfmenuInfo_SubButtonMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SelfmenuInfo_SubButtonMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SelfmenuInfo_SubButtonMultiError) AllErrors() []error { return m }

// SelfmenuInfo_SubButtonValidationError is the validation error returned by
// SelfmenuInfo_SubButton.Validate if the designated constraints aren't met.
type SelfmenuInfo_SubButtonValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SelfmenuInfo_SubButtonValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SelfmenuInfo_SubButtonValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SelfmenuInfo_SubButtonValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SelfmenuInfo_SubButtonValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SelfmenuInfo_SubButtonValidationError) ErrorName() string {
	return "SelfmenuInfo_SubButtonValidationError"
}

// Error satisfies the builtin error interface
func (e SelfmenuInfo_SubButtonValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSelfmenuInfo_SubButton.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SelfmenuInfo_SubButtonValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SelfmenuInfo_SubButtonValidationError{}

// Validate checks the field values on SelfmenuInfo_SelfButton with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SelfmenuInfo_SelfButton) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SelfmenuInfo_SelfButton with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SelfmenuInfo_SelfButtonMultiError, or nil if none found.
func (m *SelfmenuInfo_SelfButton) ValidateAll() error {
	return m.validate(true)
}

func (m *SelfmenuInfo_SelfButton) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Type

	// no validation rules for Name

	// no validation rules for Key

	// no validation rules for Value

	// no validation rules for Url

	if all {
		switch v := interface{}(m.GetSubButton()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, SelfmenuInfo_SelfButtonValidationError{
					field:  "SubButton",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, SelfmenuInfo_SelfButtonValidationError{
					field:  "SubButton",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetSubButton()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SelfmenuInfo_SelfButtonValidationError{
				field:  "SubButton",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return SelfmenuInfo_SelfButtonMultiError(errors)
	}

	return nil
}

// SelfmenuInfo_SelfButtonMultiError is an error wrapping multiple validation
// errors returned by SelfmenuInfo_SelfButton.ValidateAll() if the designated
// constraints aren't met.
type SelfmenuInfo_SelfButtonMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SelfmenuInfo_SelfButtonMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SelfmenuInfo_SelfButtonMultiError) AllErrors() []error { return m }

// SelfmenuInfo_SelfButtonValidationError is the validation error returned by
// SelfmenuInfo_SelfButton.Validate if the designated constraints aren't met.
type SelfmenuInfo_SelfButtonValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SelfmenuInfo_SelfButtonValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SelfmenuInfo_SelfButtonValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SelfmenuInfo_SelfButtonValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SelfmenuInfo_SelfButtonValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SelfmenuInfo_SelfButtonValidationError) ErrorName() string {
	return "SelfmenuInfo_SelfButtonValidationError"
}

// Error satisfies the builtin error interface
func (e SelfmenuInfo_SelfButtonValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSelfmenuInfo_SelfButton.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SelfmenuInfo_SelfButtonValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SelfmenuInfo_SelfButtonValidationError{}
