// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.5.3
// - protoc             v3.21.9
// source: admin/v1/wx_gzh_material.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationWxGzhMaterialDeleteWxGzhMaterial = "/admin.v1.WxGzhMaterial/DeleteWxGzhMaterial"
const OperationWxGzhMaterialGetWxGzhMaterialInfo = "/admin.v1.WxGzhMaterial/GetWxGzhMaterialInfo"
const OperationWxGzhMaterialGetWxGzhMaterialList = "/admin.v1.WxGzhMaterial/GetWxGzhMaterialList"
const OperationWxGzhMaterialGetWxGzhMaterialStats = "/admin.v1.WxGzhMaterial/GetWxGzhMaterialStats"
const OperationWxGzhMaterialSyncWxGzhMaterial = "/admin.v1.WxGzhMaterial/SyncWxGzhMaterial"

type WxGzhMaterialHTTPServer interface {
	DeleteWxGzhMaterial(context.Context, *DeleteWxGzhMaterialReq) (*DeleteWxGzhMaterialReply, error)
	GetWxGzhMaterialInfo(context.Context, *GetWxGzhMaterialInfoReq) (*GetWxGzhMaterialInfoReply, error)
	GetWxGzhMaterialList(context.Context, *GetWxGzhMaterialListReq) (*GetWxGzhMaterialListReply, error)
	GetWxGzhMaterialStats(context.Context, *GetWxGzhMaterialStatsReq) (*GetWxGzhMaterialStatsReply, error)
	SyncWxGzhMaterial(context.Context, *SyncWxGzhMaterialReq) (*SyncWxGzhMaterialReply, error)
}

func RegisterWxGzhMaterialHTTPServer(s *http.Server, srv WxGzhMaterialHTTPServer) {
	r := s.Route("/")
	r.POST("/admin/v1/wx_gzh_material/delete", _WxGzhMaterial_DeleteWxGzhMaterial0_HTTP_Handler(srv))
	r.GET("/admin/v1/wx_gzh_material/info", _WxGzhMaterial_GetWxGzhMaterialInfo0_HTTP_Handler(srv))
	r.GET("/admin/v1/wx_gzh_material/list", _WxGzhMaterial_GetWxGzhMaterialList0_HTTP_Handler(srv))
	r.GET("/admin/v1/wx_gzh_material/stats", _WxGzhMaterial_GetWxGzhMaterialStats0_HTTP_Handler(srv))
	r.POST("/admin/v1/wx_gzh_material/sync", _WxGzhMaterial_SyncWxGzhMaterial0_HTTP_Handler(srv))
}

func _WxGzhMaterial_DeleteWxGzhMaterial0_HTTP_Handler(srv WxGzhMaterialHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteWxGzhMaterialReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationWxGzhMaterialDeleteWxGzhMaterial)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteWxGzhMaterial(ctx, req.(*DeleteWxGzhMaterialReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteWxGzhMaterialReply)
		return ctx.Result(200, reply)
	}
}

func _WxGzhMaterial_GetWxGzhMaterialInfo0_HTTP_Handler(srv WxGzhMaterialHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetWxGzhMaterialInfoReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationWxGzhMaterialGetWxGzhMaterialInfo)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetWxGzhMaterialInfo(ctx, req.(*GetWxGzhMaterialInfoReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetWxGzhMaterialInfoReply)
		return ctx.Result(200, reply)
	}
}

func _WxGzhMaterial_GetWxGzhMaterialList0_HTTP_Handler(srv WxGzhMaterialHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetWxGzhMaterialListReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationWxGzhMaterialGetWxGzhMaterialList)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetWxGzhMaterialList(ctx, req.(*GetWxGzhMaterialListReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetWxGzhMaterialListReply)
		return ctx.Result(200, reply)
	}
}

func _WxGzhMaterial_GetWxGzhMaterialStats0_HTTP_Handler(srv WxGzhMaterialHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetWxGzhMaterialStatsReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationWxGzhMaterialGetWxGzhMaterialStats)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetWxGzhMaterialStats(ctx, req.(*GetWxGzhMaterialStatsReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetWxGzhMaterialStatsReply)
		return ctx.Result(200, reply)
	}
}

func _WxGzhMaterial_SyncWxGzhMaterial0_HTTP_Handler(srv WxGzhMaterialHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SyncWxGzhMaterialReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationWxGzhMaterialSyncWxGzhMaterial)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SyncWxGzhMaterial(ctx, req.(*SyncWxGzhMaterialReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SyncWxGzhMaterialReply)
		return ctx.Result(200, reply)
	}
}

type WxGzhMaterialHTTPClient interface {
	DeleteWxGzhMaterial(ctx context.Context, req *DeleteWxGzhMaterialReq, opts ...http.CallOption) (rsp *DeleteWxGzhMaterialReply, err error)
	GetWxGzhMaterialInfo(ctx context.Context, req *GetWxGzhMaterialInfoReq, opts ...http.CallOption) (rsp *GetWxGzhMaterialInfoReply, err error)
	GetWxGzhMaterialList(ctx context.Context, req *GetWxGzhMaterialListReq, opts ...http.CallOption) (rsp *GetWxGzhMaterialListReply, err error)
	GetWxGzhMaterialStats(ctx context.Context, req *GetWxGzhMaterialStatsReq, opts ...http.CallOption) (rsp *GetWxGzhMaterialStatsReply, err error)
	SyncWxGzhMaterial(ctx context.Context, req *SyncWxGzhMaterialReq, opts ...http.CallOption) (rsp *SyncWxGzhMaterialReply, err error)
}

type WxGzhMaterialHTTPClientImpl struct {
	cc *http.Client
}

func NewWxGzhMaterialHTTPClient(client *http.Client) WxGzhMaterialHTTPClient {
	return &WxGzhMaterialHTTPClientImpl{client}
}

func (c *WxGzhMaterialHTTPClientImpl) DeleteWxGzhMaterial(ctx context.Context, in *DeleteWxGzhMaterialReq, opts ...http.CallOption) (*DeleteWxGzhMaterialReply, error) {
	var out DeleteWxGzhMaterialReply
	pattern := "/admin/v1/wx_gzh_material/delete"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationWxGzhMaterialDeleteWxGzhMaterial))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *WxGzhMaterialHTTPClientImpl) GetWxGzhMaterialInfo(ctx context.Context, in *GetWxGzhMaterialInfoReq, opts ...http.CallOption) (*GetWxGzhMaterialInfoReply, error) {
	var out GetWxGzhMaterialInfoReply
	pattern := "/admin/v1/wx_gzh_material/info"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationWxGzhMaterialGetWxGzhMaterialInfo))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *WxGzhMaterialHTTPClientImpl) GetWxGzhMaterialList(ctx context.Context, in *GetWxGzhMaterialListReq, opts ...http.CallOption) (*GetWxGzhMaterialListReply, error) {
	var out GetWxGzhMaterialListReply
	pattern := "/admin/v1/wx_gzh_material/list"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationWxGzhMaterialGetWxGzhMaterialList))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *WxGzhMaterialHTTPClientImpl) GetWxGzhMaterialStats(ctx context.Context, in *GetWxGzhMaterialStatsReq, opts ...http.CallOption) (*GetWxGzhMaterialStatsReply, error) {
	var out GetWxGzhMaterialStatsReply
	pattern := "/admin/v1/wx_gzh_material/stats"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationWxGzhMaterialGetWxGzhMaterialStats))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *WxGzhMaterialHTTPClientImpl) SyncWxGzhMaterial(ctx context.Context, in *SyncWxGzhMaterialReq, opts ...http.CallOption) (*SyncWxGzhMaterialReply, error) {
	var out SyncWxGzhMaterialReply
	pattern := "/admin/v1/wx_gzh_material/sync"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationWxGzhMaterialSyncWxGzhMaterial))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
