// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package ai_boilerplate_model

import (
	"database/sql"
	"time"

	"gorm.io/datatypes"
	"gorm.io/gorm"
)

const TableNameAiChatConversation = "ai_chat_conversation"

// AiChatConversation mapped from table <ai_chat_conversation>
type AiChatConversation struct {
	ID               string         `gorm:"column:id;type:uuid;primaryKey;default:gen_random_uuid();comment:对话编号" json:"id"`        // 对话编号
	TenantID         string         `gorm:"column:tenant_id;type:character varying(64);not null;comment:租户编号" json:"tenantId"`      // 租户编号
	AdminID          string         `gorm:"column:admin_id;type:character varying(64);not null;comment:用户编号" json:"adminId"`        // 用户编号
	Title            string         `gorm:"column:title;type:character varying(256);not null;comment:对话标题" json:"title"`            // 对话标题
	Pinned           bool           `gorm:"column:pinned;type:boolean;not null;comment:是否置顶" json:"pinned"`                         // 是否置顶
	PinnedTime       sql.NullTime   `gorm:"column:pinned_time;type:timestamp with time zone;comment:置顶时间" json:"pinnedTime"`        // 置顶时间
	PromptSetting    datatypes.JSON `gorm:"column:prompt_setting;type:jsonb;comment:提示词设置" json:"promptSetting"`                    // 提示词设置
	ModelSetting     datatypes.JSON `gorm:"column:model_setting;type:jsonb;comment:模型设置" json:"modelSetting"`                       // 模型设置
	KnowledgeSetting datatypes.JSON `gorm:"column:knowledge_setting;type:jsonb;comment:知识库设置" json:"knowledgeSetting"`              // 知识库设置
	McpSetting       datatypes.JSON `gorm:"column:mcp_setting;type:jsonb;comment:mcp设置" json:"mcpSetting"`                          // mcp设置
	CreatedAt        time.Time      `gorm:"column:created_at;type:timestamp with time zone;not null;comment:创建时间" json:"createdAt"` // 创建时间
	UpdatedAt        time.Time      `gorm:"column:updated_at;type:timestamp with time zone;not null;comment:更新时间" json:"updatedAt"` // 更新时间
	DeletedAt        gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp with time zone;comment:删除时间" json:"deletedAt"`          // 删除时间
}

// TableName AiChatConversation's table name
func (*AiChatConversation) TableName() string {
	return TableNameAiChatConversation
}
