// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package ai_boilerplate_model

import (
	"time"

	"gorm.io/datatypes"
	"gorm.io/gorm"
)

const TableNameSysRole = "sys_role"

// SysRole mapped from table <sys_role>
type SysRole struct {
	ID        string         `gorm:"column:id;type:uuid;primaryKey;default:gen_random_uuid();comment:编号" json:"id"`          // 编号
	TenantID  string         `gorm:"column:tenant_id;type:character varying(64);not null;comment:租户Id" json:"tenantId"`      // 租户Id
	Name      string         `gorm:"column:name;type:character varying(50);not null;comment:名称" json:"name"`                 // 名称
	Remark    string         `gorm:"column:remark;type:character varying(200);comment:备注" json:"remark"`                     // 备注
	DataScope string         `gorm:"column:dataScope;type:character varying(64);not null;comment:数据范围" json:"dataScope"`     // 数据范围
	MenuIds   datatypes.JSON `gorm:"column:menuIds;type:jsonb;comment:菜单" json:"menuIds"`                                    // 菜单
	Sort      int64          `gorm:"column:sort;type:bigint;not null;comment:排序值" json:"sort"`                               // 排序值
	Status    int16          `gorm:"column:status;type:smallint;not null;comment:状态(-1禁用,1开启)" json:"status"`                // 状态(-1禁用,1开启)
	CreatedAt time.Time      `gorm:"column:created_at;type:timestamp with time zone;not null;comment:创建时间" json:"createdAt"` // 创建时间
	UpdatedAt time.Time      `gorm:"column:updated_at;type:timestamp with time zone;not null;comment:更新时间" json:"updatedAt"` // 更新时间
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp with time zone;comment:删除时间" json:"deletedAt"`          // 删除时间
}

// TableName SysRole's table name
func (*SysRole) TableName() string {
	return TableNameSysRole
}
