// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package ai_boilerplate_model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameWxGzhAccount = "wx_gzh_account"

// WxGzhAccount mapped from table <wx_gzh_account>
type WxGzhAccount struct {
	ID             string         `gorm:"column:id;type:uuid;primaryKey;default:gen_random_uuid();comment:编号" json:"id"`          // 编号
	TenantID       string         `gorm:"column:tenant_id;type:character varying(64);not null;comment:租户编号" json:"tenantId"`      // 租户编号
	Name           string         `gorm:"column:name;type:character varying(100);not null;comment:公众号名称" json:"name"`             // 公众号名称
	Account        string         `gorm:"column:account;type:character varying(100);not null;comment:公众号账号" json:"account"`       // 公众号账号
	AppID          string         `gorm:"column:app_id;type:character varying(100);not null;comment:公众号appid" json:"appId"`       // 公众号appid
	AppSecret      string         `gorm:"column:app_secret;type:character varying(100);not null;comment:公众号密钥" json:"appSecret"`  // 公众号密钥
	URL            string         `gorm:"column:url;type:character varying(1000);comment:公众号url" json:"url"`                      // 公众号url
	Token          string         `gorm:"column:token;type:character varying(64);comment:公众号token" json:"token"`                  // 公众号token
	EncodingAesKey string         `gorm:"column:encoding_aes_key;type:character varying(64);comment:加密密钥" json:"encodingAesKey"`  // 加密密钥
	QrCodeURL      string         `gorm:"column:qr_code_url;type:character varying(1000);comment:二维码图片URL" json:"qrCodeUrl"`      // 二维码图片URL
	Remark         string         `gorm:"column:remark;type:character varying(255);comment:备注" json:"remark"`                     // 备注
	CreatedAt      time.Time      `gorm:"column:created_at;type:timestamp with time zone;not null;comment:创建时间" json:"createdAt"` // 创建时间
	UpdatedAt      time.Time      `gorm:"column:updated_at;type:timestamp with time zone;not null;comment:更新时间" json:"updatedAt"` // 更新时间
	DeletedAt      gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp with time zone;comment:删除时间" json:"deletedAt"`          // 删除时间
}

// TableName WxGzhAccount's table name
func (*WxGzhAccount) TableName() string {
	return TableNameWxGzhAccount
}
